### ISSUE TITLE
I can't type chinese in OpenID Title.

### ISSUE THREAD

**Issue by chiyi4488** [zorn-v/nextcloud-social-login#10]
I can't type chinese in OpenID Title. Please fix this Bug. thank you!

**Comment by zorn-v** [comment]
This is not a bug. Provider title must contain only user `uid` compatible characters due internal reasons.

**Comment by chiyi4488** [comment]
OK, but the title can't be Chinese  it's inconvenient.

**Comment by chiyi4488** [comment]
It's good idea. and then?

**Comment by zorn-v** [comment]
Check v1.5.2
