### ISSUE TITLE
[Feature Request]: Custom OIDC parameters

### ISSUE THREAD

**Issue by swe-covis** [zorn-v/nextcloud-social-login#101]
Hi

We'd like to use Azure AD B2C for authentication but it turned out we need to pass the user flow (formerly policy) as an URL parameter.
Would it be possible to add a field for custom parameters in the "Custom Open ID Connect" configuration so we can add the user flow to the authorize URL (e.g. "p=B2C_1A_signin").

As an alternative if you'd check the authorize URL if it contains a question mark and append your query parameters using ampersand in that case we could add our additional parameters using the authorize URL settings.

Best regards
Sebastian

**Comment by zorn-v** [comment]
Authorize url is not sanitized or so. I do not understand your problem.

**Comment by swe-covis** [comment]
Thanks for your answer and sorry for not being clear enough.
The final URL for authorization is currently being built by taking the authorize URL and attaching the query string. As the query string always starts with a question mark in case the authorize URL already includes a query string the resulting URL contains two question marks - one from the parametrized auth URL and one from adding the query string:

Auth-URL: https://my-idp-auth-url?p=my-custom-parameter
Querystring: ?scope=<your-scope&reply-url=...

Result: https://my-idp-auth-url**?**p=my-custom-parameter**?**scope=<your-scope&reply-url=...

**Comment by zorn-v** [comment]
Check v1.16.5

**Comment by swe-covis** [comment]
Thanks for your fast reply! It works now - thanks a lot
