### ISSUE TITLE
Cannot create connection to google account

### ISSUE THREAD

**Issue by christianlupus** [zorn-v/nextcloud-social-login#102]
# Problem description

I have the problem, that I cannot register my google account with my self-hosted nextcloud account. I think I did the needed steps like registering in the named google development site a OAuth Client-ID and put it in the configuration of nextcloud. After a bit of tweaking (and potential typos) I had it running that I could click in the settings of my NC account on the link to attach to my google account. I am shown the "correct" page from google which looks quite promising.

After clicking on the account I am redirected back to NC. I get the URL https://example.com/cloud/index.php/apps/sociallogin/oauth/google?state=XYZ&code=xyz&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&session_state=abc&prompt=consent. The NC is installed in https://example.com/cloud/. I changed a few parameters as I am unsure what these mean and I want to avoid security leakage. They were a few dozen alphanumeric characters or similar.

# What I get

I get a message like this by a 503 status code.
```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

There are no log generated when this site is called.

# What is the desired effect

The page is redirected further such that I am again within my NC and my google account is registered to allow me to login via google later.

Is this URL correct or did I miss some configuration in the google configuration?
What can I do to track down the problem?

**Comment by zorn-v** [comment]
Check added docs for google https://github.com/zorn-v/nextcloud-social-login/blob/master/docs/sso/google.md

**Comment by christianlupus** [comment]
Thank you very much. I will try it out soon.
