### ISSUE TITLE
Could I replace the param client_id with appid?

### ISSUE THREAD

**Issue by flysail** [zorn-v/nextcloud-social-login#104]
Could I replace the param client_id with appid, and how to do this?
Like this
![1565854067637](https://user-images.githubusercontent.com/3145906/63079614-6187a500-bf71-11e9-8d3b-46b947ce7eac.jpg)

**Comment by zorn-v** [comment]
Seems you provider is not follow oauth standards.
Is not https://github.com/zorn-v/nextcloud-social-login/issues/74 issue related ?

**Comment by ywtoly** [comment]
sociallogin\3rdparty\hybridauth\hybridauth\src\Provider\WeChat.php
这个是支持微信了吗？想问一下，想使用这个文件，在哪儿配置，使其生效？

**Comment by ywtoly** [comment]
现在微信wechat已经成为中国使用最多的社交软件之一了，想使用wechat登录NC,因为wechat中的参数是appid,所以后台配置无法适配。看了上面WeChat.php代码，应该是可以的，但是不知道怎么配置，使用这个文件。

**Comment by flysail** [comment]
这个是我之前改的一版，可以用来做微信登录。
你可以和原版比一下，看看改的地方。
[sociallogin 修改微信登录.zip](https://github.com/zorn-v/nextcloud-social-login/files/14851120/sociallogin.zip)
zhe'eg

**Comment by ywtoly** [comment]
> 这个是我之前改的一版，可以用来做微信登录。 你可以和原版比一下，看看改的地方。 [sociallogin 修改微信登录.zip](https://github.com/zorn-v/nextcloud-social-login/files/14851120/sociallogin.zip) zhe'eg

感谢！感觉挺搞笑的，两个中国人，在一个外国网站上进行了交流！
还是非常感谢，我研读一下！

**Comment by ywtoly** [comment]
> 这个是我之前改的一版，可以用来做微信登录。 你可以和原版比一下，看看改的地方。 [sociallogin 修改微信登录.zip](https://github.com/zorn-v/nextcloud-social-login/files/14851120/sociallogin.zip) zhe'eg

感谢！我研读一下。
