### ISSUE TITLE
openID (using Gitlab) login deletes set e-mail in nextcloud

### ISSUE THREAD

**Issue by ochorocho** [zorn-v/nextcloud-social-login#106]
Hey,

i have setup social login to authenticate using my private Gitlab install.
Login works perfekt.

But on each Login, the e-mail address is deleted in nextcloud and the user gets an email saying

```
Email address changed for XXXXXX

Your email address on https://data.domain.com/ was changed by an administrator. If you did not request this, please contact an administrator.
``` 
Settings for the Application in Gitlab:

![Bildschirmfoto 2019-08-16 um 08 41 50](https://user-images.githubusercontent.com/4623070/63148735-69435a00-c002-11e9-964f-36a56e832bfb.png)

Even if i untick the box "Update user profile every login" it deletes the e-mail address set in Nextcloud.

But i like the idea of having the User Profile updated.

**Comment by zorn-v** [comment]
> Even if i untick the box "Update user profile every login" it deletes the e-mail address set in Nextcloud.

Did you click "save" button after untick checkbox ? Just check, it does not change email when update on every login is disabled.

> But i like the idea of having the User Profile updated.

Try to set userinfo url in provider setting like https://gitlab.com/oauth/userinfo to get email from gitlab profile

**Comment by ochorocho** [comment]
1. Works now, you were right. 🤦‍♂ 
2. I had to set a Public email address in Gitlab user settings to get the email in `/oauth/userinfo `, so the social login was able to use that email

Thanks so much!
