### ISSUE TITLE
Group Mapping using "Custom OpenID Connect" (Gitlab)

### ISSUE THREAD

**Issue by ochorocho** [zorn-v/nextcloud-social-login#108]
I have trouble getting  the group mapping to work.

When i add a new Group Mapping what Gitlab-Group do i have to place in the input field?
I tried a groups id or name, but it didn't work.

It set only the "Default Group" after login.

![Bildschirmfoto 2019-08-27 um 10 54 25](https://user-images.githubusercontent.com/4623070/63765729-f4a5d080-c8c9-11e9-8d94-8dce27026091.png)

Do i need to configure anything special in Gitlab/Nextcloud to make the mapping work?

**Comment by zorn-v** [comment]
You MUST specify "groups claim". It is "key" for claim that returned from provider. Check readme )
