### ISSUE TITLE
Nextcloud Sociallogin with nextcloud didn't work

### ISSUE THREAD

**Issue by MrPresidentWhite** [zorn-v/nextcloud-social-login#11]
Hello,

i have an issue with sociallogin with github. if i whant to logging in with sociallogin with github 

this issue appears all the time
![unbenannt1](https://user-images.githubusercontent.com/38688739/39396989-221304bc-4af8-11e8-99a0-63ee18abd3c5.PNG)

and in the Server protocol appears the error message

![unbenannt](https://user-images.githubusercontent.com/38688739/39396995-38025764-4af8-11e8-9465-5a22fa9da0ae.PNG)

my Website is https://aw96.de/nextcloud

**Comment by zorn-v** [comment]
Seems you incorrect configure `redirect_url` in github oauth app. Case of provider in url is important and MUST be `GitHub`
Just copy link of `GitHub` button and paste it as `redirect_url`

**Comment by MrPresidentWhite** [comment]
ok after the update today the error didn't appears again but now it appear's this error:
![unbenannt](https://user-images.githubusercontent.com/38688739/39571427-bc42b592-4ecb-11e8-8cdc-916671317831.PNG)

Sorry for my bad english ^^

**Comment by zorn-v** [comment]
Read carefully my prev message. There is NO provider `github`, but `GitHub` there is.
You should update `Authorization callback URL` in your github app. You can set only domain there AFAIK (`https://aw96.de` in your case)

**Comment by MrPresidentWhite** [comment]
i just fixed it. I did not think about the case of capitalization in the redirect_url

**Comment by zorn-v** [comment]
> i just fixed it

Yep, I tested it on your server and close issue :wink: 
Urls always was case sensitive.

**Comment by MrPresidentWhite** [comment]
thank you for the help. i have deleted youre account on my server because i configured that nextcloud creates a new account

**Comment by zorn-v** [comment]
No problem
