### ISSUE TITLE
Documentation on how to setup Google SSO

### ISSUE THREAD

**Issue by josephdpurcell** [zorn-v/nextcloud-social-login#110]
# Problem / Motivation

It's unclear how to setup Google as a SSO provider. Yes, I see it's "supported" but that's not equivalent to "easy" or "obvious" setup.

This ticket is intended to help drive towards a more "easy" or more "obvious" setup than is currently available.

# Proposed Solution

Add documentation or an example that explains step-by-step how to achieve Google SSO integration.

**Comment by josephdpurcell** [comment]
Related to https://github.com/zorn-v/nextcloud-social-login/issues/102

**Comment by josephdpurcell** [comment]
# Attempt 1 at explaining setup

This is the first attempt I'll make at explaining how to do a setup of Google SSO from start to finish:

1. Install the app
    1. Login to your nextcloud as an admin
    2. Click "+ Apps" in the menu
    3. Click the "Integrations" tab and find "Social Login"
    4. Click "Download and enable"
2. Setup a Google Authorized Domain
    1. Go to Google Webmaster Tools: https://www.google.com/webmasters/tools/
    2. Click "Add Property" and enter the full domain that your NextCloud will be accessible at, e.g. example.com
    3. Verify your site ownership via the various methods shown here https://support.google.com/webmasters/answer/9008080?visit_id=637032436952938937-2175615075&rd=1
    4. Wait a while.
    5. Confirm that in Google Webmaster Tools you see the property (i.e. domain) you've entered is verified
3. Setup a Google app
    1. Go to https://console.developers.google.com/
    2. Click the list of projects at the top then "New project"
    3. Enter whatever project name you want, no need to specify an org; click "Create"
    4. Click "Create credentials" then click "OAuth client ID"
    5. Click "Configure consent screen"
    6. Enter values:
        * Application name: something relevant
        * Authorized domains: example.com (then hit ENTER; see setup of authorized domains if there's an error)
    7. Click "Save"
    8. Click "Web application" for application type and enter values:
        * Name: something relevant
        * Authorized JavaScript origins: https://example.com (then hit ENTER; see setup of authorized domains if there's an error)
        * Authorized redirect URIs: https://example.com (then hit ENTER; see setup of authorized domains if there's an error)
    9. Click "Save"
    10. You should see a "client ID" and "client secret"; store these somewhere safe
4. Configure "Social Login" in NextCloud
    1. Click "Settings" in the menu
    2. Under Administration click "Social login"
    3. In the bottom section under "Google" enter:
        * App id: the "client ID" provided earlier
        * Secret: the "client secret" provided earlier
        * Default group: "admin" or whatever user group you want new users assigned to
        * Allow login only from specified domain: (you can leave this blank)
    4. Click "Save" at the very bottom
5. Now, open up a new browser to test the login. On the login screen you should now see "Google" underneath the typical NextCloud login prompt.

**Comment by josephdpurcell** [comment]
I've created https://github.com/zorn-v/nextcloud-social-login/pull/111

The intent of it is to capture the above in a doc within the project code base. The upside is the documentation is available wherever the code is. The downside is the steps to setup and configure SSO providers will change over time and the documentation would need to be updated with it, which requires code changes. I think this is a reasonable expectation of a community project -- it enables collaboration and contributions.

I'm happy to change direction on the solution as well. Ultimately, I just wanted to submit back some info that I thought wasn't quite obvious when I was going through it.

**Comment by josephdpurcell** [comment]
Whoops. Wrong button. I didn't mean to close.

**Comment by josephdpurcell** [comment]
Note: it looks like other NextCloud apps also make use of a `docs` directory, e.g. https://github.com/nextcloud/news/tree/master/docs.

**Comment by cahya-wirawan** [comment]
Hi,
Thanks for the documentation to setup the Google SSO. However, I am stuck at the step:
`3. viii: Click "Web application" for application type and enter values`. I just can't find where this "Web application" button is.
Thanks again
