### ISSUE TITLE
Pruning unavailable groups ignores the last group a user is in

### ISSUE THREAD

**Issue by rysiekpl** [zorn-v/nextcloud-social-login#117]
Seems like there's a bug in how pruning unavailable groups works - it seems to ignore the last group a user is in.

That is, if the user is in groups `provider1-group1` and `provider1-group2`, and `provider1-group1` is removed on the IdP side, the user correctly ends up only in `provider1-group2` upon new login.

If now `provider1-group2` is also removed in IdP, the user is *not* removed from that group in Nextcloud upon new login.

If a user is in multiple groups and is removed from all of them at once on the IdP side, the user is *not* removed from *any* groups in Nextcloud upon new login.

Seems like empty group claim is not handled correctly in these cases.

**Comment by zorn-v** [comment]
Can you build docker image for idP to reproduce bug ?

**Comment by rysiekpl** [comment]
That might be too much work, sorry. But from my looking at the code and responses of Keycloak (our IdP), it seems that if there are no roles for a given user in Keycloak, the whole claim is not returned at all in the token.

Looks like this line of code *assumes* that the relevant groups claim is always present (even if empty):
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L369

The logic here means that if IdP does not return the configured groups scope, the whole block is ignored (and thus groups are not updated at all). Perhaps the logic should be changed to also check if group claim is configured, and if so a missing group claim should be interpreted as the user not being part of any groups?

**Comment by rysiekpl** [comment]
Looks like the sanest way to change the logic would be here:
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOAuth2.php#L62

The idea would be to check if `groups_claim` config setting is non-empty, and if so always return an array - since that means the group claim is *expected* to be there (and if it isn't there, that just means the user is in no groups).

**Comment by rysiekpl** [comment]
There are also assumptions made here:
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L38
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L65

The assumption is: if the group data evaluates to `false`, then there is no group data (which might be different than "the user is in no groups").

**Comment by zorn-v** [comment]
Oh, seems I got. Your idP does not return "empty array" if no roles. 
No empty array, no roles claim. I dont know, is it empty, or error in config (bad name for roles claim for example).
So problem in your side :smile:

**Comment by rysiekpl** [comment]
> Oh, seems I got. Your idP does not return "empty array" if no roles.

Correct.

>  I dont know, is it empty, or error in config (bad name for roles claim for example).

Sure. But if it's an error in the config, the admin should notice and fix it. That should not inform implementation. And if a group claim config setting is not empty, we *know* we're supposed to expect the group claim. So reacting to this and removing the user makes it *easier* for admin to debug the issue.

> So problem in your side

Well, appreciate your feedback here very much. In response, I provided a pull request. I'd appreciate your thoughts on it.

**Comment by rysiekpl** [comment]
> Oh, seems I got. Your idP does not return "empty array" if no roles.

One more thing -- from my reading of the original code, the bug would have existed also with an "empty array" returned when no roles are assigned for the user.

Specifically:

1. this `if` would evaluate to `false`, and so `null` would have been returned by `getGroups()`:  
   - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOAuth2.php#L65
1. even if an empty array was returned by `getGroups()`, these would evaluate to `false` too:  
    - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L38
    - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L65
1. even if that were not the case and the empty array was passed on all the way to this spot, `empty($profile->data['groups'])` would have evaluated to `true` here, and so the whole block that updates the groups would have been skipped:  
    - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L369

So it doesn't really seem like, as you put it, a "problem on my side"...

**Comment by zorn-v** [comment]
> the admin should notice and fix it

You are right. Need something like warning in log.

**Comment by rysiekpl** [comment]
> You are right. Need something like warning in log.

Yup, that would be a very good idea. Something like:
> "No groups claim found in response but groups claim name configured; removing user from all groups."

**Comment by rysiekpl** [comment]
Tested with the latest codebase, the issue exists -- although I have no way of testing against an IdP that sends an empty group claims (as opposed to omitting it when empty).

However, looking how the only change is in [`LoginController.php`](https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L369), I would assume that these two lines would still cause the bug to exist *even if IdP sends an empty groups claim*:
 - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L38
 - https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L65

**Comment by rysiekpl** [comment]
Additionally, it seems like for some reason if group mapping and `Restrict login for users without mapped groups` are set, then the user is (correctly!) not let in even if IdP does not send a groups claim (but, the user is *still not removed* from their groups).

So, apparently an missing groups claim is treated differently depending on group mapping being set or not. If it isn't, a missing groups claim means "we have no info on groups", if it is, it seems to mean "assuming the user is not a member of any groups".

This is very confusing.

**Comment by zorn-v** [comment]
> still cause the bug to exist even if IdP sends an empty groups claim

Check with latest commit https://github.com/zorn-v/nextcloud-social-login/commit/fd0173d4f6a4a89088ba58cc77faf3d05a61fee3

**Comment by rysiekpl** [comment]
> Seems I "fix" confusing behavior in v2.0.3

I can confirm the fix in `v2.0.3` works and groups are pruned when no groups claim is provided by IdP. Thank you for the fix!
