### ISSUE TITLE
"Restrict login for users without mapped groups" doesn't seem to work

### ISSUE THREAD

**Issue by rysiekpl** [zorn-v/nextcloud-social-login#118]
In our testing the `Restrict login for users without mapped groups` setting does not seem to do anything. We have tested 3 scenarios (both creating new users and `Restrict login for users without mapped groups` are **enabled** in all three):

1. User *does not exist in Nextcloud*, but *exists in IdP*; is not a member of any groups on the IdP side.
**Result:** upon login, an account is created, login succeeds
1. User *exists in Nextcloud*, and *exists in IdP*; user *was* a member of a few groups on the IdP side (and thus in Nextcloud), but the user was removed from all of them on IdP side.
**Result:** login succeeds, user is not removed from some groups on Nextcloud side (related bug: #117 )
1. User *exists in Nextcloud*, and *exists in IdP*; user *was* a member of a few groups on the IdP side (and thus in Nextcloud), but the user was removed from all of them on IdP side, *and manually on Nextcloud side*.
**Result:** login succeeds

In all of these scenarios I would expect the logins (and account creation in `1.`) to fail.

**Comment by zorn-v** [comment]
This option works only if some group mapping is defined for provider. 
You are welcome to update docs :wink:

**Comment by rysiekpl** [comment]
Oh, you mean when an *explicit* group mapping is defined? Then I do not understand what this option does. Can you elaborate?

**Comment by zorn-v** [comment]
Yep 
https://github.com/zorn-v/nextcloud-social-login/blob/bda18baf1b5b55e11c849f499a17d9ab9191b6a4/lib/Controller/LoginController.php#L327

Actually this option should be in provider setting and disabled without mapped groups, but...

Main idea is - you should *explicit* define groups what you need.

**Comment by rysiekpl** [comment]
So, a user is blocked from logging-in only if:
1. `restrict_users_wo_mapped_groups` is enabled, *and*
1. some group mappings are set, *and*
1. the user is in none of the mapped groups.

Is that correct?

if so, what is the rationale behind not making this just a general setting to disable logins of users who are in no groups, and then a more specific setting of limiting these groups only to mapped groups?

**Comment by zorn-v** [comment]
Backward compatibility :wink: 

Imagine update in with no one can not login :smile:

**Comment by rysiekpl** [comment]
Yeah, that's not great. ;)

On the other hand, from the security standpoint, failsafe is a thing... I wonder if there's a way to square that circle.

**Comment by zorn-v** [comment]
Actually that was "ordered feature". And customer was happy with implementation :smiley:

**Comment by rysiekpl** [comment]
Thanks for your feedback. I guess you can close the issue, although I still see the way this setting acts as weird.

**Comment by zorn-v** [comment]
> I guess you can close the issue

You can close too as "author" )

> I still see the way this setting acts as weird.

Yep, I too ) But no time (or lazy) to fix it.
