### ISSUE TITLE
Undefined variable: title at /server/apps/sociallogin/lib/Controller/SettingsController.php#101

### ISSUE THREAD

**Issue by dartcafe** [zorn-v/nextcloud-social-login#12]
https://github.com/zorn-v/nextcloud-social-login/blob/4d308ae2f2824d279ffdb438ace062eb42ff8dfa/lib/Controller/SettingsController.php#L101

Error in log (debug level)

**Comment by zorn-v** [comment]
Fix it tommorrow )
