### ISSUE TITLE
Unable to login using custom OIDC on Nextcloud 17.0.0 Beta 4

### ISSUE THREAD

**Issue by hukoeth** [zorn-v/nextcloud-social-login#120]
Hi,
Not sure if this is an issue with my setup or the Server or this plugin so appologies if this belongs somewhere else.
While testing Nextcloud 17.0.0 Beta 4 I noticed that I can't login using my custom keycloak OIDC provider.
The server log show following error:

[index] Error: Exception: Argument 2 passed to OC\User\Events\PostLoginEvent::__construct() must be of the type string, null given, called in /var/www/public/lib/private/User/Session.php on line 381 at <<closure>>

0. /var/www/public/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\SocialLogin\ ... {}, "customOidc")
1. /var/www/public/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\SocialLogi ... r", "customOidc", OC\AppFramework\ ... {}, {provider: "kiot ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({provider: "kiot ... "})
3. /var/www/public/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {provider: "kiot ... "})
4. /var/www/public/lib/base.php line 1000
   OC\Route\Router->match("/apps/sociallog ... o")
5. /var/www/public/index.php line 42
   OC::handleRequest()

GET /apps/sociallogin/custom_oidc/custom-oidc?state=[...]

**Comment by zorn-v** [comment]
Fixed in v2.0.1
