### ISSUE TITLE
Telegram auth style error

### ISSUE THREAD

**Issue by hibryid** [zorn-v/nextcloud-social-login#123]
Hello!
nextcloud 16.0.4
nginx + php7.3

Reinstalled my nextcloud and now, even connecting my old bot with the same settings to my cloud gives this error and no widget on login page:
Path is correct

`Undefined index: style at /var/www/html/apps/sociallogin/templates/admin.php#360`

`{"reqId":"Wb6AZ4104tM3sYuimZQK","level":3,"time":"2019-09-21T09:31:54+00:00","remoteAddr":"*","user":"admin","app":"PHP","method":"GET","url":"/settings/admin/sociallogin","message":"Undefined index: style at /var/www/html/apps/sociallogin/templates/admin.php#360","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"16.0.4.1","id":"*"}`

As I see, it also can't define user group:
Undefined index: defaultGroup at /var/www/html/apps/sociallogin/templates/admin.php#295

**Comment by zorn-v** [comment]
I cannot get those errors on my instance. And as I can see from source code it is not related to telegram. Need to add some checks after https://github.com/zorn-v/nextcloud-social-login/pull/109 I think

Try to click on "save" button in socialligin settings and check again.

**Comment by hibryid** [comment]
I have installed version 1.6.x, it works fine.
One day I will be able to check it on testing server, thanks

**Comment by zorn-v** [comment]
Походу из за блокировок было )
