### ISSUE TITLE
Disable Notify Admins on User Create

### ISSUE THREAD

**Issue by gary-kim** [zorn-v/nextcloud-social-login#125]
First of all, thank you for this app, it is very useful.

It would be nice if there was a way to disable to automatic email on new user creation for admins which isn't necessary when you have already limited the accounts that can create new accounts.

Individually per admin would be best but globally would be good as well.

EDIT: I'm a bit too busy to send in a PR at the moment. I can come back to this later if there hasn't been any progress.

**Comment by zorn-v** [comment]
Check v2.2.0

**Comment by gary-kim** [comment]
Thank you!
