### ISSUE TITLE
Allow login only from specified domain

### ISSUE THREAD

**Issue by febrianto-mikatasa** [zorn-v/nextcloud-social-login#126]
Hi, when i read your documentation, i found this part

Details about "Allow login only from specified domain" google setting you can find here #44 You can use comma separated list for multiple domains

but, when i tried to add comma separated list for multiple domains (domain1.com,domain2.com). I can login with domain1.com account, but  i'd got error Login from domain2.com  "domain is not allowed for google provider"

**Comment by zorn-v** [comment]
Just tested and all works fine. Check input field for additional characters like space etc.

**Comment by febrianto-mikatasa** [comment]
this is my input :
domain1.com,domain2.com

**Comment by febrianto-mikatasa** [comment]
> Just tested and all works fine. Check input field for additional characters like space etc.
my bad, i have tried to delete all values and write it again, and now everything is works fine.
thanks
