### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by karl-in-office** [zorn-v/nextcloud-social-login#127]
We have to use HTTP proxy between Nextcloud and OpenID server. 
Currently we manually patch to:
https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Adapter/OpenID.php#L71

Do you have any plans to support HTTP proxy?

**Comment by zorn-v** [comment]
It is related to hybridauth lib (https://github.com/hybridauth/hybridauth) first. But anyway I think it is VERY RARE case to complicate things.

**Comment by karl-in-office** [comment]
Noted.
I’ll patching up by myself so far.
