### ISSUE TITLE
Can't delete custom OAuth2 Configuration

### ISSUE THREAD

**Issue by MatthiasLohr** [zorn-v/nextcloud-social-login#129]
Hi,

I'm trying to delete a custom configured OAuth2 provider. The "x" button (I assume it's for deletion) does not work. At Chrome's console, I get the following error:
```
Uncaught ReferenceError: OCdialogs is not defined
    at HTMLDivElement.<anonymous> (settings.js?v=1a7efc60-0:46)
    at HTMLDivElement.dispatch (jquery.js:4435)
    at HTMLDivElement._.handle (jquery.js:4121)
```

Any idea?

* Nextcloud: 17.0.0
* Social Login: 2.2.0

Best regards
Matthias Lohr

**Comment by zorn-v** [comment]
Check v2.2.1

**Comment by MatthiasLohr** [comment]
Works!

Thank you for fixing so fast!
