### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by edvanleeuwen** [zorn-v/nextcloud-social-login#130]
I have just upgraded and tried to login. I am faced with the following error:

![image](https://user-images.githubusercontent.com/7131152/66854239-46d9a880-ef81-11e9-8564-e487841592a6.png)

What can I do?

**Comment by zorn-v** [comment]
It is not related to sociallogin app.

**Comment by edvanleeuwen** [comment]
Ok, sorry for that.
