### ISSUE TITLE
Limiting discord login to specific guild

### ISSUE THREAD

**Issue by LJNIC** [zorn-v/nextcloud-social-login#132]
It seems weird that anyone can login through Discord. It would be nice to have a way to only allow people from a specific guild to join. How difficult would this be to implement? I may try implement it myself but I'm no PHP wizard.

**Comment by zorn-v** [comment]
I doubt that discord provides such info in response, but maybe I'm wrong

**Comment by LJNIC** [comment]
You could check if they're part of the guild with an API call couldn't you?

**Comment by Novae7** [comment]
Its build in by default as possible response in the OAuth2 already, so if requested the Discord replys with the Guilds (servers)
Maybe an check on the nextcloud/plugin side if the joined guilds/servers contains server xyz -> allow register/login could be possible?

![grafik](https://user-images.githubusercontent.com/2822685/68986510-55d1a600-0820-11ea-9c4b-362a3b7154ff.png)

**Comment by zorn-v** [comment]
Well, you can try to create custom oauth provider and play around with "groups" feature.

**Comment by LJNIC** [comment]
After looking into it a bit the other day, it's not worth it for me to learn PHP and spend hours setting up a local environment to implement this. Although, #134 might do what I want. Just wanted some way to restrict anyone with discord from logging in.

**Comment by Novae7** [comment]
> 
> 
> Well, you can try to create custom oauth provider and play around with "groups" feature.

I think I'll take an look into this.

for now I'll run also with #134 as an solution in the short run.

are the Discord UserIDs compatible when i switch the oauth? should so, as they are getting the same result back even when i use an custom OAuth or Im wrong with this assumption?

**Comment by zorn-v** [comment]
> are the Discord UserIDs compatible when i switch the oauth?

Should be if you use "discord" as internal name. But maybe you should remove (empty fields) built in discord provider.

**Comment by Fardilha** [comment]
Hi all.
Just want to add my "me too" on restrict users to be able to login if they came form a specific chat / guild.
Otherwise this is just do dangerous.

Thanks!

**Comment by suprovsky** [comment]
I think good way of managing it would be to make some allow list for Discord user IDs allowed to use the login flow. What do you think about that?

**Comment by pktiuk** [comment]
Are there any plans of implementing this functionality?

**Comment by JuanjoNuevo** [comment]
@zorn-v just looking into this, and google a bit, not a pro from php but, there is a method on the oauth api from discord that returns the guilds/groups that a user is member of:

Get Current User Guilds: (https://discord.com/developers/docs/resources/user#get-current-user-guilds)

GET/users/@me/guilds
Returns a list of partial guild objects the current user is a member of. Requires the guilds OAuth2 scope.

Example Partial Guild
{
  "id": "80351110224678912",
  "name": "1337 Krew",
  "icon": "8342729096ea3675442027381ff50dfe",
  "owner": true,
  "permissions": "36953089",
  "features": ["COMMUNITY", "NEWS"]
}

This endpoint returns 200 guilds by default, which is the maximum number of guilds a non-bot user can join. Therefore, pagination is not needed for integrations that need to get a list of the users' guilds.

If a user is not member of that guild ID, user cannot access on nextcloud with the login.

**Comment by JuanjoNuevo** [comment]
Not an expert, some part of the code is written on C++ cause i don't have any idea of this...

public function getUserProfile()
    {
        $response = $this->apiRequest('users/@me');

        $response2 = $this->apiRequest('users/@me/guilds');

        $data2 = new Data\Collection($response2);

        $data = new Data\Collection($response);

        if (!$data->exists('id')) {
            throw new UnexpectedApiResponseException('Provider API returned an unexpected response.');
        }

        // DON'T KNOW HOW TO MAKE THIS LOOP ON THIS CODE, SO I PUT IT ON C++ sorry about that....
	for (n=0;n<data2.sizeof();n++) {

        if (!$data2[n]->exists('id')) {
	    throw new UnexpectedApiResponseException('User is not member of any guild.');
	}
	else {
	    if (data2[n].id!="id-given-on-configuration-social-login-app") {
	         throw new UnexpectedApiResponseException('User is not member of the guild.');
	    }
	}

        //finish of my code....
	}

        // Makes display name more unique.
        $displayName = $data->get('username') ?: $data->get('login');
        if ($discriminator = $data->get('discriminator')) {
            $displayName .= "#{$discriminator}";
        }

**Comment by zorn-v** [comment]
Actually changes should be done somewhere in `OCA\SocialLogin\Service\ProviderService`. 
Also there is need to override standard hybridauth scope with adding `guilds`

Can you invite me to some guild on discord that I can test responses from discord api ?
zorn#0865

**Comment by zorn-v** [comment]
Interesting things - everyone need something. But when I ask something that will help do it -nobody here )
Same was with AppleID.

**Comment by JuanjoNuevo** [comment]
Sorry for the late response, i will add you right know, i've been bussy as i'm working as a database manager for a company in expansion and i'm finish my studies too. My discord is Juan José#2593 i will create a discord server for testing and let's see if we can make it run!!

**Comment by JuanjoNuevo** [comment]
https://discord.gg/HJua7XpqBu This is the invite for the guild of Discord, tried to send you a message but as you don't have me added, you couldn't receive that message.

**Comment by zorn-v** [comment]
Check v4.12.0

**Comment by suprovsky** [comment]
The tag/release seem to not exist yet.

**Comment by JuanjoNuevo** [comment]
@suprovsky it appears, just you don't know where to search :P look the commits from 4.11...... and u will find. Thanks @zorn-v , i'll check right now

**Comment by JuanjoNuevo** [comment]
@zorn-v  Look pretty strong, have you tried the changes?, i will try using new version let's see if it runs

**Comment by JuanjoNuevo** [comment]
![image](https://user-images.githubusercontent.com/58025382/155560401-8567ac2b-c192-4513-8af8-d122bb9fb545.png)
WORKS LIKE A CHARM @zorn-v !!!!!

**Comment by JuanjoNuevo** [comment]
you are awesome!!! If you need to translate the message or something, it would be great. One more thing, maybe is posible, maybe not. If it would be posible to make the message "Login is only available to members of the following Discord guilds: " and put the real name of the guild instead the ID of the guild, that would be pretty much it. i will look into the way to obtain the name of the guild from the id

**Comment by zorn-v** [comment]
> The tag/release seem to not exist yet.

Yep, forget to release it :)

> and put the real name of the guild instead the ID of the guild

I think it is not so necessary - it need to do several additional requests, just for get names.

**Comment by pktiuk** [comment]
This feature is implemented, released and works very well.  
Why is this issue still opened?
