### ISSUE TITLE
Enable further OAuth providers

### ISSUE THREAD

**Issue by bergernetch** [zorn-v/nextcloud-social-login#133]
How can I enable further OAuth Providers from 3rdparty/hybridauth/hybridauth/src/Provider/?

**Comment by zorn-v** [comment]
Just request. There some work needed like add proper icons, styles etc.
OR just use custom oidc/oauth provider

**Comment by bergernetch** [comment]
Well, I need a custom one that is not available yet. The problem is that it requires multiple calls to the API to get the fields like the groups. It is not a standard IDP, so not a standard solution.

I modified CustomOAuth2.php and added the necessary calls with the parsing. This works for me.

Thank you.
