### ISSUE TITLE
Programmatically add custom oAuth2 provider

### ISSUE THREAD

**Issue by mbassiouny33** [zorn-v/nextcloud-social-login#135]
Hello,

I'm using Nextcloud and I have a custom Keycloack server for login. I tried your app and it worked like a charm but the only issue for me is having to go to the web interface to configure the provider.

We install multiple instances on multiple servers with a set of docker-compose commands and even the client in Keycloak is created via CLI.

I was wondering if there's a way to automate the configuration for your app without having to go to the interface. Like manually creating a config file, modify existing config files with some regex and pattern matching, or even manually altering the database.

Thanks in advance for your help and for this great plugin

**Comment by zorn-v** [comment]
Config stored in `*PREFIX*appconfig` table (default prefix is `oc_`)
You can check it like `SELECT * FROM oc_appconfig WHERE appid = 'sociallogin'`
`custom_oauth2_providers` (or maybe `custom_oidc_providers`) configkey is what you need.

Config values for providers is json encoded

**Comment by mbassiouny33** [comment]
Thanks a lot for you help! I will give it a try today/tomorrow and get back to you.

**Comment by mbassiouny33** [comment]
Hey,

Thanks a lot for the hint.

I compared the database before and after configuring the plugin and I figured out the settings I need to manually add.

Just in case anyone is looking for this, I had to manually insert these lines for oAuth to work.

> 
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'allow_login_connect', '');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'auto_create_groups', '');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'create_disabled_users', '');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'custom_oauth2_providers', '[]');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'custom_oidc_providers', '[{"name":"internal_keycloack","title":"keycloack","authorizeUrl":"https:\/\/ouath.domain.me:9045\/access\/ouath\/authurl","tokenUrl":"https:\/\/oauth.domain.me:9045\/access\/ouath\/token","userInfoUrl":"","logoutUrl":"","clientId":"nextcloud_client","clientSecret":"382173891dsd_28372813798127","scope":"openid","groupsClaim":"","style":"","defaultGroup":""}]');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'disable_registration', '');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'no_prune_user_groups', '');
> INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('sociallogin', 'openid_providers', '[]');

(replace urls with your reals urls, same for client id and secret )
