### ISSUE TITLE
Facebook URL Blocked.. help me please

### ISSUE THREAD

**Issue by bulzipke** [zorn-v/nextcloud-social-login#136]
Hi, 

I get the following error:

```
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
```

My settings (Basics) in Facebook are:
- App Domains: cloud.bulzipke.com
- Site URL for website: https://cloud.bulzipke.com/

In the advanced tab, Valid OAuth redirect URIs is set to:
https://cloud.bulzipke.com/apps/sociallogin/oauth/facebook
https://cloud.bulzipke.com/index.php/apps/sociallogin/oauth/facebook

I have referenced the [link](https://github.com/zorn-v/nextcloud-social-login/blob/master/docs/sso/facebook.md?fbclid=IwAR1l6Zv1rSBBzUxeiZ4yATskS22I74jzOjOSobfF1oU0Z5Lum12AiBuGxcE), but it doesn't work.
What is wrong with me? Thank you.

**Comment by DomiXLogic** [comment]
Hi dude can you please tell me how did you make it work by using the Google account ? I logged to your cloud perfectly.
