### ISSUE TITLE
Sinle logout Process

### ISSUE THREAD

**Issue by cheesgno** [zorn-v/nextcloud-social-login#137]
Hi
i'm using your plugin with my keycloak 8 server.
My nextcloud instance is one of a series of differents types of applications wich share the same session.
During the login process all works and I'm able to retrive all user and groups data.
If I perform a logout from nextcloud all my applications execute logout without error.
If one of the other application execute logout all application logout but not my nextcloud.
How can configure my nextcloud instance in order to manage logout signal from other applications?
Thanks a lot

**Comment by zorn-v** [comment]
You can set "logout url" param in provider config. There will be redirect on that url after logout in NC.
