### ISSUE TITLE
Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.   

### ISSUE THREAD

**Issue by becash** [zorn-v/nextcloud-social-login#139]
I  receive  this letter  from facebook,   after one  week   hi lock my app>
Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app cloud.foto-video.md (AppId: xxxxxxx) doesn't comply with the following Platform Policies:

Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.
  
During Login, your app or website is crashing or hanging excessively, creating a broken experience for people trying to use your Login integration. To make sure this flow runs smoothly, check that you've integrated Facebook Login correctly. We recommend that you test Login on all integrations. If you have not already done so, please:

• We encourage you to test your Login integration following these steps here: https://developers.facebook.com/docs/facebook-login/testing-your-login-flow/
• Best Practices for Login can be found here: https://developers.facebook.com/docs/facebook-login/best-practices

 
Since we're striving to improve the Platform experience, your app's ability to do the following has been restricted.

Access to Facebook Login
  
Restriction on Facebook Login means that you will need to remove the button from all user-facing interfaces to avoid negative user experiences. If you believe your product can be fixed and want to integrate Facebook Login going forward, please add the button after your appeal has been approved.
 
   
If you would like to revert this restriction, your app will need to be updated so that it is compliant with the above policy. Once your updates are complete, please submit an appeal here for review: https://developers.facebook.com/appeal/. A member of our team will respond within 48 hours.
  
We're always working to create great experiences for developers on Facebook,  we’d love to hear your feedback on what you liked about your interaction with us and what we could improve.  Please take a few minutes to fill out our survey: www.facebook.com/survey/?oid=xxxxxxx&cd={"job_id":"xxxxx"}.

Thanks,

**Comment by MeghanaBasutkar2** [comment]
@becash hey, did you find any solution to this problem? Please DM me here: meghana.basutkar5@gmail.com

Regards,
Meghana

**Comment by sandeep14** [comment]
Hi @becash , I also received same email from facebook team, I don't know how to communicate with theme to know what is exact issue they are facing please help me for this

**Comment by becash** [comment]
nobody not respond, not have solution yet.... i see is work.... but not sure if without errors

**Comment by zorn-v** [comment]
Facebook (oh I should say Meta), is not my "field of work". 
Somehow by yourself
