### ISSUE TITLE
add Google SSO html meta tag verification 

### ISSUE THREAD

**Issue by KnicKnic** [zorn-v/nextcloud-social-login#140]
Would it be possible to make it easier to verify owership https://github.com/zorn-v/nextcloud-social-login/blame/master/docs/sso/google.md#L9

One way would be to add the ability to do html meta tag customization of the root page in the social plugin.

**Comment by zorn-v** [comment]
I did not wrote that documentation :smile: 
At my side no verification was not needed while I test google login functionality.

**Comment by KnicKnic** [comment]
> I did not wrote that documentation 😄
> At my side no verification was not needed while I tested google login functionality.

You are correct, I did not need to verify my site. I am unclear if verification gets any benefit.

@josephdpurcell do you know what additional benefit occurs if verification you mentioned in the docs is performed.

**Comment by josephdpurcell** [comment]
@KnicKnic I was following the documentation from Google. My site was already verified so I couldn’t verify if verification was of any benefit.

**Comment by josephdpurcell** [comment]
I *think* that having ran authorized domain is requisite to using it when setting up the application in google — sorry I don’t have notes to confirm.

As a shot in the dark maybe it helps avoid this:

> If you don't verify your script project's OAuth client, users outside your domain see an unverified app screen

https://developers.google.com/apps-script/guides/client-verification

**Comment by KnicKnic** [comment]
> I _think_ that having an authorized domain is requisite to using it when setting up the application in google — sorry I don’t have notes to confirm.
> 
> As a shot in the dark: maybe it helps avoid this:
> 
> > If you don't verify your script project's OAuth client, users outside your domain see an unverified app screen
> 
> https://developers.google.com/apps-script/guides/client-verification

@josephdpurcell 

When signing in my unverified domain, I do not see an unverified app screen. 

I am going to close this for now. Also since the validation isn't scoped to the subdomain I am using it would be of no use to add the meta information at the subdomain level.
