### ISSUE TITLE
Incompatibility with Auth0 OIDC

### ISSUE THREAD

**Issue by theopen-institute** [zorn-v/nextcloud-social-login#142]
At present, Social Login fails when Auth0 is used as a identity provide. This is because Auth0 uses the pipe character `|` in the value for `sub`, and the pipe character is disallowed as a Nextcloud username.

In my local install, I've solved the problem by replacing CustomOpenIDConnect.php line 34, which currently reads:
```
$userProfile->identifier  = $data->get('sub');
```
with:
```
$userProfile->identifier  = str_replace('|', '@', $data->get('sub'));
```

I'm happy to submit a pull request if it'd be helpful, but this isn't a particularly elegant solution and I don't understand enough about the nextcloud architecture to propose a better one. Perhaps there's a more universal way?

(In any case, thanks for all the hard work on this app! It has improved the user experience on our Nextcloud implementation tremendously!)

**Comment by zorn-v** [comment]
Fixed in v2.3.1 by another way https://github.com/zorn-v/nextcloud-social-login/commit/cc545dd7d20d1068e22bf55e526b26099e894e6d
