### ISSUE TITLE
Multiple same providers at login page

### ISSUE THREAD

**Issue by Omaha2002** [zorn-v/nextcloud-social-login#146]
Updated to 2.4.2 this morning and deleted Twitter social login now there are multiple same social login providers on the home page. I did re-enable Twitter social login but to no avail.

Nextcloud 17.0.2

![image](https://user-images.githubusercontent.com/3179748/72680906-36285980-3abf-11ea-975f-245fd2d0bce6.png)

**Comment by chrismaster** [comment]
same here

**Comment by danielepercivaldi** [comment]
same here 17.0.2 update to 2.4.2. Back to 2.4.1.

**Comment by GilchristT** [comment]
Same here - fresh installation of 2.4.2 on NextCloud 18.0.0 if that's any help

**Comment by zorn-v** [comment]
Try v2.4.3

**Comment by Omaha2002** [comment]
Fixed with 2.4.3, thanks!

**Comment by danielepercivaldi** [comment]
Thanks.
