### ISSUE TITLE
Social Login buttons off-centered on login screen

### ISSUE THREAD

**Issue by jecal22** [zorn-v/nextcloud-social-login#147]
Nextcloud 18.0.0
Social Login: 2.4.3
OS: CentOS 7.7.1908
PHP: 7.3.12 (fpm-fcgi)
MySQL: 8.0.18
Apache: 2.4.6

Issue: After updating to Nextcloud 18 I have noticed that on the login screen the social login buttons are off-centered.  Prior to upgrading from Nextcloud 17 to 18 the buttons were centered under the login form.

Expected Behavior: Social Login buttons should be centered under the login form.

![Screenshot_20200128_203429](https://user-images.githubusercontent.com/20260386/73324020-1efc1100-420f-11ea-9940-73dc1c72b9e7.png)

**Comment by zorn-v** [comment]
It is NC18 issue
https://github.com/nextcloud/server/pull/19031

**Comment by jecal22** [comment]
It didn't even occur to me that it would be a bug with the core NC since it
was only the alt login buttons that were affected. Thanks for pointing me
in the right direction.

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/19238
