### ISSUE TITLE
Authorization in settings menu does not pass

### ISSUE THREAD

**Issue by SparkYDevtk** [zorn-v/nextcloud-social-login#148]
NextCloud 17.0.3 Authorization in settings menu does not pass.
log 
2,"time":"2020-02-01T17:51:44+00:00","remoteAddr":"*.*.*.*","user":"--","app":"no app in context","method":"POST","url":"\/Cloud\/index.php\/login","message":"Login failed: *** (Remote IP: *.*.*.*)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.3.1"}
everything works fine with a regular password

**Comment by zorn-v** [comment]
> Login failed: ***

And what behind stars ?

**Comment by SparkYDevtk** [comment]
{"reqId":"p6De5jaVg0JGvx7RfucV","level":2,"time":"2020-02-02T10:52:29+00:00","remoteAddr":"0.0.0.0","user":"***","app":"passwords","method":"GET","url":"\/Cloud\/index.php\/settings\/user","message":"Login attempt with invalid session for **","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.3.1"}

stars - nickname

**Comment by zorn-v** [comment]
> "app":"passwords"

It is not my app. Can you please explain what are you trying to do step by step, and what result you expect.

**Comment by SparkYDevtk** [comment]
Такс продолжу на нашем. Да, действительно, это приложение "passwords"каким то образом мешало войти в меню после авторизации через nextcloud-social-login. После его удаления я смог провалиться в меню настроек без проблем.
