### ISSUE TITLE
Discord login ends in 401 Unauthorized error

### ISSUE THREAD

**Issue by GizmoRA2** [zorn-v/nextcloud-social-login#15]
I have added Discord to the AdminSettings.php
And have configured the correct Client ID, Client Secret, and Redirect URL
https://example.com/index.php/apps/sociallogin/oauth/Discord

example.com is not the real domain obviously

Login works as expected until you click continue on the discord permissions page
Or if you try a second time it skips the permissions page and goes straight to the error
The error I get is below:

Error
Signed API request has returned an error. HTTP error 401. Raw Provider API response: {"code": 0, "message": "401: Unauthorized"}.

**Comment by zorn-v** [comment]
Try to comment this line https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L91
Or change `email` to `identify email`

**Comment by zorn-v** [comment]
>As you can see, Discord auth already has identify email scope

Yes, but I override scope for all providers, to request as few permissions as possible. You must comment that line to use scope from builtin provider.

Seems I was right, and scope must be `identify email`
https://www.cpume.com/question/foefsinh-oauth2-error-401-unauthorized-at-php-request-with-access-token-discord-api.html

Anyway I'll test all and add `Discord` to release :wink:

**Comment by zorn-v** [comment]
Added Discord in v1.5.5
You should reconfigure Client ID, Client Secret, and Redirect URL as `discord` in lower case now.

PS. You should have cleaned the cookies after changing scope, but now it is no needed I think, as name "changed".

**Comment by GizmoRA2** [comment]
Thank you it worked perfectly this time, cookies....*face-palm* why did I not think to clear the cookies.... anyway thanks heaps, 10/10 will recommend nextcloud-social-login to everyone :)
