### ISSUE TITLE
Link to external account management

### ISSUE THREAD

**Issue by tophattom** [zorn-v/nextcloud-social-login#150]
I'm using Keycloak as OIDC prodiveder and I was wondering if there is a way to make Nextcloud link to Keycloak's account management page. This would be nice since Keycloak is the source of truth for account data and making changes in Nextcloud wouldn't make sense.

I realize this might not be the responsibility of this app but I figured this could be a decent place to start investigating a solution.

**Comment by zorn-v** [comment]
> This would be nice since Keycloak is the source of truth for account data and making changes in Nextcloud wouldn't make sense.

This is not true for all. You can link many providers for one nextcloud account, and maybe configure app not syncing data from external source on every login.

**Comment by tophattom** [comment]
Oh, true, I didn't think of that. But in my case it would make sense so my question still stands.
