### ISSUE TITLE
Redirect page protocol

### ISSUE THREAD

**Issue by dkrainyk** [zorn-v/nextcloud-social-login#151]
I have nextcloud hidden behind reverse proxy that adds https, cert and access via normal domain name. Config is modified according to [official link](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#example)
But social plugin thinks that nextcloud is running on http and creates http based redirect pages that are failing on google/facebook/etc.
Social plugin should read 'overwriteprotocol' config parameter and use it instead of default value.

**Comment by zorn-v** [comment]
If you set `'overwriteprotocol' => 'https'` all will works fine.

**Comment by dkrainyk** [comment]
Thanks, had to comment out `'overwritecondaddr'` in config to make it work, looks like an issue in tutorial.
