### ISSUE TITLE
Login-Button defaced

### ISSUE THREAD

**Issue by sr-verde** [zorn-v/nextcloud-social-login#152]
Hi,
there is a styling issue with the external login button (see attached) after upgrading to NC 18. Where should this be fixed? In this repo in https://github.com/zorn-v/nextcloud-social-login/blob/master/css/guest.css? If so, I can fix it there and create a PR. If not, please give me a hint.

Best wishes!

![image](https://user-images.githubusercontent.com/10595600/74436111-2b66a780-4e66-11ea-86f2-a870054cfaee.png)

**Comment by zorn-v** [comment]
https://github.com/zorn-v/nextcloud-social-login/issues/147

**Comment by sr-verde** [comment]
Yeah, solved it.
