### ISSUE TITLE
Add Microsoft Login

### ISSUE THREAD

**Issue by drkmccy** [zorn-v/nextcloud-social-login#155]
Would it be possible to add Microsoft (Office365) SSO login?

**Comment by mmccarn** [comment]
I have been able to get Office365 SSO login functioning, setting the Nextcloud userID to the user's email address.

## Configuration:
- Microsoft non-profit organizational account / some users licensed for E1 and some for Business 365 (that is - I am not paying for Azure P2)
- Nextcloud 18.0.3 running on Ubuntu 18.04.4 (Also worked on Nextcloud 16.0.9)

## In Azure AD:
* select App Registrations, New Registration
  * enter a name for your app
  * Leave it set to 'Accounts in this organizational directory only ([your org] - Single tenant)
  * Click 'Register'

In your newly created App:
* API Permissions
  * There should be an entry for "Microsoft Graph" showing these settings:
    * User.Read / Delegated / Sign in and read user profile
  * Click "Grant admin consent for [your org]" at the top of the screen

* Token configuration (preview)
I had to manually add "email" here before I could get the O365 email address back into Nextcloud
  * Click "+Add optional claim"
    * Select "ID", check "email", click "Add"
    * repeat for "Access"
    * repeat for "SAML"

* Configuration Information
You can find the URL values needed to configure the Nextcloud App by clicking "Quickstart" in your App settings, then clicking "View" under Endpoints on the right side of the page.

## In Nextcloud
* Navigate to "Apps"
  * Select "Social & communication" on the left
  * Find "Social Login"
  * Click "Download and Enable"
* Navigate to "Settings"
  * Find "Social login" under Administration
    * Click the "+" next to "Custom OpenID Connect"
    * Fill in the fields as shown below
      * Internal Name: ```o365```
        Used in the path to the app during login, and used as the prefix for the user id in Nextcloud by default.
      * Title: ```Office 365```
        Will appear on the Nextcloud login screen as "Log in with [Title]"
      * Authorize URL
        Copy/Paste the value for "OAuth 2.0 authorization endpoint (v2) from the Azure App Quickstart page
      * Token URL
        Copy/Paste the value for "OAuth 2.0 token endpoint (v2)" from the Azure App Quickstart page
      * Client Id
        Get this from the Azure App 'Overview' page
      * Client Secret
          * [In Azure] Navigate to 'Certificates & secrets' in your App
          * Click "+New client secret
          * Select a secret life timeout (1 year, 2 years, never)
          * Copy / Paste the secret back into Nextcloud
      *  Scope
        Must be ```openid```
      * Groups claim
        I don't use this...
      * Button style
        Select 'OpenID' (this is cosmetic only)
      * Default group
        I use O365 auth for only one domain, so I put all users into that domain using this field.

Your users should now be able to login.  User IDs in Nextcloud will look like "[internal name]-GUID".  That is, if you entered ```o365``` as the internal name during setup then usernames will look like ```o365-71f4f2de-b773-ba494a51-4a51-b773aeb7e39f```.

## Not Recommended - customize sociallogin to set userid=email
If you want your nextcloud user IDs to be the users email addresses, you need to edit two files (I suspect this breaks other features of the sociallogin app):
```
# APPS/sociallogin/lib/Provider/CustomOpenIDConnect.php
-     35         $userProfile->identifier  = $data->get('sub');
+     35         $userProfile->identifier  = $data->get('email');
```
```
# APPS/sociallogin/lib/Controller/LoginController.php
-    302         $uid = $provider.'-'.$profileId;
+    302         $uid = $profileId;
```

**Comment by derekblankmccoy** [comment]
Thanks for that information, mmccarn. Very helpful.
One question. I currently have my users authenticating with LDAP/AD with their internal username set to 'sAMAccountName'. If I implement Office365 SAML SSO, is there a way these users can log in with the new auth method and have Nextcloud map to their existing accounts? Like have a hybrid login where both auth methods give the user access to the same Nextcloud account? Thanks

**Comment by mmccarn** [comment]
You probably want to look at the OpenID Connect app, which is specifically designed to address your configuration of LDAP users authenticated through Azure - including a setting to continue to use LDAP for *all* user details, using O365 *only* for authentication.

* [Open ID Connect in Nextcloud App Store](https://apps.nextcloud.com/apps/oidc_login)
* [Open ID Connect Homepage](https://github.com/pulsejet/nextcloud-oidc-login)

I found the OpenID Connect app while looking into my options after migrating my email from an on-premises server into O365.  I'm not using LDAP in Nextcloud; instead, I'm migrating from IMAP auth. This Social Login app using email addresses as usernames is (almost) a perfect fit for me.

I also looked at the [SSO & SAML authentication](https://apps.nextcloud.com/apps/user_saml) app - but the how-to for O365 for that app requires a paid version of Azure Active Directory (and I'm too cheap to fire up yet-another-per-user-monthly-fee for authentication)

**Comment by georg90** [comment]
Trying to get this to work based in @mmccarn explaination. Thanks a lot! 

However it's giving me 
`AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: REMOVED ID`

I configured the mail url in azure add: https://nextcloud.mydomain.com => This is not working.

Any idea?

**Comment by mmccarn** [comment]
* Go to the Nextcloud Login Screen
* Right-click on the sociallogin button and "Copy Link Location" (Firefox) or "Copy Link" (Edge/Chrome)

  On my system, the resulting link goes to my nextcloud server, then "/custom_oidc/", then ends with the value I entered for "Internal Name" in the Nextcloud settings for sociallogin.

  For example:  https://nextcloud.mydomain.com/sociallogin/custom_oidc/azure
https://cloud.mmsionline.us/apps/sociallogin-aicr/custom_oidc/aicr


* Go to the the Azure App configuration
  * Select 'Authentication' 
  * Locate the 'Web URI' section
  * select 'Add URI'
    Paste the URL you got from the Nextcloud login screen

**Comment by georg90** [comment]
@mmccarn Thank you for your example. This got me thinking. I had added this domain (adopted to mine) in azure, but it still didn't worked.

The i checked in Developer tools that instead of `htttps` my domain was redirected to `http`. Since I am using docker it will get SSL & HTTPS enforced by reverse proxy later..

Mentioning this I added `'overwriteprotocol' => 'https'` to my `config.php`

**Comment by KiYiul** [comment]
@mmccarn, 
<pre>
Your users should now be able to login. User IDs in Nextcloud will look like "[internal name]-GUID". That is, if you entered o365 as the internal name during setup then usernames will look like o365-71f4f2de-b773-ba494a51-4a51-b773aeb7e39f.
</pre>

I was succeed login with Azure AD account of your detail description. thanks. However, My AAD account was displayed at "vS7GeYmh_eHC7QXCKb1JJCGiumrBK666eg7tRaANdQk". It is not name attribute in AAD. In AAD, name attribute is "유기열(Ki Yiul Yoo - TPI팀)". That problem has been told by you. Nevertheless that, how can I use correct name attribute in AAD?

I'm not sure that issue belong to encoding which like UTF-8 or mapping to attribute in  AAD.

**Comment by mmccarn** [comment]
The default username is your domain name plus the Azure GUID for the user.

To use something else you have to edit APPS/sociallogin/lib/Controller/LoginController.php as described above in the section marked 'Not recommended'

Editing a file within an app significantly increases the difficulty of maintaining your server.  Every time you update the server you need to check that your edits are still in place, and add them if they are not.

If you customize LoginController.php I recommend against using the user's name attribute, unless it is not possible for two people to have the same name.  If two people have the same name they would both see the same account in Nextcloud after logging in.

**Comment by KiYiul** [comment]
@mmccarn, Thanks the kindly reply about the authenticator + Azure GUID(sub).
I succeed to modified the APPS/sociallogin/lib/Controller/LoginController.php file and change intentifier from "sub" to "email".
Then now, I have wonder what can I select user's attribute for identifier as "sub", "email" and another things.
I tried search for Azure basic user profile to select user identifier but "name", "surname", "identifier", "firstname", "lastname", "displayname", "givenName" was null vaule.

**Comment by mmccarn** [comment]
Any field you want to access from the social login app in nextcloud needs to be added as an "optional claim" to the 'Token Configuration' section of the App in Azure as described [in the notes above](https://github.com/zorn-v/nextcloud-social-login/issues/155#issuecomment-605515991) about adding "email".

However, you should be careful about selecting an identifier that might be spoofed by another Azure user.

For example - if you use "lastname" as the identifier, an attacker could create their own account in Azure with the same "lastname" as one of your users, then use their own account to login to your server.

When I created the notes above I saw a note from Microsoft (that I can't find at the moment) indicating that "email" should not be used as a unique identifier during login.  Presumably Microsoft believes that is it possible to create two Azure accounts with the same value for "email" - possibly related to their duplicate authentication services ("personal" vs "business/school").  

On my server I can only use email (for various reasons).  I tried to minimize my exposure by restricting use of SSO login to domains that I control. However, I am not using these modifications in production, and I have not done an exhaustive security analysis of them.

**Comment by KiYiul** [comment]
@mmccarn, thank you so much for the detail information. So, I had to add "optional claim" into our Azure registration app by "Token configuration" about email, family_name, given_name, preferred_username, upn. (I can not add optional claim SAML token type about family_name, given_name, preferred_username due to there is not exist. but add to upn SAML token type successfully.)

However, I was modified ./apps/sociallogin/lib/Provider/CustomOpenIDConnect.php as below, when I tried login "Can not get identifier from provider" error poped up.


```
# APPS/sociallogin/lib/Provider/CustomOpenIDConnect.php
-     35         $userProfile->identifier  = $data->get('sub');
+    35         $userProfile->identifier  = $data->get('upn');
```

Addtionally, our company AAD's name attribute have unique value and name & last name attribute have same value. so I have not concern about your kindly advise yet.

**Comment by KiYiul** [comment]
@mmccarn, although supported by your mentions, I can not mapping AAD attribute into NextCloud account. So, I change NextCloud 3rd-party application from nextcloud-social-login to nextcloud-oidc-login which can get on https://github.com/pulsejet/nextcloud-oidc-login.

Anyway, thanks the supporting and followup on my previous question.
