### ISSUE TITLE
Adding quota claim

### ISSUE THREAD

**Issue by JulesTriomphe** [zorn-v/nextcloud-social-login#156]
Hey, it would be great if there was the possibility of configuring the user's quota through a custom claim for custom OIDC and OAuth. I've tried adding a few parameters to LoginController.php, CustomOAuth2.phpCustomOpenIDConnect.php and admin.php but no luck. Would you have any pointers or would you even be willing to support this ?

**Comment by zorn-v** [comment]
If you really wanna this, I can made it for pay, only if it go to open source then.

**Comment by JulesTriomphe** [comment]
Isn't it just a couple of lines of code ? Does it really require a lot of
development ?
Of course I would like it to remain open source :)

**Comment by zorn-v** [comment]
How about research ? Line of code cost nothing )

**Comment by JulesTriomphe** [comment]
I tried a few things by adding bits and pieces of code I found in the Nextcloud guide and other login apps and adapting yours in the files mentionned above. I'm more than happy to submit a PR if I can get the code to work. Do you have any pointers on how to do it though ? Do I have to modify another file on top of those ? I can't seem to make it work.

**Comment by krakazyabra** [comment]
Hi @JulesTriomphe 
I've solved this through groups. In my provider i made several groups (like 1G, 5G, 10G etc) and assigned users. 
In NC I made the same groups, but common to Social Login: <provider-name>-1G, <provider-name>-5G etc. 
Also I installed Groupa Quota application and set quota to my custom groups
So, users from Social Login get into the correct groups with right quota.

**Comment by JulesTriomphe** [comment]
Thanks for the tip @krakazyabra !

**Comment by krakazyabra** [comment]
@JulesTriomphe Also you can do it programmatically with API:
Create new role for user
```curl -X POST ${keycloakUri}admin/realms/${keycloakRealm}/clients/${client}/roles -H "Authorization: Bearer $TOKEN" -H 'Accept: application/json' -H 'Content-Type: application/json' -d '
{
"name": "new-role",
"composite": false,
"clientRole": true,
"containerId": "${client}"
}'
```

Get ID for new role
```
<!---------- INPUT ------------>

curl -X POST ${keycloakUri}admin/realms/${keycloakRealm}/clients/${client}/roles -H "Authorization: Bearer $TOKEN" -H 'Accept: application/json' -H 'Content-Type: application/json' | jq -r '.[] | select(.name == "new-role") | .id'

<!--------- OUTPUT ------------>

5c2c69bf-357a-44d6-bc1e-6c2596d28cec
```

Assign new role to user
```

**Comment by JulesTriomphe** [comment]
That's really interesting @krakazyabra ! Thanks for sharing the procedure. I'll be sure to try it out.
