### ISSUE TITLE
Local admin login

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#157]
Hi there! I installed Social Login in my Nextcloud instance, added `'social_login_auto_redirect' => true,` to config.php
Everything is OK, users can login, I can manage them from keycloak. 
But how can I login using local admin account? The only way I fount - disable auto_redirect for a while, login under admin, enable auto_redirect back. But it is nonsense. 
Also I cannot assign Keycloak user to local admin group (checkbox "Update groups" enable, and i can't disable it, because it is very important for me). 
So, is there any possibility to:
a) Login under local admin with social_login_auto_redirect enabled?
b) Assign Social user to local admin group?

Thanks in advance.

**Comment by zorn-v** [comment]
Update to version 2.4.5 and you can use `noredir=1` query parameter in login page.
Something like `https://cloud.domain.com/login?noredir=1`
Readme also updated

**Comment by krakazyabra** [comment]
Gr8! Thank you! 
About second question - my bad, there is mapping under Custom OIDC block.
