### ISSUE TITLE
Problem with custom oauth2

### ISSUE THREAD

**Issue by lliebler** [zorn-v/nextcloud-social-login#158]
Hey guys, i have a problem with a custom oauth2 configuration.

My error:
Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":"invalid_request","error_description":"Invalid token","error_uri":"https:\/\/tools.ietf.org\/html\/draft-ietf-oauth-v2-31#section-7.2"}.

I've already did your 'overwriteprotocol' => 'https', patch.
Can you help me?

Best, Lasse

**Comment by zorn-v** [comment]
Seems you just not configured right. White spaces in key (copy/paste and leading white space) or something like this
