### ISSUE TITLE
Questions: How to debug... Do I *need* a profile endpoint?

### ISSUE THREAD

**Issue by phedders** [zorn-v/nextcloud-social-login#159]
I'm trying to get NC to let authentication happen at Churchsuite. They provide oauth2 endpoints, but only authorize and token - no profile.

Am I on a hiding to nothing?

I get redirected to the Churchsuite login page - but when I return to my NC instance with /?code=.... it just redirects me to /login as if nothing happened.

A bit stumped and needing some pointers - Apologies that this is not a bug report - I am the bug :)

**Comment by zorn-v** [comment]
Debug of "redirect to redirect to redirect" is really... FUCK )
If you debug my plugin - check `Providers`. There all "magic" (reduced) about redirects.
