### ISSUE TITLE
Autoremove disabled users

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#160]
Hi! Is there an option to autoclenup disabled users. On Keycloak's side I'm going to disable user and pressume, that his account will be also disabled in NC. And after some time (f.e. 30 days), the account and all the data will be removed. 
Thanks in advance ;-)

**Comment by zorn-v** [comment]
It is not possible because nextcloud does not save disable user time.

**Comment by zorn-v** [comment]
But maybe it is possible to save that time via event listener. Will check later

**Comment by zorn-v** [comment]
Yes it is posible to implement, but I think requested functionality does not related to social login.
