### ISSUE TITLE
Social Login with iOS

### ISSUE THREAD

**Issue by marinofaggiana** [zorn-v/nextcloud-social-login#161]
Hi, we have a issue with the login flow and iOS App, do you have any information to give me ?

Thanks a lot
m.

**Comment by zorn-v** [comment]
Need more info. I just test and all works fine

**Comment by marinofaggiana** [comment]
Do you have make a test with the Nextcloud iOS app ? Thanks

**Comment by zorn-v** [comment]
Yes. NC app version 2.25.9

**Comment by marinofaggiana** [comment]
Because I look an issue with Google service (do not appear the view which requires the security code) and the login procedure remain blocked.

**Comment by zorn-v** [comment]
I check login exactly with google (but without security code).
Try ask here https://github.com/nextcloud/ios/issues

**Comment by marinofaggiana** [comment]
Thanks
