### ISSUE TITLE
Social login and CalDav/CardDav

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#163]
Hi! It seems, that social login users cannot sync their calendars and contacts. 
Configuring my device (iOS and OS X): 
Username: `provider-name-f64a0584-4619-4cf0-8365-bd33e381c2ee`
Password: `<users OID pass>`
Server: `domain.org`
Path: `/remote.php/dav/principals/users/provider-name-f64a0584-4619-4cf0-8365-bd33e381c2ee/`
The result - Cannot verify username and password
Disabling Social Login app, trying to test with local admin account - everything working fine.

**Comment by zorn-v** [comment]
> Password: <users OID pass>

Password is generated when user created with social login and you can not know it. Only way to get password for account created with social login is to set correct unique email and reset password via it.

**Comment by krakazyabra** [comment]
this is not in our hands. I collect users from different backends (FreeIPA, LDAP) to keycloak. And Nextcloud working with keycloak directly. So all passwords are in backends. 
What can we perform in this case? 
З.Ы. Можно по-русски :)

**Comment by zorn-v** [comment]
> And Nextcloud working with keycloak directly

Это как ?
При логине создается акк в nextcloud и ему нужно установить пароль. Внешняя система естественно тебе этот пароль не отдаст, поэтому генерится случайный.

**Comment by krakazyabra** [comment]
>При логине создается акк в nextcloud и ему нужно установить пароль
Это при использовании внутренней авторизации. Мы у себя используем Keycloak, собираем пользователей отовсюду из разных источников, в кейклоке менеджим уже роли для них, и в NC имеют доступ только те, у кого соответствующая роль. А пароль не устанавливается, юзер использует свой LDAP пароль. Получается, что даже keycloak не хранит у себя пароли, он только хэши сравнивает.
>поэтому генерится случайный
То есть какой-то промежуточный пароль, который хранится в самом NC?

**Comment by zorn-v** [comment]
> То есть какой-то промежуточный пароль, который хранится в самом NC?

Ну да. При логине через социалку пароль же не нужен, а аккаунт без пароля - такое себе. Скорей всего сам NC не даст юзера без пароля создать. Есть другой плаг который в качестве бекенда юзеров может LDAP использовать, может он подойдет ?
https://apps.nextcloud.com/apps/oidc_login

**Comment by krakazyabra** [comment]
Я его смотрел уже, не подойдёт. Он напрямую смотрит в LDAP и берёт оттуда все данные. а у нас ldap - это всего лишь один из возможных бэкэндов. часть пользователей вообще в обычной бд лежат. поэтому и используем keycloak для того, что бы всех собрать, унифицировать, раскидать роли. 
В общем, я понял, по сабжу - caldav и social login - вещи несовместимые. 
только если вытащить из бд некстклауда промежуточный пароль))

**Comment by krakazyabra** [comment]
Хотя.. Почитал про этот плагин, вроде как умеет он с кейклоком работать. Буду пробовать, спасибо!

**Comment by zorn-v** [comment]
> только если вытащить из бд некстклауда промежуточный пароль))

Во первых там хеш ) Во вторых пароль можно сбросить через восстановление по почте (о чем я изначально и писал)

> Почитал про этот плагин, вроде как умеет он с кейклоком работать

Ну в таком режиме он от этого отличается только тем что он упрощен и можно задать только одного провайдера. Ну еще он может uid без префиксов лепить вроде как.

**Comment by krakazyabra** [comment]
Я нашел способ :) 
Через CLI некстклауда задаём пользователю такой же пароль, как и в кейклоке (в нашем случае, между пользователем и кейклоком есть прослойка (она же биллинг), все данные пользователя проходят через нее, оттуда мы можем перехватить пароль, который пользователь задаёт). Перехватываем пароль, вызываем cli, подставляем айди пользователя из кейклока, перехваченный пароль... бинго)
Теперь можно залогониться в некстклауд кк через кейклок, так и через обычную аутентификацию с тем же паролем. 
Синхронизация календарей и контактов работает!

**Comment by zorn-v** [comment]
> Через CLI некстклауда задаём пользователю такой же пароль

Ну я и пытался примерно это же сказать :) 
Только чтобы пароль задавал сам пользователь через сброс пароля по емейлу. Пользователь то знает свой пароль )

Если кейс "заботы о пользователях", то да - пароли надо перехватывать )
