### ISSUE TITLE
Google Login through managed Nextcloud not working

### ISSUE THREAD

**Issue by RayNCooper** [zorn-v/nextcloud-social-login#164]
Hey everybody,

I am currently using Nextcloud by leveraging Hetzner's Storage Share service.
Because of it being managed and them assigning me a subdomain in the form of 
https://<id>.your-storageshare.de/, I am at first sight unable to prove ownership of the domain.

I configured the Google OAuth 2.0 Login, but it redirects to Hetzner's 404 page after providing login credentials.

Supposedly this comes from the fact that I do not have control over the domain and it's routing; Any other ideas?

Cheers,
crunch

**Comment by zorn-v** [comment]
You can try use custom oauth login. 
Sorry but can't provide additional info as does not know what "Hetzner's Storage Share" is

**Comment by RayNCooper** [comment]
StorageShare is basically a modified version of Nextcloud that is managed by the Hetzner hosting company. They assign you a subdomain on your-storageshare.de while withholding root access because of their VPS architecture.

**Comment by zorn-v** [comment]
How "Hetzner's 404 page" url is looks like ?

**Comment by RayNCooper** [comment]
This is the redirect that does not work:

`https://<account-id>.your-storageshare.de/apps/sociallogin/oauth/google?state=xxxxxxxxxxxx&code=xxxxxx&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&hd=example.com&prompt=consent`

The 404 just looks like every other "Page not found" site.

**Comment by novalina26** [comment]
Novalina[Novalina]()

**Comment by novalina26** [comment]
#155 

> Ini adalah pengalihan yang tidak berfungsi:
> 
> `https://<account-id>.your-storageshare.de/apps/sociallogin/oauth/google?state=xxxxxxxxxxxx&code=xxxxxx&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&hd=google.com&prompt=consent`
> 
> 404 hanya terlihat seperti situs "Halaman tidak ditemukan" lainnya.

**Comment by novalina26** [comment]
0x9Bb7F59578e27dcE128B1ceD4E2D3f883F9DB914
