### ISSUE TITLE
Custom OAuth2: How to set and example ?

### ISSUE THREAD

**Issue by ravinote** [zorn-v/nextcloud-social-login#165]
Hi,

The app Social login via "OAuth GitHub" works very well ! Thanks a lot for all contributors. Thus, I would like to go further by using the "Custom OAuth2" function. I try to set the "Custom Oauth2" as same as what I have set with "OAuth GitHub" (still verifying account by GitHub). 

I follow the GitHub OAuth's template from: https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Provider/GitHub.php

Here is what I do in "Custom OAuths":
1. API Base URL: https://api.github.com
2. Authorize url (can be relative to base URL): https://github.com/login/oauth/authorize
3. Token url (can be relative to base URL): https://github.com/login/oauth/access_token
4. Profile url (can be relative to base URL): https://api.github.com ???
5. Scope (optional):  user:email   ???
6. Profile Fields (optional, comma-separated):   ???
7. Groups claim (optional): ???

For, 4-7 I don't know what to put in these boxes. Please help me to configure these so my Custom OAuth will work as same as "GitHub OAuth".

Thanks,
Ravi

**Comment by zorn-v** [comment]
Custom logins needs for CUSTOM (read as "you know what you do"). 
What benefits for you to create custom login instead of builtin ?

**Comment by ravinote** [comment]
Hi zorn-v,

Thanks for the suggestion and thanks for your wonderful Social login app !  

According to previous issue, I wonder about the right required URLs to put in each boxes for Custom OAuth to work. Thus, I try it with OAuth GitHub, where "builtin" have been worked very well. Currently, configuration of "Custom OAuth with GitHub" seems work for me !! Here is what I did ...  

1. API Base URL: https://api.github.com
2. Authorize url (can be relative to base URL): https://github.com/login/oauth/authorize
3. Token url (can be relative to base URL): https://github.com/login/oauth/access_token
4. Profile url (can be relative to base URL): **https://api.github.com/user**

Seem like "**Profile url**" is the most important to be placed correctly. Also, what is the important in "Scope (optional): user:email" ?  Do you have any further suggestion for me ? 

Lastly, I will develop my own OAuth app and will make it return parameter as same as what GitHub OAuth do. Therefore, other people can log-in to my Nextcloud via this app.

Best regards,
Ravi

**Comment by zorn-v** [comment]
You can make pull request (PR) with docs how you do it if you wish.
