### ISSUE TITLE
Please document which fields are required in the Custom OAuth2 profile endpoint

### ISSUE THREAD

**Issue by nikkilocke** [zorn-v/nextcloud-social-login#166]
Just a suggestion, but it would be lovely if you could document exactly which fields the custom OAuth2 provider should return when asked for profile info. I have found, by looking at the source, that they are:
- identifier, or id, or user_id - Nextcloud login name
- email - User email address
- displayName - Nextcloud user name as displayed
- emailVerified - not sure, but I set it to true anyway

There are others too.

**Comment by zorn-v** [comment]
You are welcome to improve documentation :smile: 
I'm not so good in this )
