### ISSUE TITLE
Can we have an option to link to an existing login using custom OAuth2?

### ISSUE THREAD

**Issue by nikkilocke** [zorn-v/nextcloud-social-login#167]
We have a central web app that maintains the login details of everyone in our non-profit organisation. It uses the Nextcloud Api to create logins for people who are authorised to use our Nextcloud.

We would very much like to use OAuth2 from our central web app to log people straight into Nextcloud using their credentials from the central web app.

But we don't want a single point of failure, so we would also like people to be able to login direct to Nextcloud if the central web server is down (or they are using the Nextcloud app).

In LoginController.php, the incoming login name from the OAuth2 provider is munged:

        $uid = $provider.'-'.$profileId;

It would be really useful to have a setting option to turn that off, so people can use the same login name on our web app and Nextcloud.

Happy to help code it, if you think it is a good idea.

**Comment by zorn-v** [comment]
> so we would also like people to be able to login direct to Nextcloud if the central web server is down (or they are using the Nextcloud app)

They can reset password via email (if it unique in nextcloud) and use email as login then

**Comment by zorn-v** [comment]
And NO, I WILL NOT change user identifier logic.
