### ISSUE TITLE
Bypassing social login with noredir parameter not working correctly

### ISSUE THREAD

**Issue by tophattom** [zorn-v/nextcloud-social-login#169]
When using `/login?noredir=1` to bypass the automatic SSO redirect the login form's `action` attribute doesn't containt the `noredir` query parameter. This causes the POST request sent to login to redirect to the OIDC login flow. I tried adding the parameter to the `action` attribute through developer console and after that the login worked as supposed to.

**Comment by zorn-v** [comment]
Check v2.4.6
Redirect works only for GET now
