### ISSUE TITLE
Remove user_friends and publish_actions from the requested permission scope for Facebook login

### ISSUE THREAD

**Issue by scolphoy** [zorn-v/nextcloud-social-login#17]
Requesting the user_friends permission should be removed or turned into an option that can be disabled. The user_friends permission is not one of the basic permissions, and requires submitting your Nextcloud instance to Facebook for review per their terms of use. If the instance is not reviewed and the user is not associated with a developer identity for this app, Facebook simply ignores the request, returns an empty friend list and lets the authentication continue. If the user is associated as a developer of the app, Facebook currently goes to a loop displaying an error message about permissions and the authentication never completes.

The publish_actions permission should be removed because it has been deprecated. New apps that request it will no longer be approved in the Facebook review process. Requesting this permission with a developer account on an unreviewed app also puts the authentication in the above mentioned loop. (https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/)

**Comment by thomas-lb** [comment]
Hybridauth is an other project. You could try to open a PR here : https://github.com/hybridauth/hybridauth.
Then update the dependency from this repo.
