### ISSUE TITLE
Feature request - Sign in with Apple

### ISSUE THREAD

**Issue by cryptedbv** [zorn-v/nextcloud-social-login#171]
Hi,

I would love to see an option with ‘Sign in with Apple’ including the Apple relay email. If by any chance the Nextcloud instance gets comprimised the attacker will not have any user emails with the password hashes.

Best regards,
Jeff

**Comment by zorn-v** [comment]
I thought about it when it introduced. But I don't want to purchase apple dev account for testing.

**Comment by 24unix** [comment]
I own a dev account. What do you need to test the integration?
Without Apple ID integration the Login App is useless for me as I don't trust any of the other companies.

**Comment by zorn-v** [comment]
Let's wait when it will be merged in hybridauth lib.
I will need some keys then for testing (you can send they by email me)
```
"keys" => [
    "id" => MYHYBRIDAUTH_APPLE_ID,
    "team_id" => MYHYBRIDAUTH_APPLE_TEAM_ID,
    "key_id" => MYHYBRIDAUTH_APPLE_KEY_ID,
    "key_file" => MYHYBRIDAUTH_APPLE_KEY_FULLPATH
],
```
You can read where they can be found here
https://github.com/hybridauth/hybridauth/blob/57bbece2affcc7a261c97f287d4af12f6c4d55a9/APPLE.md

**Comment by zorn-v** [comment]
Apple provider was merged in hybridauth.
If anyone wants it, I need "help" with apple dev account.

**Comment by zorn-v** [comment]
As I do not find person with apple dev account who give me keys for TEST OAUTH APP, I close this.

**Comment by cryptedbv** [comment]
Hi zorn, sorry for the late reply, was off a while. I will provide you with an Apple Dev account. I will email you.

**Comment by srijansaxena11** [comment]
> As I do not find person with apple dev account who give me keys for TEST OAUTH APP, I close this.

Hi @zorn-v, I am very much interested in using sign in with apple on Nextcloud and I have someone who is willing to help with Apple developer account for the same. Can we work on it?

**Comment by zorn-v** [comment]
Why not ?

**Comment by srijansaxena11** [comment]
> Why not ?

How should we proceed? Can we connect on [Telegram](https://t.me/SrijanSaxena) ?

**Comment by zorn-v** [comment]
@zorn_v

**Comment by zorn-v** [comment]
![изображение](https://github.com/zorn-v/nextcloud-social-login/assets/12619075/bcd278ed-bffa-4804-a9e6-1e0ce1619a6e)
Probably your secure bot just fail...

**Comment by zorn-v** [comment]
6/5 - indian coding )

**Comment by zorn-v** [comment]
Is it really so hidden, or just MacOS user does not know any, as windows users ?
I have MacOS and I am cute ?

Disappointment in people.

**Comment by zorn-v** [comment]
I requested just TEST keys (which you can revoke at any moment). but...

**Comment by zorn-v** [comment]
Just tel me "hi" in telegram and we go

**Comment by srijansaxena11** [comment]
> ![изображение](https://user-images.githubusercontent.com/12619075/285266140-bcd278ed-bffa-4804-a9e6-1e0ce1619a6e.png) Probably your secure bot just fail...

it didn't fail 😂. it worked as expected.

**Comment by srijansaxena11** [comment]
> 6/5 - indian coding )

yeah 😂
