### ISSUE TITLE
Unable to exchange code for API access token

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#172]
Hi! 
When the newly created user logins in the first time, he recieves such error message:
```
Unable to exchange code for API access token. HTTP client error: Connection timed out after 30000 milliseconds.
``` 
After simple refresh of the page - everything is loading and user sees his files. 
This error appears only in first attemp of login. In logs - nothing.

**Comment by zorn-v** [comment]
What provider are you use and what settings ? 
Also possible that "avatar url" is not accessible from your system.

**Comment by krakazyabra** [comment]
we're using keycloak auth through OIDC. What is `avatar url`? how to check it?

**Comment by zorn-v** [comment]
May be wrong "profile url" (not blank) also

**Comment by krakazyabra** [comment]
Все поля заполнил, эндпоинты все открываются. Причем, когда появляется ошибка, достаточно нажать ctrl+R и обновить страницу. И всё сразу доступно. 
У меня есть подозрение про таймауты, ведь при первом логине некстклауд создаёт пользовательские файлы. И процесс первого логина всегда дольше длится.

**Comment by zorn-v** [comment]
Не, это в процессе обмена кодами по oauth. Там именно таймаут соединения с accessTokenUrl
https://github.com/zorn-v/nextcloud-social-login/blob/0022e7ae09f13f4b848781122fc5f6564a3cfe1d/3rdparty/hybridauth/hybridauth/src/Adapter/OAuth2.php#L468-L482

**Comment by krakazyabra** [comment]
Так и не победили эту ошибку, а тут еще новая вылезла:
![image](https://user-images.githubusercontent.com/26598203/81655165-55644180-9436-11ea-9c81-16893f92a98e.png)

**Comment by krakazyabra** [comment]
Fixed. We had network problems.
