### ISSUE TITLE
FEATURE REQUEST - New User link accounts

### ISSUE THREAD

**Issue by Coolkid2342** [zorn-v/nextcloud-social-login#174]
On the admin page add a option where when a new user logs in they will need to link a existing account when no account is linked.

**Comment by zorn-v** [comment]
What do you mean by that ? 
You can already link oauth/oidc accounts in profile settings if "Allow users to connect social logins with their account" option is enabled

**Comment by Coolkid2342** [comment]
Basically if a user tries to log in using a social and there is no account linked to that user, they would have to sign in to the account.

**Comment by zorn-v** [comment]
> they would have to sign in to the account.

To the which account ?

**Comment by Coolkid2342** [comment]
the nextcloud account

**Comment by zorn-v** [comment]
Which nextcloud account ? As you say "there is not account linked"

**Comment by kowalski7cc** [comment]
@zorn-v I think @Coolkid2342 means if a user already exists as "local nextcloud account" and tries to log in with a social account but it didn't link it before, link it and log in.
This is similar to "Prevent creating an account if the email address exists in another account" but it goes a step further.

**Comment by zorn-v** [comment]
I see now, link by email. Make sense. Will add another option for this.

**Comment by zorn-v** [comment]
@kowalski7cc 
But in such case user can change their email on external side to existing user (e.g. admin) and login as another user. 
Not all require email verification.

**Comment by kowalski7cc** [comment]
It's true. I recall tho having found some websites that have this behavior.
