### ISSUE TITLE
[Bug] When a new user registers they get hit with an internal server error

### ISSUE THREAD

**Issue by ChaseHall** [zorn-v/nextcloud-social-login#175]
I'm using keycloak for my SSO, and they sign in for the first time and get hit with an internal server error, however if they re-visit nextcloud they're let in no problem.

I have the setting where it forces them to the SSO portal turned on, not sure if that makes a difference.

Any ideas about fixing this?

Thanks.

**Comment by zorn-v** [comment]
Seems similar to https://github.com/zorn-v/nextcloud-social-login/issues/172

**Comment by ChaseHall** [comment]
No idea if this is any help, but here's my logs from apache.

`cat other_vhosts_access.log
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:36:47 +0000] "GET / HTTP/1.1" 302 933 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:36:47 +0000] "GET /index.php/login HTTP/1.1" 302 940 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:36:47 +0000] "GET /index.php/apps/sociallogin/custom_oidc/keycloak HTTP/1.1" 500 5368 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:37:11 +0000] "GET /apps/files_videoplayer/js/main.js.map HTTP/1.1" 200 7816 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:37:11 +0000] "GET /apps/files_sharing/js/dist/main.js.map HTTP/1.1" 200 3013 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
<nc-link-here> 192.168.86.24 - - [22/May/2020:00:37:11 +0000] "GET /core/js/dist/main.js.map HTTP/1.1" 200 1254858 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"`

**Comment by zorn-v** [comment]
> unable to connect to 127.0.0.1:25

You did not configure mail sender properly. You can disable send mail to admins when new user is created in social login settings if you wish

**Comment by zorn-v** [comment]
Also you can update to v2.4.7
