### ISSUE TITLE
OAuth 1.0 support - feature request

### ISSUE THREAD

**Issue by MarcinWieczorek** [zorn-v/nextcloud-social-login#176]
Hey, I can see that OAuth 1.0 is available in the library but not in the nextcloud panel, only 2.0. What are the steps to introduce that protocol? I might be able to do that myself. Thanks.

**Comment by zorn-v** [comment]
Why it is needed ?

**Comment by MarcinWieczorek** [comment]
1. The library already has oauth1 implemented
2. Some services still use 1.0a
3. I've already done it (it's functional but needs some polish)
4. Could be available as oauth version `select` where oauth2 is now, so no interface bloat is introduced - for the user it's just one additional option

**Comment by zorn-v** [comment]
> Some services still use 1.0a

Which one ? 
Just do "because I can" ? Who will be support that "nobody wants" piece of code ?

**Comment by MarcinWieczorek** [comment]
I'm no expert to compare those two versions, OAuth 1.0a and OAuth 2.0. If you want to stick with the latter then I'll back off. My use case is 1.0a and I got it working my way. Don't understand me wrong when I wanted to contribute. I get it that such code would require maintenance. Thank you for your input and close the issue if you want.

**Comment by zorn-v** [comment]
> My use case is 1.0a and I got it working my way

What service you use ? Possible better just add that one as "built-in" ?

**Comment by MarcinWieczorek** [comment]
It's called USOS, a management system for universities used in Poland. Commonly every place has their own self-hosted site and therefore the urls differ.

https://apps.usos.edu.pl/developers/api/

**Comment by zorn-v** [comment]
Sorry for stupid question, but did you try it as is with oauth 2.0 (I guess you tried, but maybe not)
If it did not work, create pull request, I'll check it.

**Comment by MarcinWieczorek** [comment]
It's not backward compatible by design. Even the forms wouldn't let it through, the urls are different. I'll integrate it with oauth2 so the forms are nice and let you know here. Thanks for giving it a chance.

**Comment by zorn-v** [comment]
I made great refactoring and add oauth1 providers type
Check v3.2.0

**Comment by MarcinWieczorek** [comment]
Great, I'll test your patch when I get a chance. I'm in the middle of switching machines now.
