### ISSUE TITLE
Primary index name on "oc_social_a2_cache_documts" is too long.

### ISSUE THREAD

**Issue by patlachance** [zorn-v/nextcloud-social-login#179]
Hi, I tried to download and enable Social Login version 0.2.101 reported as "untested app" in Nextcloud 18.0.4-fpm and got the following error message:

> Primary index name on "oc_social_a2_cache_documts" is too long.

I couldn't find a similar issue reported.
Could you please help?

**Comment by zorn-v** [comment]
Were you find that version ? Seems it is not my app.

**Comment by patlachance** [comment]
You're right, output is from "social" and not "social-login" app. Closing, sorry for the mistake.
