### ISSUE TITLE
Not showing alternate login options

### ISSUE THREAD

**Issue by rohnitVizexperts** [zorn-v/nextcloud-social-login#180]
I am currently using Nextcloud Version Stable18, downloaded and enabled the "Social Login" app from the Appstore. But, when I go to my Login page, the options of alternate logins(Gmail, facebook, etc.) do not show up, which are by default provided by the application. All I can see are basic Login option, Forgot password option and Registration option.

Please help!

**Comment by zorn-v** [comment]
You should configure oauth/oidc providers that you need in admin settings

**Comment by rohnitVizexperts** [comment]
Okay! Thank you!

Also, just to get clarity of the working can you please state an example as in what needs to be filled in the "App id" and "Secret" text boxes of the providers.

Would be a great help, thanks in advance!

**Comment by rohnitVizexperts** [comment]
@zorn-v  Thanks!
