### ISSUE TITLE
support for NextCloud 19

### ISSUE THREAD

**Issue by killarny** [zorn-v/nextcloud-social-login#181]
NextCloud 19 is now released on stable channel: https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/

Sadly, the upgrade process appears to disable the social login app, and the settings area reports the app as incompatible.

I've used the "enable untested app" option, and it seems to function fine so far. I'm not sure if there are other things about the app that are broken, but if not then maybe this app merely needs some manifest file to be updated?

**Comment by zorn-v** [comment]
Updated
