### ISSUE TITLE
Social login and encryption

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#182]
Hi! 
Does social login works fine with default nextcloud encryption?

Enabled encryption, uploaded new file, but can't do anything with it: neither open, nor download. 

Created local user, login, uploaded file: can download, but still cannot open (may be because of S3)

**Comment by zorn-v** [comment]
It login as regular nextcloud user but without password. Seems encryption use user password. Need investigation.

**Comment by krakazyabra** [comment]
Tell me, if you need more information

**Comment by zorn-v** [comment]
Seems I wrong. As documentation says "You don’t have to do anything special, as it uses your Nextcloud login as the password for your unique private encryption key. Just log in and out and manage and share your files as you normally do, and you can still change your password whenever you want."

https://docs.nextcloud.com/server/19/user_manual/files/encrypting_files.html

**Comment by zorn-v** [comment]
Try use v3.2.6 and check encryption

**Comment by krakazyabra** [comment]
Thank you very much. Will check soon and reply.

**Comment by zorn-v** [comment]
I revert this change in 3.2.7 due to https://github.com/marius-wieschollek/passwords/issues/286#issuecomment-671202924

**Comment by Omaha2002** [comment]
same issue introduced again, loging in through sociallogin settingspage crashes with passwords enabled, loging in locally settingspage ok with passwords enabled.

https://github.com/marius-wieschollek/passwords/issues/286#issuecomment-671202924
