### ISSUE TITLE
no password provided when using mail app

### ISSUE THREAD

**Issue by BigMichi1** [zorn-v/nextcloud-social-login#183]
when a user does a login, e.g. via google, the mail app stops working as the imap account can not be accessed anymore and in the logs an exception is found that a password is missing. i already reported the issue here https://github.com/nextcloud/mail/issues/3271 and the maintainer also suggest to link this issue here

The version of the social-login is 2.4.8

**Comment by zorn-v** [comment]
Possible same as here https://github.com/zorn-v/nextcloud-social-login/issues/182

**Comment by Omaha2002** [comment]
Having the same issue with the passwords app, see created issue at: https://github.com/marius-wieschollek/passwords/issues/286#issuecomment-671202924

**Comment by zorn-v** [comment]
Reverted in v3.2.7
