### ISSUE TITLE
I only see two save buttons on config page of Social Login

### ISSUE THREAD

**Issue by ch31083** [zorn-v/nextcloud-social-login#184]
Anyone knows how to solve this issue?. Thanks

![Captura](https://user-images.githubusercontent.com/58217729/86503415-5eadc280-bd84-11ea-9c8b-eab8b6d20728.JPG)

**Comment by zorn-v** [comment]
What you see in browser console ? And what browser you use ?

**Comment by ch31083** [comment]
Firefox 77.0.1 (64-bit)

TypeError: "e.custom_providers is null"
TypeError: "t.$refs.opt_disable_registration is undefined"

**Comment by zorn-v** [comment]
Check v3.1.3

**Comment by ch31083** [comment]
OMG that was fast! THANKS!
