### ISSUE TITLE
Different width of Telegram login button

### ISSUE THREAD

**Issue by ch31083** [zorn-v/nextcloud-social-login#185]
The size of Telegram login button is different from the rest. Also for some reason that button takes one more second to show.
I can't find in styles.css the way to resize the Telegram button to match with others.

![Captura2](https://user-images.githubusercontent.com/58217729/86525721-35af2f80-be61-11ea-9558-43e0a46ade08.JPG)

**Comment by zorn-v** [comment]
It is not fixable coz telegram button loads via their script in iframe.
