### ISSUE TITLE
Cannot add custom providers (OpenID, Custom OAuth1, Custom OAuth2, Custom OpenID Connect)

### ISSUE THREAD

**Issue by noresistence** [zorn-v/nextcloud-social-login#186]
## Problem description

When installing the Social Login App, and trying to add a custom provider (by clicking the `+`-button), no such provider is created

## Steps to reproduce

* Install a fresh Nextcloud 18 or Nextcloud 19. I used the docker image "nextcloud:18-apache" and "nextcloud:19-apache".
* Don't install additional apps. 
* Install Social Login App v3.2.3.
* In the admin settings section, try to add a custom provider. Nothing happens.

### Browser

I tested with Firefox 78 and Chromium

**Comment by noresistence** [comment]
The issue did not appear in v2.4.8

**Comment by zorn-v** [comment]
Fixed in v3.2.4

**Comment by noresistence** [comment]
I can confirm that this fixes the issue for me. Thank you!
