### ISSUE TITLE
Gitlab as Custom OIDC

### ISSUE THREAD

**Issue by storrgie** [zorn-v/nextcloud-social-login#187]
Was reading through #25 , #83, #106 trying to get an idea for how to link a custom OIDC to my selfhosted gitlab instance and feeling unsure. Is there someone who got this successfully working (maybe @ochorocho)? There doesn't appear to be a baked in gitlab OIDC example (looks like oath only?). Would love some documentation/example/assistance.

**Comment by ochorocho** [comment]
Hey, it is still working for me. See the settings. I think its important to add the correct permissions for Application (Gitlab part)

Gitlab Setup 
![Bildschirmfoto 2020-07-16 um 14 20 45](https://user-images.githubusercontent.com/4623070/87670791-9f3c1180-c770-11ea-8001-c0d20fd4d410.png)

Nextcloud Setup
![Bildschirmfoto 2020-07-16 um 14 21 35](https://user-images.githubusercontent.com/4623070/87670795-a105d500-c770-11ea-8125-64eb47e12f7d.png)

**Comment by storrgie** [comment]
Thanks for this!

How can I link an existing user account (in nextcloud) with a social account (in gitlab)? I have "Prevent creating an account if the email address exists in another account" checked, but I also have "Allow users to connect social logins with their account".

**Comment by ochorocho** [comment]
See your accounts settings page
![grafik](https://user-images.githubusercontent.com/4623070/87672914-fabbce80-c773-11ea-9fd2-d6518cfaa2b1.png)

**Comment by storrgie** [comment]
Thanks a ton for this! I think this is fully resolved for me! I'm glad this is in the issues now for others to discover.
