### ISSUE TITLE
Authorizing requests to Nextcloud with access token

### ISSUE THREAD

**Issue by michzimny** [zorn-v/nextcloud-social-login#189]
Hi,
thanks to nextcloud-social-login, I can log in into my Nextcloud via an OIDC provider. In addition, I'd like to have another app (OIDC client) that would make HTTP requests to Nextcloud on behalf of a user. 

The app gets a user's OAuth2 access token from the OIDC and sends requests to Nextcloud with header: `Authorization: Bearer $TOKEN`. The requests are not authorized by Nextcloud though.

Example request & response:

```
GET /apps/files/ HTTP/1.1
Authorization: Bearer eyJhbG...
...

HTTP/1.1 401 Unauthorized
Content-Length: 43
Content-Type: application/json; charset=utf-8
...

{
    "message": "Current user is not logged in"
}
```

Should this work? Do I do this incorrectly? Or is it not implemented? If the latter, is it a use case related to nextcloud-social-login or it's rather out of scope?

Thank you in advance!

**Comment by zorn-v** [comment]
Login to nextcloud via oauth is not supported in my app. I did not inspect how it works etc. But seems it is not "standard". 
There is another feature in nextcloud for such things, called "federated login" (I did not test it too) 
Did you try it ?

**Comment by michzimny** [comment]
Thanks for prompt reply.

If "nextcloud oauth" means [that](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/oauth2.html), then it's Nextcloud acting as OIDC authorization server, and it's not what I'm thinking of.

First, I'm thinking of a regular setup of your (this) app with external OIDC authorization server. In its regular use case, your app enables to transform OIDC identity to a regular cookie-based session in Nextcloud. After logging in, subsequent user's HTTP requests are authorized with cookies by regular Nextcloud mechanisms.

But in addition, I'd like to only to log in (i.e. start a regular cookie-based user session) via OIDC (as usual with this app), but also to send requests (from 3rd-party app) to Nextcloud that would be authorized with an OIDC access token, issued by the same OIDC authorization server. So apps (Nextcloud, my 3rd-party app, and others) that use the same OIDC authorization server can talk to each other.

I suppose your app only handles the log-in process and does not intercept subsequent HTTP requests to extend how they are authorized. Is that correct?

Could you please give me any reference to that "federated login"? When googling, I find only "federated shares", which seem to be something different than authn/authz.

**Comment by zorn-v** [comment]
>  find only "federated shares", which seem to be something different than authn/authz.

Seems it is the same what I mean. Why you should login in external nextcloud if you can link it in another (core appropriated) way ? 
If it does not fits your needs, I'll check it how to "make it better"

**Comment by michzimny** [comment]
My 3rd-party app is not an external nextcloud. This is a different application or even applications (like Moodle, Jupyter Notebook, and others). To my knowledge, federated shares work for other Nextcloud instances or, possibly, other file sync&share solutions (e.g. ownCloud, etc.).

We have such a set of various web applications. Nextcloud is one of them. To all of them, users log in via a single OIDC authorization server. As a user has the same OIDC-based identity in all these applications and each app can have user's OIDC access token, we'd like to handle use cases, in which the apps exchange users' data, without any additional interaction from user. 

Example use case is that an app accesses certain user files in Nextcloud with such OIDC access token that could be understood by Nextcloud as it already has all the necessary OIDC settings to validate the token.

**Comment by zorn-v** [comment]
Sorry for misunderstanding, "Nextcloud" word in title confused me.

> I suppose your app only handles the log-in process and does not intercept subsequent HTTP requests to extend how they are authorized. Is that correct?

Yes

**Comment by zorn-v** [comment]
Seems it is possible to write another app for you needs.
There is need some table with mapping `token -> uid` (don't know how it will be filled)
Then some app with type `authentication` (apps with this type is loaded always, and before others)
```xml
<!-- info.xml -->
...
<types>
    <authentication/>
</types>
...
```
and in its `app.php` check `Authorization` header and if token belongs to some uid, call something like
```php
$user = \OC::$server->getUserManager()->get($uid);
\OC::$server->getUserSession()->setUser($user);
```

**Comment by michzimny** [comment]
I'll check it. Thank you.

**Comment by zorn-v** [comment]
Also, mapping table may be excess, as bearer token (JWT) can already contain all needed info

**Comment by mjw4tson** [comment]
Hi @michzimny - we've run into a similar issue, were you able to implement token based authorization for the client API?

**Comment by michzimny** [comment]
Hi @mjw4tson, no, not yet. We are still interested but do not have yet timeline for this.
