### ISSUE TITLE
Disable auto create new users should be default

### ISSUE THREAD

**Issue by kowalski7cc** [zorn-v/nextcloud-social-login#190]
The default behaviour should not allow registration from social login, as it could have security involvements. Also enabling automatic user creation should alert the user with a modal informing about the security implications of the action.

**Comment by zorn-v** [comment]
About which security involvements you are talking about ?

**Comment by kowalski7cc** [comment]
If I install the plugin and configure it like with Google, if I forgot to disable the automatic user creation, everyone will be able to login.

**Comment by zorn-v** [comment]
And what security issue here ?
At first this plugin was developed like "registration"

**Comment by ericomeehan** [comment]
Nextcloud accounts need to be created by an administrator by default.  This app defaults to allowing users to create their own accounts without an administrator.  I agree with @kowalski7cc that it would be better if the app had the same default behavior as Nextcloud itself.
