### ISSUE TITLE
Remember Login

### ISSUE THREAD

**Issue by floli** [zorn-v/nextcloud-social-login#192]
Hello,

I use social-login with Mailcow as provider. After each time I close the browser, I need to re-authorize. It would be nice, if there was a feature to remember the login for a given time or until I logout.

I understand that nextcloud sets 4 cookies. The two auth cookies have only session lifetime. I can explicitly overwrite the lifetime, which kind of works, but also seems be overwritten as some point.

Plain Nextcloud, without social-login remembers the login.

**Comment by zorn-v** [comment]
I did not have such problem. 
Just login via google, close browser, and still logged in.
I use NC 19.0.1

**Comment by floli** [comment]
Could you have a look at the cookies, their lifetime and name? (e.g. using Shift+F9 in Firefox)

**Comment by zorn-v** [comment]
![изображение](https://user-images.githubusercontent.com/12619075/90336971-9fa32300-e022-11ea-86a2-3327661e8440.png)

**Comment by zorn-v** [comment]
Did you use http or https ? I notice that firefox logout everyting logged in via http on close.

**Comment by floli** [comment]
It's all https. According to your screenshot, your cookies seem to be the same as my ones, given that the two lines below "Fri, 31 Dec 2100 23..." means something like session timeout. That's why I guess it's more a Mailcow issue. But still, I am happy for any hints!

**Comment by ZipJo** [comment]
I have rolled out Social Login via Slack on our nextcloud instance and all users are reporting the same issue.
The cookies differ between normal accounts an social-login accounts:

Account logged in via Slack:
![image](https://user-images.githubusercontent.com/2634530/104077483-34006300-521a-11eb-90c3-3747ab0641b3.png)

Account logged in with user/pw:
![image](https://user-images.githubusercontent.com/2634530/104077551-788bfe80-521a-11eb-8641-07c06558c828.png)

nc_session_id, nc_token and nc_username are not set with social login.

Any way to change this?
If you point me in the right direction, I could probably fix it :)

**Comment by zorn-v** [comment]
Check v3.6.0

**Comment by ZipJo** [comment]
Sweet, thanks a lot! this appears to be working now, I have the exact same cookies with social login as with normal login now.
I've asked a few of my users that have reported the problem, to test it as well.

Will let you know tomorrow, but I'd expect this issue to be solved now.

Thanks!

**Comment by ZipJo** [comment]
Alright, the issue is solved, my users are happy and so am I 🎉

**Comment by GNEUGNEUGNEU** [comment]
Hi, i'm using Discord oauth and everytime i want to go to my cloud i have to log and approve with discord that i want to use my discord account for nextcloud, how i can set up to always be connected ? Thanks
