### ISSUE TITLE
How can i get it to work?

### ISSUE THREAD

**Issue by Shuvi-Hub** [zorn-v/nextcloud-social-login#194]
This is not a problem but a question
How can I get this to work xD...
i just know a little about discord bots and have no idea how it works... (maybe about a reach presens?)

**Comment by cj2tech** [comment]
the way I have gotten it to work is this.
create app in discord
go to oauth2 settings.
put redirect to https://www.example.com/apps/sociallogin/oauth/discord
![chrome_O25gPdFnDf](https://user-images.githubusercontent.com/9431091/93026711-0db51880-f5d6-11ea-84de-16b2d018812f.png)

once done go back to the general information and copy the Client id and Client secret and put them in to the config App id and Secret

**Comment by cj2tech** [comment]
This is how I have gotten it to work

1. Goto https://discord.com/developers/applications
2. Create New Application and enter a name for app
![image](https://user-images.githubusercontent.com/9431091/93027030-5b328500-f5d8-11ea-9edf-0944a078a8d5.png)
![image](https://user-images.githubusercontent.com/9431091/93027038-6a193780-f5d8-11ea-834a-70a9e14d42be.png)

3. Note down your Client ID and your Client Secret
![image](https://user-images.githubusercontent.com/9431091/93027140-f3c90500-f5d8-11ea-8080-2f89cc5c80b2.png)

4. Goto OAuth2 tab
5. Enter https://www.example.com/apps/sociallogin/oauth/discord (replacing with your url)
6. Save changes
![image](https://user-images.githubusercontent.com/9431091/93027012-39390280-f5d8-11ea-8f2d-0c7c99294b68.png)

On your nextcloud server goto Settings>Administration>Social login
![image](https://user-images.githubusercontent.com/9431091/93027202-69cd6c00-f5d9-11ea-8915-9283110bbff3.png)

1. Under the Discord, section input your App ID as your Client ID from discord.
2. Under the Discord, section input your Client Secret as your Secret from discord.
3. Then click save
Note: I would check off "Disable auto create new users" and Allow users to connect social logins with their accounts

**Comment by cj2tech** [comment]
I would also test it by doing the following:
Test #1 - a basic test that redirects is working and not making new users on your nextcloud.

1. Goto your nextcloud server in an incognito window.
2. Use the sign in with discord button.
3. It should fail and show you an error new user creation has been disabled.

This is good and means that your login is working and not making new users

Test #2

1. On your nextcloud server goto Personal > Social login
2. Click the discord button.
3. Sign in with your discord. After discord authorized you, you should see and "discord - [randomidnumber]" - this means your account is linked.
4. Open another incognito window and sign in to your server using the sign in with discord button

You see your files page which means everything is working as it should.

**Comment by Shuvi-Hub** [comment]
Oh thanks it works fine ^^ can you tell me how it works with the others?

**Comment by Shuvi-Hub** [comment]
oops... i found the Ducumentation xD
