### ISSUE TITLE
Group association does not work?

### ISSUE THREAD

**Issue by tmigf** [zorn-v/nextcloud-social-login#196]
Hi there,

thanks for this nice plugin! I have a problem associating user groups via Keycloak and I don't know if it's a bug or my failure. I'm using the following components:

Keycloak: 10.0.2
Nextcloud: 19.0.3

Here's what I have done:

I created two client roles named "admin" and "standard". Next I created a Keycloak group named "Nextcloud Admin", containing these two client roles. My test user is a member of that group. When I evaluate the Nextcloud client scope for that test user, and have a look at the generated access token, I can see the roles in the "resource_access" claim.

`  "resource_access": {
    "nextcloud": {
      "roles": [
        "standard",
        "admin"
      ]
    },`

In the "Social Login" settings I've created a new "Custom OpenID Connect" provider. The optional "Groups claim" is set to `resource_access.nextcloud.roles`. The login itself works but the roles/groups are not associated with that test user. The groups called "admin" and "standard" both exist in my Nextcloud instance.

So what I'm missing?

Thanks!

**Comment by zorn-v** [comment]
Is checkbox "update user profile on every login" checked ?

**Comment by zorn-v** [comment]
Also groups mapping is mandatory event if it name the same for association without creating

**Comment by zorn-v** [comment]
Necloud side. "Add group mapping" button

**Comment by tmigf** [comment]
Ah thanks. Now I created a group mapping for "admin" and "standard".  But my SSO user is getting only the first role from the "resource_access" array assigned, which is "standard". The "admin" role is still missing. Also when I check the Checkbox "Restrict login for users without mapped groups" my SSO user isn't allowed to login any more. The given error message is: "Your user group is not allowed to login, please contact support".

**Comment by zorn-v** [comment]
Possibly role names in SSO looks different that you map. Try to enable "auto_create_groups" and check what groups will created.

**Comment by tmigf** [comment]
There were no new groups created. Anyway the solution was to create a mapper on Keycloak side and use it as groups claim. The nested claim "resource_access.nextcloud.roles" didn't work. :+1:

**Comment by C0rn3j** [comment]
I've a very similar issue, the group does not get assigned.

When I let the plugin create the groups, it weirdly creates every single group I am a part of in Keycloak with a `keycloak-` prefix.

![image](https://user-images.githubusercontent.com/1641362/94372998-84880080-0102-11eb-99cc-f53af4fc5d45.png)

![image](https://user-images.githubusercontent.com/1641362/94372943-3115b280-0102-11eb-9578-003f6bb9eab6.png)

![image](https://user-images.githubusercontent.com/1641362/94372956-4a1e6380-0102-11eb-823d-bdb73079f3a2.png)
(note I wasn't trying to add to 'admin' specifically but another group, changed it to censor info)

**Comment by zorn-v** [comment]
Possibly you have some typo in group mapping (maybe ending space)

> Note that the creation option has a typo, it should be 'exist', not 'exists'

What about https://www.php.net/file_exists ?

> I tried to also used the Default Group option to at least assign one of the correct groups but that does not work either.

Default group should be assigned always (if update profile option enabled). May be you just forget to save settings while testing or something like this.
https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/lib/Service/ProviderService.php#L442-L445

**Comment by C0rn3j** [comment]
>What about https://www.php.net/filWhat about https://www.php.net/file_exists ?

File exists, files exist.

I'll check out the mapping tomorrow

**Comment by TBG-FR** [comment]
> There were no new groups created. Anyway the solution was to create a mapper on Keycloak side and use it as groups claim. The nested claim "resource_access.nextcloud.roles" didn't work. 👍

Same issue here, no new groups created, and even if I created groups in Nextcloud and add 1:1 mappings, users accounts are created without groups. `resource_access.nextcloud.roles` settings doesn't seem to work, while I see `,"resource_access":{"nextcloud":{"roles":["group_name"]},` in token...

How did you fix your issue ? How do you create a mapper and use it as groups claim
