### ISSUE TITLE
Need more documentation on OpenID and custom OAuth2 configuration

### ISSUE THREAD

**Issue by Aetherus** [zorn-v/nextcloud-social-login#198]
We need more documentation on configuration, specifically

- What's the `redirect_uri`?
- Do they respect the provider's `.well-known` endpoints (`/.well-known/oauth-authorization-server` or `/.well-known/openid-configuration`)? If not, what URL should the server expose for each endpoint?
- How should the response of the userinfo endpoint look like?
- What's the purpose of "Profile Fields" in custom OAuth2 configuration?

**Comment by zorn-v** [comment]
I not so good at documenting ) 
PRs are welcome. Current documentation mostly from them.

> What's the redirect_uri?

It needed in oauth app setting on provider side.

> Do they respect the provider's .well-known endpoints

No idea what are you talking about

> How should the response of the userinfo endpoint look like?

If you talk about OpenID then same as info in id_token, but maybe with additional fields. 
Check this
https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/lib/Provider/CustomOpenIDConnect.php#L28

> What's the purpose of "Profile Fields" in custom OAuth2 configuration?

Some oauth providers may accept `fields` query parameter (AFAIR facebook did something like this). 
Check this
https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/lib/Provider/CustomOAuth2.php#L24-L26

**Comment by dberardo** [comment]
i agree with @Aetherus  , the documentation on how to configure the openId flow is way too open.

@zorn-v the .well-known is one of the endpoints that openId servers must espose.

I am using a custom openId server running on ruby, you can find 3 discovery routes under this link: https://apidemo.energenious.net/oauth/authorize (the last three GET routes)

i have tried all of them in the Social login configuration but they cannot be properly recognized.

I have also tried to figure out what's needed by looking through the discovery algorithm here, https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Thirdparty/OpenID/LightOpenID.php#L671

but php is way too mystic for me to follow through.


I am wondering ... does it App even support openId connect, or only 1.0 and 2.0 ?

**Comment by zorn-v** [comment]
> the documentation on how to configure the openId flow is way too open

"OpenID" and "OpenID Connect" is not the same things.
In social login OIDC is builded on top of oauth2 adapter (of hybridauth lib) and pretty simple (no discovery etc.)
Check https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php class

**Comment by dberardo** [comment]
in the configuration form of Social Login i can only find the field "Identifier url", which is provider specific. The other fields are somewhat not protocol specific (title, etc.).

i had a look at the script you have shared, but i cannot figure out which URL is the App expecting.

I am using openID connect, and the only 3 protocol-specific endpoints that i have are the ones from the link above (which i have corrected ... there was a mistake in the previous link)

here the correct one: https://github.com/doorkeeper-gem/doorkeeper-openid_connect#routes

these are the routes:

GET   /oauth/discovery/keys
GET   /.well-known/openid-configuration
GET   /.well-known/webfinger

**Comment by zorn-v** [comment]
> i can only find the field "Identifier url", which is provider specific

One more time - OpenID is NOT the same as OpenID Connect. You need "Custom OpenID Connect" config section, and there are 3 (one optional) provider specific urls:
* Authorize url
* Token url
* User info URL

In link above that you give it says that "you can customize routes" and seems by default it looks like described here
https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-routes#version--05-1

**Comment by dberardo** [comment]
Thanks for your reply, i have indeed figured out that i was not able to notice the "Custom OpenID Connect", which was somehow hiding between the Oauth2 configuration and the most used Providers below .... 

I have managed to properly connect the client to our custom auth server (in a similar way as i did using Oauth2) but i get the problem that differently from the Oauth2 configuration, here i cannot specify which field should be used to map the user of the Resource server to the one in Nextcloud .... by default the field "id" is used, but i need to change this to "email".

The Portainer service for docker uses a similar approach, and exposes one more form field to map this value: https://documentation.portainer.io/v2.0/auth/oauth/

it would be great to have something like this also in the social login app

**Comment by zorn-v** [comment]
> by default the field "id" is used, but i need to change this to "email"

This never will be done. Many times discussed.

**Comment by dberardo** [comment]
i am sorry @zorn-v  but then the only solution is to have users that share the same ID on both systems ??? is this really the way this App is designed? 

or what should be the shared identifier ?

i cannot find this info in the documentation, this would save everyone a lot of time

**Comment by zorn-v** [comment]
You can "connect" social login account with existing NC account.
https://github.com/zorn-v/nextcloud-social-login/issues/224#issuecomment-778569138
