### ISSUE TITLE
Configure all settings through environment variables or CLI

### ISSUE THREAD

**Issue by gabriel-v** [zorn-v/nextcloud-social-login#199]
There seems to be no way to automatically fill in the login form when looking at the project documentation.

Is there some generic way to fill out all the configuration in [nextcloud-social-login/src/components/settings/provider-types.js](https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/src/components/settings/provider-types.js#L68) through sets of env variables or CLI config commands?

I see the configs get accepted [through the SettingsController here](https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/lib/Controller/SettingsController.php#L52) [and the custom ones here](https://github.com/zorn-v/nextcloud-social-login/blob/31be6e220707bf34ef9f0ab23ecb47f7f83c447a/lib/Controller/SettingsController.php#L64) - do you see a simple way to inject this configuration from the CLI, for example?

If this is as simple as `config:app:set` and `config.app.get`, can we reference some complete examples of automatically setting these up in the readme? Would just run `config:app:set` be enough to set-up the login app? Would running it again with different values update the configuration? Is a server restart needed?

Thanks!

**Comment by zorn-v** [comment]
> Would just run config:app:set be enough to set-up the login app?

Yep. Check `configvalue` field in `*PREFIX*appconfig` table with `appid = 'sociallogin'` in configured instance to know what to pass as values. There is just json encoded arrays. 
WARNING - previously I already changed some fields in them, and updated via migration.

> Would running it again with different values update the configuration?

I think so. I'm pretty sure it is, but you can check if values in `*PREFIX*appconfig` table updated.

> Is a server restart needed?

Nope. It is php babe )

**Comment by gabriel-v** [comment]
Ok, I'll try it and come back with a working example for the readme.

Thanks for the quick reply and the tip on checking that table!
