### ISSUE TITLE
Match social login to the existing account 

### ISSUE THREAD

**Issue by lachmanfrantisek** [zorn-v/nextcloud-social-login#2]
Hi,

thanks for the nice app. Would it be possible to add also support for adding the social login to the existing user? (e.g. in settings I can add a social login like I am adding TOTP/u2f)

Reasons:
- There are people who want to use this but already has their nextcloud account.
- There is not so nice cloud ID made on the registration (probably another issue).

Thanks for your work!

**Comment by lachmanfrantisek** [comment]
Thanks for the quick reply. No hurry, but it would be nice to have it in the future.

**Comment by JanGross** [comment]
Just stumbled across this awesome app. Linking accounts is really the only thing missing right now.  
Is there an ETA on this feature?

**Comment by zorn-v** [comment]
Check settings page in v1.3.1

**Comment by lachmanfrantisek** [comment]
> Check settings page in v1.3.1
 
Works like a charm. Thanks!

----

It also checks whether the account is already used. Good!
