### ISSUE TITLE
Provide 'basic' authentication method for custom OAuth2/OIDC

### ISSUE THREAD

**Issue by Lurkars** [zorn-v/nextcloud-social-login#201]
Cannot find option to change the client authentication method from 'post' (Default from Hybridauth\Adapter/Oauth2) to 'basic'. If custom provider only supports basic method, authentication will fail.

**Comment by zorn-v** [comment]
I can not remember any oauth/oidc provider with basic auth. 
Is it really needed ? Is no option to do "form auth" ?

Or maybe I understand you wrong ? 
"Auth form" (base standard browser) appear and then nothing happens or what ? 
As suppose - basic auth is not from provider at all.

**Comment by Lurkars** [comment]
I mean basic auth in tokenExchangeHeaders, like in https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Provider/Reddit.php in function initialize(). 
Maybe client authentication method was a wrong call here, but OAuth2 gives to possibilities to post token request and one is with credentials in basic auth header.
So a setting for custom OAuth2 to toggle from "post" to "basic" and if set to basic, call
`        $this->tokenExchangeParameters = [
           'grant_type'   => 'authorization_code',
           'redirect_uri' => $this->callback
        ];

        $this->tokenExchangeHeaders = [
            'Authorization' => 'Basic ' . base64_encode($this->clientId .  ':' . $this->clientSecret)
        ];

        $this->tokenRefreshHeaders = $this->tokenExchangeHeaders;`

on initialize()

**Comment by zorn-v** [comment]
No problem to implement it, but every new line of code need to maintain (is it needed only for oauth2 or ouath1 and oidc need it too ?). 
Is it really needed ?

Some time ago I implement oath1 auth by this request https://github.com/zorn-v/nextcloud-social-login/issues/176 and still does not know is it work at all (several time ago I fix critical bug in it). 

So I just write another piece of dead code or what ? :smile:

**Comment by Lurkars** [comment]
I can't speak for OAuth1, but is it a specified option for OAuth2 and because OIDC uses OAuth2 it is related to both! Because CustomOpenIDConnect extends CustomOAuth2 the change should only affect CustomOAuth2 and will be automatically added to OIDC. I didn't take a look at the frontend code, but the settings which method to choose should be available in both: OIDC and OAuth2! Thanks.

**Comment by zorn-v** [comment]
Nobody wants, so closed
