### ISSUE TITLE
LDAP compatible

### ISSUE THREAD

**Issue by chrisfritsche** [zorn-v/nextcloud-social-login#202]
In order to make this APP compatible with LDAP, where users log in with email, it would be necessary to adjust the login method, so as not to add (concatenate) the provider name at the beginning of the uid. This could be flexible, with the inclusion of a config key, which, if enabled, would avoid concatenation. Then, in the auth method (ProviderService), we just need to include something like this, in line 330:

`$ldapCompatible = $this->config->getAppValue($this->appName, 'ldap_compatible', '') === 'true';
		
        $uid = $ldapCompatible ? (string)$profile->email : $provider.'-'.$profileId;
        if (!$ldapCompatible && (strlen($uid) > 64 || !preg_match('#^[a-z0-9_.@-]+$#i', $profileId))) {
            $uid = $provider.'-'.md5($profileId);
        }`

Pls @zorn-v , can you give me feedback? Thanks a lot in advance ...

**Comment by zorn-v** [comment]
I told many times, uid field will not be configurable.
Check https://github.com/zorn-v/nextcloud-social-login/issues/122 for example.
