### ISSUE TITLE
Google error - Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by benasp123** [zorn-v/nextcloud-social-login#205]
Hi. 

I was getting this error message and it took me sometime to figure it out. Hope this might save someone some time. The error message was:

Error 400: redirect_uri_mismatch
The redirect URI in the request, https://example.com.au/index.php/apps/sociallogin/oauth/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

In step 3 viii where it says: Authorized redirect URIs: https://example.com/apps/sociallogin/oauth/google
I had to change this to: https://example.com.au/index.php/apps/sociallogin/oauth/google

**Comment by cahya-wirawan** [comment]
in my case I have also to change from https to http:
http://example.com.au/index.php/apps/sociallogin/oauth/google
even the nextcloud uses https

**Comment by klou** [comment]
Mine was the same -- change from HTTPS to HTTP.  I wonder if the reverse proxy(proxies, I use Docker + an outer SSL proxy) has anything to do with it.

**Comment by klou** [comment]
`'overwriteprotocol' => 'https'` , in `config.php` is likely the one we want.

Then "outbound" server addresses (also Settings->Mobile/Desktop) will show as https.

**Comment by zorn-v** [comment]
Also common mistake to copy/paste secret from google with "space" prefix
