### ISSUE TITLE
Issue calling Nextcloud client API with Authorization header

### ISSUE THREAD

**Issue by mjw4tson** [zorn-v/nextcloud-social-login#206]
Hi all, I'm trying to make some basic calls to the Nextcloud client API using an access token I've received from my OIDC provider, but reading the Nextcloud documentation it looks like it only supports Basic authentication or stored session cookies. 

Is there a way I can exchange my access token for a session cookie so I can make API calls as a specific user?

Thanks!

**Comment by mjw4tson** [comment]
Sorry I should clarify - we've successfully implemented the social login app for end users utilizing the web client, just wanting a way to make requests to the nextcloud API using the same access tokens.

**Comment by zorn-v** [comment]
Is it what you mean https://github.com/zorn-v/nextcloud-social-login/issues/189 ?

**Comment by mjw4tson** [comment]
Thanks for the response @zorn-v!

It looks like @michzimny was trying to achieve the same result. I was hoping that enabling the social login app would also enable JWT access tokens to work when accessing the nextcloud client API via a Bearer token in the Authorization header. It seems like the validation logic between the two use cases would share a lot of similar functionality. Is nextcloud client API access using social login outside of the scope for this plugin?

**Comment by zorn-v** [comment]
> Is nextcloud client API access using social login outside of the scope for this plugin?

Yeah, I think so
