### ISSUE TITLE
HttpClient variables

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#210]
Hi! 
Is it possible somehow to use [these](https://github.com/zorn-v/nextcloud-social-login/blob/0c29e503e3e50b7b0777d0fb692dd3462bde258e/3rdparty/hybridauth/hybridauth/src/HttpClient/Curl.php#L24-L36) variables in global nextcloud's config file? If I change some of them I have risk of rewriting with update. 

Thanks in advance ;)

**Comment by zorn-v** [comment]
> in global nextcloud's config file?

What you mean ? AFAIK nextcloud does not have some http client or options related to it.

**Comment by krakazyabra** [comment]
Nextcloud has config file for user's configuration https://github.com/nextcloud/server/blob/master/config/config.sample.php  
Also throught this config you can set different values for the application, if application supports this. 
Same as for `social_login_auto_redirect`.

**Comment by zorn-v** [comment]
Got it, you mean not nexcloud related vars. Next question - with curl vars you need to change and why ?
Maybe add not curl specified config like ?
```php
social_login_http_client => ['ssl_verify' => true]
```

**Comment by krakazyabra** [comment]
I've changed these two
```
CURLOPT_TIMEOUT        => 45,
CURLOPT_CONNECTTIMEOUT => 45,
```

Our network is quite complicated and specific, with default values I get errors like in this issue https://github.com/zorn-v/nextcloud-social-login/issues/172

**Comment by zorn-v** [comment]
Update to v3.5.0 and you can use
```php
  'social_login_http_client' => [
      'timeout' => 45,
  ],
```
in `config.php`

**Comment by krakazyabra** [comment]
awesome! Thanks a lot!
