### ISSUE TITLE
Uninstall Instructions

### ISSUE THREAD

**Issue by niklas2810** [zorn-v/nextcloud-social-login#212]
Hey there!

First off, thanks for this amazing plugin. However, I noticed that there are no uninstall instructions, neither in the Readme file nor on the plugin page on Nextcloud. 

Is it even possible to migrate existing accounts to normal Nextcloud accounts or is the plugin a requirement if the accounts have been created with it?

**Comment by zorn-v** [comment]
Social login create normal nexcloud accounts, but with one note - it generate random password on account creation. 
So if you need to login in it by general way, you must reset password first.

**Comment by niklas2810** [comment]
Okay, thanks!
