### ISSUE TITLE
Yandex: HTTP error Bad URL

### ISSUE THREAD

**Issue by fazlerabbi37** [zorn-v/nextcloud-social-login#213]
I am trying to configure Yandex as a custom OAuth provider. I have created a client with the following scopes:

- Access to username, first name and surname, gender
- Access to email address
- Access to user avatar

I have put a dummy value for the Callback URL as instructed in the README.

These are my values for Custom OAuth1:
Internal name: yandex
Title: Yandex
Authorize url: https://oauth.yandex.ru/authorize
Token url: https://oauth.yandex.com/token
Profile url: https://login.yandex.ru/info
Logout URL (optional)
Consumer key: ••••••••••••••••••••••••••••••••
Consumer Secret: ••••••••••••••••••••••••••••••••
Button style: None
Default group:None

After saving this I opened my Nextcloud instance page in a different browser copied the URL from the `Log in with Yandex` button and put that as my Callback URL.

Now If I click on `Log in with Yandex`, I get an error saying `Error Signed API request has returned an error. HTTP client error: Bad URL.`

What am I doing wrong? 

Thanks in advance!

**Comment by zorn-v** [comment]
Yandex use OAuth2, not 1

**Comment by fazlerabbi37** [comment]
so the 1 and 2 signifies OAuth1 and OAuth2? It doesn't seem very clear to me as I thought it was 2 Custom OAuth app 1 and 2 :unamused: 

---

I will try with Custom OAuth2 and let know here.

**Comment by fazlerabbi37** [comment]
Thanks @zorn-v! Using Custom OAuth2 and giving all the appropriate info seems to work nicely! I would like to make a PR documenting how to add Yandex in Social Login, do you have any objection?

---

Off Topic [Hopefully helpful for the doc]: 

I want to create users with username and email as Yandex email address so that they can log in with Yandex OAuth. Is it possible? I have checked the `Disable auto create new users` option and created a separate user group and set the default user group to the created group.

It would be extremely helpful if you can answer the question. Thanks for the great app!
