### ISSUE TITLE
Debug error with Social login?

### ISSUE THREAD

**Issue by Borega** [zorn-v/nextcloud-social-login#216]
I cant for the live of me get Sociallogin to work with my institutions Educationplatform. They say the abide to openID rules.
Anyway when turning on Debug I get this message:
`OC_App::registerLogIn() is deprecated, please register your alternative login option using the registerAlternativeLogin() on the RegistrationContext in your Application class implementing the OCP\Authentication\IAlternativeLogin interface`
Using NC 20.
might that be the Problem?
When trying to login I get with Social Login Custom Oauth 2 with the conig the Eduplatform provided I get: 
`Provider API returned an unexpected response.`
With the openid, email, profile scope. openid seems to cause this error. 
Is there a log where this unexpected response is logged?

**Comment by zorn-v** [comment]
> might that be the Problem?

No it is not related. I have no idea what service you try to configure and how.
Seems there is no one of mandatory field in response 
https://github.com/zorn-v/nextcloud-social-login/blob/fd121948c5730d7b793242d8e297b387c0430ec1/lib/Provider/CustomOAuth2.php#L28-L37

**Comment by Borega** [comment]
Thanks for your answer. The question the devs from the other side had was why you did not just use sub to identify. They say they comply with https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by zorn-v** [comment]
You should configure "Custom OpenID Connect" then. Not OAuth 2

**Comment by Borega** [comment]
Iam an Idiot. thank you very much for your help. I got it to work 👍
