### ISSUE TITLE
Breaks installation for other apps while social login is active 

### ISSUE THREAD

**Issue by cj2tech** [zorn-v/nextcloud-social-login#218]
When this app is active it breaks the installation of other apps. My instance is set up with docker and I'm using reverse proxy.
I've followed all of next cloud installation instructions an added `'overwriteprotocol' => 'https',` to my config.php

Below is an image on trying to install an app with social login installed and inabled
![image](https://user-images.githubusercontent.com/9431091/104348066-4c4cd800-54cf-11eb-8e89-90a69129c66c.png)

Below is an image on installing an app with social login installed and disabled
![image](https://user-images.githubusercontent.com/9431091/104348352-a3eb4380-54cf-11eb-8e23-9732d00d5913.png)

**Comment by zorn-v** [comment]
Seems it is bug in nextcloud. First suggestion - it is because my app is not signed. Will dig depeer later.

**Comment by cj2tech** [comment]
how come other apps don't do that unless it's my particular instance

**Comment by zorn-v** [comment]
Seems I found a problem. It is because I have phpseclib in my "vendors" (3rdparty).

**Comment by zorn-v** [comment]
Fixed in 4.0.2
