### ISSUE TITLE
The authorization state is either invalid or alredy consumed

### ISSUE THREAD

**Issue by LecrisUT** [zorn-v/nextcloud-social-login#219]
Currently I am locked out of my server due to this error:
```
The authorization state [state=xx-xxxxxxxxxx] of this page is either invalid or has already been consumed.
```
I've tried using incognito mode and clearing cookies on client, with no success. For some reason I cannot even connect via password so I am unable to edit the settings.

Is there a manual way of editing the settings, e.g. changing the secret.

**Comment by zorn-v** [comment]
> For some reason I cannot even connect via password so I am unable to edit the settings.

You can reset password via cli with `php occ user:resetpassword myuser` in NC dir. 
Also you can enable/disable apps, change settings etc. 
Run `php occ` to list all commands.

**Comment by LecrisUT** [comment]
I've found that the login issue is even more complex, but it's unrelated to this app. For some reason nextcloud keeps feeding me an expired cookie, and no configurations I have tried solves the login issue. My other instance does not have this issue.

I don't know if this is this cookie issue root cause of authorization state not being valid. But even so there is still no manual way of editing the OAuth secrets, or at least none are documented. I'm not sure if the data should be in the database, but I found nothing there to guide me.

**Comment by zorn-v** [comment]
Check https://github.com/zorn-v/nextcloud-social-login/issues/199

**Comment by zorn-v** [comment]
> For some reason nextcloud keeps feeding me an expired cookie

Check server date

**Comment by LecrisUT** [comment]
> > For some reason nextcloud keeps feeding me an expired cookie
> 
> Check server date

Checked. Date is correct. Here is the nextcloud issue for some reference:  nextcloud/server#25328
