### ISSUE TITLE
Usage of deprecated APIs

### ISSUE THREAD

**Issue by lmm-git** [zorn-v/nextcloud-social-login#220]
https://github.com/nextcloud/server/blob/master/lib/private/legacy/OC_App.php#L688 states that the function `registerLogIn` is dreprecated in newer Nextcloud versions (>= 20).

Currently it is used to register the login flow with Nextcloud: https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/AppInfo/Application.php#L75

Are there any plans to update the API usage in the near future?

**Comment by zorn-v** [comment]
I know about that, but there is a blocker in new API. 
A make a PR some time ago with no response https://github.com/nextcloud/server/pull/25063

**Comment by zorn-v** [comment]
Fixed in v4.7.0
