### ISSUE TITLE
LDAP & Social Log in users show as different even though its the same account !!!! !

### ISSUE THREAD

**Issue by JonCSgr** [zorn-v/nextcloud-social-login#224]
Hi , my nextcloud is syncing with LDAP and has SSO using keycloak using social login.

My keycloak is sync with LDAP. 

The users logging from LDAP and the users logging from social login are understanding to be as a different user even though they ae the same user !!! 

E.G log in with user103 not from social log in but normal log in of nextcloud (credentials are pulled from nextcloud that are synced with ldap)
     log in with user103 from social log in to nextcloud (credentials are pulled from keycloak that syncs with ldap)

That user should be the same but Nextcloud understands him as a completely different user !

**Comment by zorn-v** [comment]
To be the same user you should LINK existing NC account with keycloak account. Check "allow_login_connect" option.
Those mappings in `*PREFIX*sociallogin_connect` table. If you fill that table manually "allow_login_connect" option does not needed to be enabled.
If you do not want to create new users you should enable "disable_registration" setting in social login app.

**Comment by JonCSgr** [comment]
Hey , thanks for the quick reply .
Where is the "allow_login_connect" , is it on nextcloud or keycloac i can't seem to find it.

**Comment by zorn-v** [comment]
> Is it the " allow users to connect social logins with their account" on nc social log in settings page?

Yes

**Comment by JonCSgr** [comment]
Also by disabling "disable registration" i get 
Error

    Auto creating new users is disabled
 while logging in.
 
 Thanks for the quick reply once again.

**Comment by zorn-v** [comment]
That is the sense :smile: 
To not allow create new account in nextcloud

**Comment by zorn-v** [comment]
Account mapping MUST BE explicit. Social login does not (and will not) guess is account is the same by fields like email.

**Comment by JonCSgr** [comment]
Hi and terribly sorry for asking so many questions.

I enabled allow_login_connect
Now i am logging in to nextcloud from normal login to user100 - > create a new folder called "FolderTest"
After i log in to Nextcloud from  social log in to user 100 -> i cannot see folder "FolderTest", its like a new user logged in with everything fresh.

Do i need to configure anything else ?

**Comment by zorn-v** [comment]
You already have 2 different user100 users - check their uids.
allow_login_connect allow users to connect account with socials in personal settings

**Comment by JonCSgr** [comment]
I only have one user100 in database on nextcloud . Second user100 (keycloak-ce62b0a8dbb126c799584d3d7987ce13
user100 ) is created after i log in using social login with keycloak BUT that user is the same as user100 .

**Comment by zorn-v** [comment]
> BUT that user is the same as user100

It is from your point of view ) 
How social login app should determine that it is the same ?

**Comment by JonCSgr** [comment]
Yes i understand , i am asking if its possible to make social log in understand that it's the same since they have the same username .

**Comment by zorn-v** [comment]
> same since they have the same username

This never will be done. You can check many closed issues to understand why )

**Comment by JonCSgr** [comment]
So i cant configure it somehow to understand that it's the same user?

**Comment by zorn-v** [comment]
You can use another app that seems fill your needs.
https://apps.nextcloud.com/apps/oidc_login

**Comment by JonCSgr** [comment]
I will try that thanks.

BTW rocket.chat suppors what i mention. Logging from Keycloak & rocket.chat with same user it understands its the same user.

Just saying maybe you want to see how it works and improve this app . Saying from goodwill this app works 100% really good and thanks :)

**Comment by JonCSgr** [comment]
But to be honest i am asking in your first comment you said 
To be the same user you should LINK existing NC account with keycloak account. Check "allow_login_connect" option.

So is it possible or not ?

**Comment by zorn-v** [comment]
> Check "allow_login_connect" option

Is for that you got how it can made via interface. 
Yes, you can link account on sync. 
There is a API for it by the way (I forget about it)
https://github.com/zorn-v/nextcloud-social-login/pull/203

**Comment by JonCSgr** [comment]
Hello , i truly appreciate  your help but all those are way too advanced for me , can you guide me ?

I want my endresult to be that user that exist on nextcloud & user that logs from social log in to be the same account.

My reason is : 
The user on nextcloud is imported from LDAP .
The user on keycloak is imported from  THE same LDAP as above

So in reality is same user , how can i make social log in understand it ?

Thanks again and sorry for too many replies , i just start now on the tech world. Appreciate your help !

**Comment by zorn-v** [comment]
> So in reality is same user , how can i make social log in understand it ?

I seems it like this:
1. Import users from LDAP to keycloak. Saving what ids keycloak is make for user
2. Create (if not exists) users in nexcloud
3. Link NC account with keycloak account (with prefix etc). Via raw `INSERT` to db or via API, no matter

**Comment by JonCSgr** [comment]
1.is done sync is every 1 second
2. yes all users on nextcloud exist on keycloak and vice versa all the same taken from same ldap
3.
So you mean tell keycloak to change id for user to be the same as nextcloud id from api ?

**Comment by zorn-v** [comment]
> So you mean tell keycloak to change id for user to be the same as nextcloud id from api ?

Nope. SYNC SCRIPT should map keycloak ids to NC users

**Comment by JonCSgr** [comment]
ok i have no idea how to make that thanks though . I will try to see if i can find something else .

**Comment by zorn-v** [comment]
Just try to link account and check table in db )

**Comment by JonCSgr** [comment]
What you mean map ? To my understand : 
Find id on keycloac e.g for user101 id is fd29584e-1780-4934-b6e9-2adc5dcf12c5
![image](https://user-images.githubusercontent.com/61245954/107819106-4d4c8000-6d81-11eb-97ba-1c83d5de6432.png)

And now go nextcloud and do what ? This user is the same but its understand as 2 different accounts.  
![image](https://user-images.githubusercontent.com/61245954/107819499-f3988580-6d81-11eb-866f-deb22a15097b.png)

You are really helpful .!!

**Comment by zorn-v** [comment]
> So edit id of nextcloud from keycloak-fd29584e-1780-4934-b6e9-2adc5dcf12c5 to user101 ?

No, add mapping record to `*PREFIX*sociallogin_connect` like
| uid | identifier |
| --- | --- |
| user101 | keycloak-fd29584e-1780-4934-b6e9-2adc5dcf12c5 |

**Comment by JonCSgr** [comment]
I used oidc-login and it works exactly as it should out of the box. Writing this for future people .
