### ISSUE TITLE
Not mapping OpenID standard fields

### ISSUE THREAD

**Issue by jvinolas** [zorn-v/nextcloud-social-login#226]
According to the OpenID standard https://openid.net/specs/openid-connect-basic-1_0.html#Scopes the profile will provide name, family_name fields and I assume that the displayname in nextcloud should be build based on this fields but it doesn't as seen at 
https://github.com/zorn-v/nextcloud-social-login/blob/dc76af81d44b10eca273f04ae35b1993d2e1fe10/3rdparty/hybridauth/hybridauth/src/Adapter/OpenID.php#L222-L235

OpenID Connect defines the following scope values:

![108854732-79b99500-75e8-11eb-8e6c-e65faf12ff2e](https://user-images.githubusercontent.com/2132863/108972535-b4bcd680-7683-11eb-947d-5604b7b3c576.jpg)

At least this is how other CMS like moodle handle that.

**Comment by zorn-v** [comment]
> nextcloud-social-login/3rdparty/hybridauth/hybridauth/src/Adapter/OpenID.php

OpenID is not the same as OpenID Connect.
Check https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php
Anyway there is no need to map all fields.
