### ISSUE TITLE
GitHub login: Restrict to users of specific GitHub organizations

### ISSUE THREAD

**Issue by daniel-richter** [zorn-v/nextcloud-social-login#227]
Hi there,

I was wondering whether it is possible to grant access only to users that are member of a specific GitHub organization.

While browsing around I found a feature "mapped groups". Also, the custom OAuth config has parameters such as "Scope", "Profile Fields", and "Groups claim". However, I can't estimate if and how you can implement some access restriction with it.

The use case is: I do not want to grant access to _all_ GitHub users. Only to those e.g. beeing member of a certain organization or having access to a certain repository. Is it possible to include (and map) those membership information?

**Comment by zorn-v** [comment]
It is not possible for now, as it is not "generic" - need to get url from "organizations_url" profile field, make request, and parse response in own way.

**Comment by manning-ncsa** [comment]
First of all, thanks for sharing this useful app. My problem is similar enough that I thought this issue might be a good place to ask my question. I am using a custom OIDC definition to use GitLab.com as my Nextcloud authenticator. While I am able to authenticate using GitLab and automatically create new users, I would also like to restrict access to only those people in a particular GitLab group. I tried adding the Group ID number in the `Groups claim` field but this did not work. Is there a way to do this?

**Comment by manning-ncsa** [comment]
I finally got it working, so I'll share my config here for others struggling with the settings. These settings allow only GitLab users that are part a specific group (in this example the name of the GitLab group is `my_gitlab_group_name_not_id`) to login to the Nextcloud server (`https://nextcloud.example.com`).

Social Login settings
------------------------------------------

Social Login app settings at `https://nextcloud.example.com/settings/admin/sociallogin`

* [x] Update user profile every login
* [x] Restrict login for users without mapped groups

```
Internal name: gitlab_oidc
Title: GitLab
Authorize url: https://gitlab.com/oauth/authorize
Token url: https://gitlab.com/oauth/token
User info URL: https://gitlab.com/oauth/userinfo
Logout URL: 
Client Id: [client_id_from_gitlab_application_settings]
Client Secret:  [client_secret_from_gitlab_application_settings]
Scope: openid
Groups claim: groups
Button style: Gitlab
Default group: my_existing_nextcloud_group
Group mapping: my_gitlab_group_name_not_id <--> my_existing_nextcloud_group
```

GitLab Application settings
------------------------------------------

The corresponding GitLab application settings (https://gitlab.com/oauth/applications)
```
Scopes: openid
Confidential: No
Callback URL: https://nextcloud.example.com/apps/sociallogin/custom_oidc/gitlab_oidc
```

**Comment by daniel-richter** [comment]
> [...] need to get url from "organizations_url" profile field, make request, and parse response in own way.

Thanks! I played around a bit and tried things out. 

### In Theory

With the GitHub API you can request:

**Check membership of a user**
- [Check if a user is, publicly or privately, a member of the organization.](https://docs.github.com/en/rest/reference/orgs#check-organization-membership-for-a-user)  
  GET `/orgs/{org}/members/{username}` 
- [Get team membership for a user](https://docs.github.com/en/rest/reference/teams#get-team-membership-for-a-user)  
  GET `/orgs/{org}/teams/{team_slug}/memberships/{username}` (OAuth access tokens require the `read:org` scope)

Response if user is a member: __Status 204 No Content_.  
Response if user is not a member: __Status: 404 Not Found__.

**List memberships of a user**
- [List organizations for the authenticated user.](https://docs.github.com/en/rest/reference/orgs#list-organizations-for-the-authenticated-user) (requires at least `user` or `read:org` scope)
  GET `/user/orgs`

### In Practice

I have put my changes into the file `3rdparty/hybridauth/hybridauth/src/Provider/GitHub.php`.

Add `read:org` scope:
``` php
public $scope = 'user:email read:org';
```
The following code goes to the end of the `getUserProfile()` function.

**Check membership of a user**

``` php
$user = $data->get('login');
$org = 'MyOrganizationName';
$team = 'MyTeamName';
$this->apiRequest('orgs/'.$org.'/members/'.$user); //  (204) success if user is a member, otherwise (404) throws exception
$this->apiRequest('orgs/'.$org.'/teams/'.$team.'/members/'.$user); //  (204) success if user is a member, otherwise (404) throws exception
```

**Use memberships of a user as SocialLogin goups**

The simplest solution to solve the problem is to add just the for following lines.  
This will make all the organizations the user belongs to available as groups in SocialLogin/Nextcloud.
``` php
foreach ($this->apiRequest('user/orgs') as $orgData) {
    $org = new Data\Collection($orgData);
    $userProfile->data['groups'][] = $org->get('login');
}
```

It is possible to extend this code so that every team the user belongs to is available as a group:
``` php
$user = $data->get('login');
foreach ($this->apiRequest('user/orgs') as $orgData) {
    $org = new Data\Collection($orgData);
    $orgName = $org->get('login');

    $userProfile->data['groups'][] = $orgName;

    foreach($this->apiRequest('orgs/'.$orgName.'/teams') as $teamData) {
        $team = new Data\Collection($teamData);
        $teamName = $team->get('name');

        try {
            $this->apiRequest('orgs/'.$orgName.'/teams/'.$teamName.'/membership/'.$user);
            $userProfile->data['groups'][] = $orgName.'/'.$teamName;
        } catch (\Exception $e) { }
    }
}
```

### Open Questions

- Is `3rdparty/hybridauth/hybridauth/src/Provider/GitHub.php` the correct place to implement that?
- What is the best solution to implement?
  1. Check membership of organization.
  _Pro_: Does not need additonal scope
  _Con_: Organization name(s) have to be added to configuration.
  2. Check membership of team.
  _Pro_: Fine-grained access-control
  _Con_: Needs `read:org` scope*; Organization/team name(s) have to be added to configuration.
  3. Map organization/team memberships to groups.
  _Pro_: Low implementation effort. No need for additional configuration.
  _Con_: Needs `read:org` scope.

*`read:org` scope: If the OAuth-App (ClientID) belongs to the organization same organization you want to check, this permission is enabled by default. All other organizations have to be activated manually.

**Comment by zorn-v** [comment]
> Is 3rdparty/hybridauth/hybridauth/src/Provider/GitHub.php the correct place to implement that?

No, it is 3rdparty library https://github.com/hybridauth/hybridauth that can be updated etc.

Public info no need any additional scope. If membership in org is public you can get it like this

```php
// lib/Provider/CustomOAuth2.php
//...
protected function getGroups(Data\Collection $data)
{
    if ($orgsUrl = $data->get('organizations_url')) {
        $groups = [];
        $orgs = $this->apiRequest($orgsUrl);
        foreach ($orgs as $org) {
            $groups[] = $org->login ?? null;
            //or
            //$groups[] = (object)['gid' => $org->id ?? null, 'displayName' => $org->login ?? null];
        }
        return $groups;
    }
//...
```
with custom configured OAuth2 provider

**Comment by daniel-richter** [comment]
> Public info no need any additional scope. If membership in org is public you can get it like this

There are two variants to get the organization of a user:

- [List organizations for a user](https://docs.github.com/en/rest/reference/orgs#list-organizations-for-a-user)
  This method only lists _public_ memberships, regardless of authentication.  
  GET `/users/{username}/orgs` (that is what `organizations_url` in user data return)
- [List organizations for the authenticated user](https://docs.github.com/en/rest/reference/orgs#list-organizations-for-the-authenticated-user)
  This lists organizations that your authorization allows you to operate on in some way (public and private memberships) Therefore, this API requires at least user or `read:org` scope.  
  GET `/user/orgs`

Thanks for your code! That can solve the problem, but one drawback is that only public memberships are checked.

**Comment by daniel-richter** [comment]
I extendend your code: The following code reads public _and private_ groups in case the custom configrued OAuth2 provider has `Scope (optional)` defined with `read:org` (otherwise only public organizations are mapped as groups):
 ``` php
    // lib/Provider/CustomOAuth2.php
    //...
    protected function getGroups(Data\Collection $data)
    {
        if ($orgsUrl = $data->get('organizations_url')) {
            try {
                $groups = [];
                $orgs = $this->apiRequest('user/orgs');
                foreach ($orgs as $org) {
                    $groups[] = $org->login ?? null;
                }
                return $groups;
            } catch (\Exception) {
                return $this->apiRequest($orgsUrl);
            }
        }
    //...
```

**Comment by zorn-v** [comment]
Check v4.2.0

**Comment by daniel-richter** [comment]
Thanks for the merge, your code modifications and the new release!

To clarify the handling of `$adapter->apiRequest('orgs/'.$org.'/members/'.$username);`:
- If the user _is a member_ of the organization: The `apiRequest` call is successful (status: 204 No content) - Response if requester is an organization member and user is a member (in this case: requester=user)
- If the user _is not a member_ of the organization: The `apiRequest` call throws an exception with the message "Signed API request has returned an error. HTTP error 404. Raw Provider API response: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}."

I did not include a separate check for the "GitHub" provider (just looking for `['orgs']` in config, what currently is set only for GitHub provider). I followed the implementation of `['authorize_url_parameters']['hd']`, where there is also no distinction after the provider name.

**Comment by zorn-v** [comment]
> what currently is set only for GitHub provider

Yep, main word - "currently" :wink:
But implementation specific to github (hardcoded urls etc.), authorize_url_parameters is "more generic" I think, but maybe it was bad idea to not check that it is google. Time will tell :smile: 
In any case there is no some specific requests etc.
