### ISSUE TITLE
allow multiple domains/subdomains to login via google

### ISSUE THREAD

**Issue by dardbeqiri** [zorn-v/nextcloud-social-login#230]
I have a domain example.com and a subdomain stud.example.com;
I want to be able to allow users to login using only emails email@example.com and email@stud.example.com but at the moment I only can chose one(or am I missing something?).
An even better solution would be to be able to even differ roles between domains/subdomain-s on sign up. 
My users with emails on subdomain stud.... should have access on fewer shares than the users in the main domain or the prof.example.com
Thank you very much for your great work 💪🏻

**Comment by zorn-v** [comment]
README.md
> Details about "Allow login only from specified domain" google setting you can find here #44 You can use comma separated list for multiple domains

**Comment by dardbeqiri** [comment]
Thank you very much, I knew probably I was missing something.
