### ISSUE TITLE
User Connect to Social Account (Google) gives 403

### ISSUE THREAD

**Issue by klou** [zorn-v/nextcloud-social-login#232]
I'm trying to connect a local user to a Social Login provider (google).  However, when I click on the provider from User Settings -> Personal -> Social login -> Connect, it gives 403.

The redirect URL is correct (https://my.nextcloud.com/apps/sociallogin/oauth/google), and I can log in via Social Login.

The login username does NOT exist in Google.  Do they have to match?

**Comment by zorn-v** [comment]
Who gives 403 ? What exactly error sounds like ?

**Comment by klou** [comment]
I'm sorry, it's a HTTP 403.

But that being said, there's something wrong with my nginx.conf.  I reverted some changes and the Connect seemed to work better.
