### ISSUE TITLE
RFE: Social Login Connect -> create/link local Nextcloud User?

### ISSUE THREAD

**Issue by klou** [zorn-v/nextcloud-social-login#239]
Current behavior is to link local Nextcloud users to external service accounts.

But if a user whose account was initially created as a Social Login Account, would it be possible to create/link to a local Nextcloud user here?  Essentially, the other direction.

This would making DAV much easier for the user.

**Comment by zorn-v** [comment]
I can't think of a way to do it right

**Comment by klou** [comment]
Do you have any suggestions for linking the users manually, then?

**Comment by zorn-v** [comment]
Delete "social" user and link it after login with "local"
