### ISSUE TITLE
 Possible improvement in provider to use existing users

### ISSUE THREAD

**Issue by fastrandom** [zorn-v/nextcloud-social-login#24]
Would it be possible to login to a user already created by the LDAP from a custom OIDC provider?
Let me explain: There is a user created "username", when you configure the custom OIDC provider and login, it receives the userID "username" but it creates a new user "provider-username".
Could it be configured in the provider to use existing users in the system?
Thank you.

**Comment by zorn-v** [comment]
You can "connect" any external oauth/openid user to exsisting account with "Allow users to connect social logins with their account" setting enabled. Check account additional settings if this option enabled.
Check https://github.com/zorn-v/nextcloud-social-login/issues/2 issue

**Comment by zorn-v** [comment]
It is dangerous. Imagine user with username 123 with high security data. And some provider CAN return 123 as uid...

**Comment by fastrandom** [comment]
It is correct, obviously only the administrator must manage this configuration under his responsibility. But in a business environment it is useful not to ask 2000+ users to connect manually. Obviously the openId server is also managed by the same administrator ...

**Comment by zorn-v** [comment]
> only the administrator

Nope. Only ACCOUNT OWNER should configure such things.

**Comment by fastrandom** [comment]
From the business point of view it is the responsibility of the administrator to provide ease of access to users, since all applications are integrated with the OpenId server as the only form of authentication..

**Comment by zorn-v** [comment]
Imagine 2:
1. I'm admin with no access to user files.
2. I know and very need of all files of some user
3. Check on your providing setting
4. Configure local oidc provider with user with username that i need
5, BANG. I have full access to that user.

**Comment by zorn-v** [comment]
But. "malicious application" must be in appstore (remember - you not have access to server). And I dont want that my app is become "malicious"

**Comment by fastrandom** [comment]
It's like everything, if the nextcloud administrator wants to access a user's files he can find how to, for example, create a local ldap server, and temporarily configure the ldap settings.
the same case that you described earlier with the OIDC.
What do you think?

**Comment by zorn-v** [comment]
With ldap you can have access to exsisting account created without it ? Does not use it before.

**Comment by zorn-v** [comment]
You can exec something like `INSERT INTO oc_social_connect SELECT blablabla` But I dont insert this opportunity in my app.
