### ISSUE TITLE
exeption during installation -> table already exist

### ISSUE THREAD

**Issue by NowyQuei** [zorn-v/nextcloud-social-login#241]
hi
i have a fresh installation of nextcloud with group folders.
when i try to install the plugin this error apears:
**An exception occurred while executing 'CREATE TABLE "oc_sociallogin_connect" ("uid" VARCHAR(255) NOT NULL, "identifier" VARCHAR(190) NOT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_sociallogin_connect" already exists**

looks like an issue in the installing procedure?

**Comment by zorn-v** [comment]
I can not reproduce it. Seems you missed some details specific to your case.

**Comment by zorn-v** [comment]
Close then
