### ISSUE TITLE
KeyKloak Provider API returned an unexpected response.

### ISSUE THREAD

**Issue by reipes** [zorn-v/nextcloud-social-login#242]
I have follwing issue when I try to login with a user defined in KeyKloak:

 Provider API returned an unexpected response.

I resolved temporary the  problem adding this lines to CustomOAuth2.php

        if (!isset($response->identifier) && isset($response->preferred_username)) {
            $response->identifier = $response->preferred_username;
        }

Are there some other possibilities to resolve this problem. Other where could  these lines be integrated in the code?

Best regards

**Comment by zorn-v** [comment]
All keykloak users does not have problems. Just do not use OAuth provider, but OIDC provider.
