### ISSUE TITLE
Documentation on contributing new providers?

### ISSUE THREAD

**Issue by ostankin** [zorn-v/nextcloud-social-login#244]
I would like to contribute a custom provider (Mail.ru). Since this provider is supported by the underlying library (Hybridauth), adding this provider takes adding a couple of lines (one to [ProviderService.php](https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Service/ProviderService.php) and one to [styles.scss](https://github.com/zorn-v/nextcloud-social-login/blob/master/src/styles.scss)) and a couple of SVG icons in [img](https://github.com/zorn-v/nextcloud-social-login/tree/master/img) directory). I made this change locally on my own server and it works fine (see [commit](https://github.com/ostankin/nextcloud-social-login/commit/7b912cc9f12ac0bbf93cae0aae3ad477a41d44b0) I prepared in my forked repo).

However, when I though about contributing this change officially, I stumbled upon a couple of questions:

1. [styles.css](https://github.com/zorn-v/nextcloud-social-login/blob/master/css/styles.css) is obviously auto-generated from [styles.scss](https://github.com/zorn-v/nextcloud-social-login/blob/master/src/styles.scss). I used an online SCSS complier and CSS minifier, but I would like to generate it precisely the same way you did when building the project.
2. I may have missed some other aspects necessary for the change to be complete.

Is there any guidance or checklist to go through in order to make a contribution?

P.S. The reason why I want to contribute this provider is because it can't be added via "Custom OAuth2" option - it has a very specific user profile retrieval, the custom algorithm can't be used for it.

**Comment by zorn-v** [comment]
1. Just run `npm run build`
2. All fine

PS. Better name it in lowercase as others. Exceptions is for classes (in hybridauth) with capital letter in middle.

**Comment by ostankin** [comment]
Thanks, converted to lowercase, rebuilt the project and submitted a [pull request](https://github.com/zorn-v/nextcloud-social-login/pull/247)!
