### ISSUE TITLE
Mastodon / Element.io support

### ISSUE THREAD

**Issue by kylelondon92** [zorn-v/nextcloud-social-login#245]
Will it be possible to add this as a feature in some of the next releases?

I am not sure if that is doable, sadly I am short on time lately to check or do anything myself.

But if this is an option that can be introduced, I think it would be an awesome addition.

Additionally, if you do not want to include it in the main project, maybe make separate branch of it or give instructions to people how to do it or enable different providers of their choice.

Thanks a lot.

**Comment by Lukas2112** [comment]
In general, perhaps support for Fediverse services could be useful.
