### ISSUE TITLE
Support “ LarkSuite” login

### ISSUE THREAD

**Issue by lin54241930** [zorn-v/nextcloud-social-login#248]
Hello, I see that the "provider" does not have anything to do with "LarkSuite" login. Can the author access "LarkSuite"? 
The document of “LarkSuite” is here  [https://open.larksuite.com/document/ukzMxEjL5MTMx4SOzETM/ukDNwYjL5QDM24SO0AjN](LarkSuite)

**Comment by zorn-v** [comment]
What is it your LarkSuite ? Why someone should implement it ?
