### ISSUE TITLE
Cron job fails when default login is hidden

### ISSUE THREAD

**Issue by JonasPrimbs** [zorn-v/nextcloud-social-login#249]
Hello, I figured out that execution of my cron.php script fails when the hideDefaultLogin option is set to true.
I have configured Social Login for OAuth 2 authentication with a custom Keycloak instance.

In my logs I get the following fatal exception:

[no app in context] Fatal: Exception: The requested uri() cannot be processed by the script '/var/www/nextcloud/cron.php') at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/Http/Request.php line 809
   OC\AppFramework\Http\Request->getRawPathInfo()
1. /var/www/nextcloud/apps/sociallogin/lib/AppInfo/Application.php line 112
   OC\AppFramework\Http\Request->getPathInfo()
2. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 168
   OCA\SocialLogin\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
3. /var/www/nextcloud/lib/private/legacy/OC_App.php line 191
   OC\AppFramework\Bootstrap\Coordinator->bootApp("sociallogin")
4. /var/www/nextcloud/lib/private/legacy/OC_App.php line 131
   OC_App::loadApp("sociallogin")
5. /var/www/nextcloud/cron.php line 54
   OC_App::loadApps()

Any suggestions?
I have unchecked the option "Hide default login" in Settings > Administration > Social Login and then the Cron job succeeded.
But it would be nice if hiding the default login might be possible without crashing the cron.php execution.

**Comment by zorn-v** [comment]
Fixed in v4.4.1

**Comment by JonasPrimbs** [comment]
Works for me, thanks!
