### ISSUE TITLE
Option "Prevent creating an account if the email address exists in another account" not working as expected

### ISSUE THREAD

**Issue by SamuelBlickle** [zorn-v/nextcloud-social-login#251]
The option "Prevent creating an account if the email address exists in another account" seems not to work as expected.

When I manually create a Nextcloud user (1) via the regular Nextcloud user management with an email address, and then log in with an account via OpenID Connect (Keycloak) that has the same email address in Keycloak, a new account (2) gets created in Nextcloud regardless of the state of said setting.

However: The email address field of this Keycloak-based Nextcloud user (2) user is then left empty.

When I log into the Nextcloud instance with the manually created account (1) and try to connect it via the Social login connect option with the Keycloak-based user (2), it shows the message "This account already connected".

When I just log in a new account via OpenID Connect without manually registering a Nextcloud account with the same email adress first, the email address value gets set as expected. So I don't think the problem comes from some connection-related issues between Keycloak and Nextcloud.

**Comment by zorn-v** [comment]
> However: The email address field of this Keycloak-based Nextcloud user (2) user is then left empty.

Seems that field just not filled (transferred to nextcloud) in response. I see misconfiguration, not bug.
