### ISSUE TITLE
App Passwords Changing on Login with Nextcloud 21.0.1

### ISSUE THREAD

**Issue by gary-kim** [zorn-v/nextcloud-social-login#253]
* Ref https://github.com/nextcloud/server/issues/26502
* Ref https://github.com/pulsejet/nextcloud-oidc-login/issues/94

There's currently an issue where logging on with Social Login will invalidate all other app passwords for the user due to an upstream change for 21.0.1.

Thanks for the app, by the way, it's incredibly useful.

**Comment by zorn-v** [comment]
Can you tell what I should do to get "error" and "what expected" please ?

**Comment by Proximus888** [comment]
This, I have the same problem. Because of that I have social login disables for now. 

I saw that there was a update but I don't know if it addresses this issue.

**Comment by zorn-v** [comment]
Seems nextcloud core team make some incompatible changes (and does not know about it).
https://github.com/nextcloud/server/pull/25571/files
I'll check it later and decide how to fix it better.

**Comment by C0rn3j** [comment]
>Seems nextcloud core team make some incompatible changes (and does not know about it).

It seems like plugins need to be updated.

https://github.com/nextcloud/server/issues/26502

https://github.com/pulsejet/nextcloud-oidc-login/issues/94

We reverted `PublicKeyTokenProvider.php` for now.

**Comment by zorn-v** [comment]
Check v4.5.1 for the issue

**Comment by beerlao** [comment]
> Check v4.5.1 for the issue

Works for me, thanks!

**Comment by beerlao** [comment]
> > Check v4.5.1 for the issue
> 
> Works for me, thanks!

Sorry, I was too fast. I still have issues with app passwords being invalidated after some time.

**Comment by klatka** [comment]
> > > Check v4.5.1 for the issue
> > 
> > 
> > Works for me, thanks!
> 
> Sorry, I was too fast. I still have issues with app passwords being invalidated after some time.

Your Works comment motivated me to upgrade nc to 21.0.1 and now I have the same issue :/

**Comment by beerlao** [comment]
> > > > Check v4.5.1 for the issue
> > > 
> > > 
> > > Works for me, thanks!
> > 
> > 
> > Sorry, I was too fast. I still have issues with app passwords being invalidated after some time.
> 
> Your Works comment motivated me to upgrade nc to 21.0.1 and now I have the same issue :/

Sorry :-(

**Comment by klatka** [comment]
@beerlao Np, I could successfully go back to 21.0.0 :)

**Comment by zorn-v** [comment]
Check again v4.5.2

**Comment by beerlao** [comment]
> Check again v4.5.2

It's running for 1 hour now - all app passwords still working. So from what I can tell it works - previously app passwords were invalidatet within minutes. Thanks!
