### ISSUE TITLE
How to only allow users to only login using the configured provider?

### ISSUE THREAD

**Issue by ShadyF** [zorn-v/nextcloud-social-login#259]
Hello,

I've ran into this slight problem and couldn't find any documentation / issues on it.

Basically, we've setup google as our social login with nextcloud. Whenever a user logs in with his google account, a new user is created on nextcloud with a random generated username (for example, `google-100219282268409156769`).

The problem that arises is that there's no stopping someone from setting a password to the newly generated user on nextcloud and logging in using the google username (`google-100219282268409156769`) and the newly set password.

I've looked into setting `'social_login_auto_redirect' => true` in `config.php` but that can be easily bypassed by setting the `noredir=1` query parameter in the url for login page.

Is there anyway to stop users from logging in with usernames and passwords and only allow social login?

**Comment by zorn-v** [comment]
> with a random generated username

It not random, it is id of google user (in your example)

> The problem that arises is that there's no stopping someone from setting a password to the newly generated user

And how "someone" can do this ?

**Comment by ShadyF** [comment]
Apologies. I was referrering to a user resetting his own password and logging in normally with a password.

When I initially opened this issue, I only changed the password of a user from an admin account. This allowed me to be able to login using that user's google id + the newly set password. I assumed users can easily reset their own password and do the same thing.

However, after your comment, I tried doing the password reset process as a normal user and couldn't since I didn't have its "current password" (users created from social login don't have passwords I'm guessing?).

Anyways, sorry for wasting your time, closing this issue, thank you.

**Comment by zorn-v** [comment]
> I tried doing the password reset process as a normal user

Yes, you can reset password via email, but email (if provided) is your, right ?

> users created from social login don't have passwords I'm guessing?

Actually they have passwords that no one knows (random) :smile:
