### ISSUE TITLE
'social_login_auto_redirect' meaning

### ISSUE THREAD

**Issue by danielepercivaldi** [zorn-v/nextcloud-social-login#26]
I cannot understand the aim of 'social_login_auto_redirect' option in config.php.
The behaviour is the same as if it is true / false / absent. And, well, it works like a charm always.

Thanks

**Comment by zorn-v** [comment]
https://github.com/zorn-v/nextcloud-social-login/pull/8

**Comment by danielepercivaldi** [comment]
OK. So it is valid only if ONE alternative access is enable.

Thanks.
