### ISSUE TITLE
restrict login to users without assigned role

### ISSUE THREAD

**Issue by krakazyabra** [zorn-v/nextcloud-social-login#265]
Hi! Is it possible to add restriction to login users without assigned group at all? At keycloak we have users without roles, but they are able to login into nextcloud. May be it is possible to add additional checkbox to settings, like "Restrict login for users without assigned roles"? Application will check, if user has roles, if not - restrict login.
Or to add some "garbage collector" role mapping. If there is role mapping with this GC role, then restrict access.
We cannot delete users from keycloak, that's why we need to define their access by roles.

**Comment by zorn-v** [comment]
There is option `restrict_users_wo_mapped_groups` already exists.

**Comment by krakazyabra** [comment]
> There is option `restrict_users_wo_mapped_groups` already exists.

This option is for mapped groups only. We're using scheme, where each user has his own group. If I enable this option, I cannot login, if there is no mapping, but I cannot make mapping for all thousands of groups :)

**Comment by zorn-v** [comment]
What's a point to create group for one user ?

**Comment by krakazyabra** [comment]
Users should not see each other. Users should be isolated inside groups due privacy rules. Also this allows us to manage amount of applications for each group, set individual sharing policies. 
That's why, when users log in without group, they become members of "nogroup" group :)
I cannot control each user, sometimes there can be mistakes on our backend, which is managing roles in keycloak. That's why checkbox "Restrict login user without assigned role" is important.

**Comment by zorn-v** [comment]
> Users should not see each other

Damn, I thought it is by default in NC (users without groups don't see each other). Some stupid behavior...

I'll add this option then.

**Comment by zorn-v** [comment]
Check v4.6.0

**Comment by krakazyabra** [comment]
Patch https://github.com/zorn-v/nextcloud-social-login/commit/6e646dd1b118a783abbe59d7bf69ce47c105fe00 is working as expected, thanks @zorn-v!
