### ISSUE TITLE
Multi device login

### ISSUE THREAD

**Issue by alimnette** [zorn-v/nextcloud-social-login#267]
Hello,

i use google login.
social-login is in 4.6.0
Nextcloud is in 21.0.1.1

when connecting to another device, the last one is disconnected.
I don't have this behavior with local accounts

What do you think?

Br

**Comment by alimnette** [comment]
Let me maybe more clear

If I connect on 2 devices using google accounts, I'm disconnected from all devices
what do you need from me to have some help from you guys plz :)?

**Comment by zorn-v** [comment]
I guess it is happen when creating new account in nextcloud. In that case - sorry, I can not do anything.

**Comment by alimnette** [comment]
no for all old account too

**Comment by zorn-v** [comment]
Is problem exists by now
