### ISSUE TITLE
Internal Server Error after Upgrade to 4.6.6.

### ISSUE THREAD

**Issue by nils-one** [zorn-v/nextcloud-social-login#270]
Hi there,
I have a Custom OpenID Login configured and everything worked fine. But after Upgrade the login isn't working anymore for any user. I only get the message: 
`{"reqId":"2FWIbcHfx0EMnrLr4ryH","level":3,"time":"2021-05-26T08:09:25+00:00","remoteAddr":"2003:e4:7730:9600:88a4:17ee:4f27:b026","user":"--","app":"PHP","method":"GET","url":"/apps/sociallogin/custom_oidc/spd-ltbg","message":
{"Exception":"Error","Message":"Undefined variable $profile at /nextcloud-root/apps/sociallogin/lib/Provider/CustomOpenIDConnect.php#36","Code":0,"Trace":[
{"file":"/nextcloud-root/apps/sociallogin/lib/Provider/CustomOpenIDConnect.php","line":36,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/nextcloud-root/apps/sociallogin/lib/Service/ProviderService.php","line":318,"function":"getUserProfile","class":"OCA\\SocialLogin\\Provider\\CustomOpenIDConnect","type":"->"},
{"file":"/nextcloud-root/apps/sociallogin/lib/Service/ProviderService.php","line":270,"function":"auth","class":"OCA\\SocialLogin\\Service\\ProviderService","type":"->"},
{"file":"/nextcloud-root/apps/sociallogin/lib/Controller/LoginController.php","line":41,"function":"handleCustom","class":"OCA\\SocialLogin\\Service\\ProviderService","type":"->"},
{"file":"/nextcloud-root/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"custom","class":"OCA\\SocialLogin\\Controller\\LoginController","type":"->"},
{"file":"/nextcloud-root/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/nextcloud-root/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/nextcloud-root/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/nextcloud-root/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/nextcloud-root/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/nextcloud-root/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.2.1","id":"60ae034543e6b"}`
The Nextcloud Version 21.0.2, it runs with nginx and php 8.0.5.

Sadly no user can log in at the moment.

**Comment by zorn-v** [comment]
Sorry, it was typo. Fixed in 4.6.7

**Comment by janikvonrotz** [comment]
Wow! One  hour ago I installed Nextcloud with social login 4.6.6. I added a custom oidc with GitLab and got the issue mentioned above. Looked up the issue here and saw that an update is already available with a fix.

Great work!

**Comment by nils-one** [comment]
Yes, really wow for that fast reaction. Thank you very much for that fast fix. Now everything runs as expected. 

And thank you very much for that great work at all. :smile: :+1:
