### ISSUE TITLE
other  profile token data

### ISSUE THREAD

**Issue by keesee** [zorn-v/nextcloud-social-login#272]
Is there a straight forward way to bring in other data from the token besides mapped groups?  I'm particularly interested in an avatar_url locale phone, and language settings. 

we are currently using saml via keycloack, but I' prefer switching over to OIDC if possible. 
Any best practives on a migration?  If user IDs and email match (same instance, same realm)   should I expect any issues?

Thanks in advance.  Project looks great at a glance :) 

JK>

**Comment by zorn-v** [comment]
You can fork this project and do what you need (opensource rulezz). 
For keycloak you need this file https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php
