### ISSUE TITLE
Migration between Social Login Providers

### ISSUE THREAD

**Issue by Jacob-Roberts** [zorn-v/nextcloud-social-login#278]
Currently, I have a custom OIDC Provider set up. We decided that we would rather not manage our own login service and are trying to migrate to Google. If we get all users to "add Google Login" to their own account and then we delete the custom OIDC provider will the accounts be preserved?
What is the best migration path forward?
Thanks!

**Comment by zorn-v** [comment]
> If we get all users to "add Google Login" to their own account and then we delete the custom OIDC provider will the accounts be preserved?

Yes.

> What is the best migration path forward?

Seems, you proposed best path
