### ISSUE TITLE
Disable elevated password prompt

### ISSUE THREAD

**Issue by jayfk** [zorn-v/nextcloud-social-login#280]
Is there a way to disable the elevated password prompt if the user is solely authenticated through a Social Login? I know that there's the "Disable password confirmation on settings change" per user setting but this doesn't seem to work in conjunction with the LibreSign app. 

Any ideas?

<img width="844" alt="Screenshot 2021-06-18 at 13 52 12" src="https://user-images.githubusercontent.com/2930472/122557507-2a86ec80-d03d-11eb-9bac-a8d3e70c300e.png">

**Comment by zorn-v** [comment]
Consult in LibreSign app
