### ISSUE TITLE
Redirect URI not HTTPS

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [zorn-v/nextcloud-social-login#283]
I am using Keycloak for OpenID-Connect, and I kept getting invalid redirect_uri errors. Finally figured out that it hasn't been passing an HTTPS URI.

Social Login:
```
redirect_uri=http%3A%2F%2Fcloud.DOMAIN.com%2Fapps%2Fsociallogin%2Fcustom_oidc%2FKeycloak
```
If I manually add the missing s, everything works. Is this a configuration issue or a bug?
 \
 \
 \
 \
 \
It's also using HTML character codes instead of regular characters which is strange IMO.
Portainer example:
```
redirect_uri=https://portainer.DOMAIN.com&scope=openid%20profile%20email
```

**Comment by zorn-v** [comment]
![изображение](https://user-images.githubusercontent.com/12619075/124007087-5e3f1a80-da1e-11eb-89c7-b373e17e722a.png)
Check readme

**Comment by Adrian-at-CrimsonAuzre** [comment]
> Keycloak authenticates the user and creates a one-time, very short lived, temporary code. Keycloak redirects back to the application using the callback URL provided earlier and additionally adds the temporary code as a query parameter in the callback URL.
AFAIK there's no way to override the callback URL on the Keycloak side just whitelisting for valid callbacks. Thanks for pointing out the ```overwriteprotocol``` setting, don't know how I missed that.
