### ISSUE TITLE
The Telegram button doesn't appear without Google

### ISSUE THREAD

**Issue by plyaskin** [zorn-v/nextcloud-social-login#285]
Hi all,

Could you let me know how to show Telegram button on the login page without Google (or another except Telegram)? 
![image](https://user-images.githubusercontent.com/9464550/124227691-4908df80-db35-11eb-8a31-2dfdf1f78a01.png)

Otherwise I have just a standard login page with Login and Password.
![image](https://user-images.githubusercontent.com/9464550/124227536-0d6e1580-db35-11eb-9488-5a6e200e1e49.png)

**Comment by zorn-v** [comment]
Fixed in v4.6.14

**Comment by plyaskin** [comment]
> Fixed in v4.6.14

Thank you! 
But still the standard login is active.
![image](https://user-images.githubusercontent.com/9464550/124358799-1ef61100-dc4c-11eb-887c-f77e33e7e09a.png)
![image](https://user-images.githubusercontent.com/9464550/124358757-f110cc80-dc4b-11eb-8f3f-54c39396f731.png)

**Comment by zorn-v** [comment]
Check v4.6.15

**Comment by plyaskin** [comment]
Hi again,

I noticed that the connection with Telegram is displayed with a link, but it is not in the default login.
![image](https://user-images.githubusercontent.com/9464550/124444527-e455bb00-dda8-11eb-9c58-ecb009a32f5e.png)
Could you check and fix it?

**Comment by zorn-v** [comment]
Check v4.6.17

**Comment by smasharov** [comment]
Unable to link new user to Telegram, no Telegram button in "Available providers"
4.6.17

The existing users are working, and able to login from the login page, but the Telegram button in setting is also missing.

**Comment by zorn-v** [comment]
Fixed in v4.6.18
