### ISSUE TITLE
Selfcreated user disabled by default

### ISSUE THREAD

**Issue by danielepercivaldi** [zorn-v/nextcloud-social-login#29]
It would be very nice if there is the option for establishing that selfcreated users are disabled by default.

**Comment by zorn-v** [comment]
You may disable it before adding your first provider. In the same page BTW.

**Comment by danielepercivaldi** [comment]
Oh, yeah, now I understand: sorry, the label is not clear.
I think labels should be:
"Default group that all new users belong to "
"Disable new selfcreated users"
"Allow users to connect their social account to their own user account"
 What do you think?

Thanks
