### ISSUE TITLE
Unable to exchange code for API access token

### ISSUE THREAD

**Issue by SDAdham** [zorn-v/nextcloud-social-login#291]
I am getting the same error **Unable to exchange code for API access token. HTTP client error: Connection timed out after 30000 milliseconds.** as this issue https://github.com/zorn-v/nextcloud-social-login/issues/172

I'm on Gitlab and I am using "Custom OpenID Connect" from "Social Login" and we don't have network problems, but it is on cPanel and gitlab is outside cPanel

Can you please help?

**Comment by zorn-v** [comment]
Try to increase timeout
![изображение](https://user-images.githubusercontent.com/12619075/128816251-72c50ee6-d30e-4d98-8adc-a91dbd609e42.png)

**Comment by SDAdham** [comment]
@zorn-v , where is this file?

**Comment by SDAdham** [comment]
I did edit `config/config.php`, however now i get:
```
Unable to exchange code for API access token. HTTP client error: Connection timed out after 45000 milliseconds
```

**Comment by zorn-v** [comment]
Global nextcloud config located in `config/config.php`

**Comment by zorn-v** [comment]
> I did edit config/config.php, however now i get

Try to increase more. And check all urls for correctness

**Comment by SDAdham** [comment]
I did more and still the same issue:
```
Unable to exchange code for API access token. HTTP client error: Connection timed out after 60000 milliseconds
```

**Comment by SDAdham** [comment]
I double checked, what url does it call when it gives that timeout?

**Comment by SDAdham** [comment]
My configurations match:
```
{"custom_oidc": [{"name": "gitlab_oidc", "title": "Gitlab", "authorizeUrl": "https://gitlab.my-domain.org/oauth/authorize", "tokenUrl": "https://gitlab.my-domain.org/oauth/token", "userInfoUrl": "https://gitlab.my-domain.org/oauth/userinfo", "logoutUrl": "", "clientId": "$my_application_id", "clientSecret": "$my_super_secret_secret", "scope": "openid", "groupsClaim": "groups", "style": "gitlab", "defaultGroup": ""}]}
```

**Comment by zorn-v** [comment]
Check that server with nextcloud can reach https://gitlab.my-domain.org
For example `curl https://gitlab.my-domain.org` in console

**Comment by SDAdham** [comment]
I tested it from the console, there is a network problem :) 👍 , thanks.
