### ISSUE TITLE
OAUTH2 with gitlab - Can not get identifier from provider

### ISSUE THREAD

**Issue by pocovoc** [zorn-v/nextcloud-social-login#293]
Hi there, 

we have an issue when trying to connect next cloud to gitlab via OAUTH2. We receive the error message
"Can not get identifier from provider"

We are using the current version of the plugin. The scope openid on gitlab 
has been activated (non confidential).

The error:

![image](https://user-images.githubusercontent.com/82943692/130592450-18cfe20d-4569-461c-a585-39b775b443e4.png)

**Comment by zorn-v** [comment]
Use "Custom OpenID Connect" for gitlab

**Comment by pocovoc** [comment]
Thank you very much, that worked for us! :)
