### ISSUE TITLE
'Last Login' view in users panel not working for discord

### ISSUE THREAD

**Issue by John-H-Smith** [zorn-v/nextcloud-social-login#294]
With discord registered users won't update their last login value. Because of that, you cannot impersonate the user, because he has to be logged in one time before.
I don't know if this error occurs with other providers too.

**Comment by h05hardman** [comment]
It also occurs with other providers.
Just shows the creation date if they always log in using that feature.

**Comment by zorn-v** [comment]
Fixed in v5.2.0

**Comment by h05hardman** [comment]
thanks! works now <3
