### ISSUE TITLE
"Ce compte est déjà connecté" ("this account is already connected")

### ISSUE THREAD

**Issue by albedo15** [zorn-v/nextcloud-social-login#296]
Bonjour,

Lors de l'utilisation du connecteur Custom Oauth2, un message bloquant apparaît dans ce cas de figure : 

1. Je clique sur le connecteur, et me connecte parfaitement à mon service avec l'Oauth2.
2. Je ferme l'onglet de mon service **sans me deconnecter**
3. Je veux retourner sur le service, et clique de nouveau sur le connecteur, et là le message suivant apparaît : 'ce compte est déjà connecté' et on se retrouve bloqué.

![image](https://user-images.githubusercontent.com/87094370/131489331-8fe7b4c4-0bc7-45d1-a4c2-94ffcf7b7cf0.png)

N'est-il pas possible d'autoriser la redirection même quand l'utilisateur est déjà connecté ?

Merci
__________________________________________________
Hello,

When using the Custom Oauth2 connector, a blocking message appears in this case:

1. I click on the connector, and connect me perfectly to my service with the Oauth2.
2. I close my service tab ** without logging out **
3. I want to go back to the service, and click again on the connector, and there the following message appears: 'this account is already connected' and we find ourselves blocked.

![image](https://user-images.githubusercontent.com/87094370/131489331-8fe7b4c4-0bc7-45d1-a4c2-94ffcf7b7cf0.png)

Is it not possible to allow redirection even when the user is already logged in?

Thank you

**Comment by zorn-v** [comment]
If you already logged in, why you need to click on some connector ? Why just not open index page ?

**Comment by albedo15** [comment]
Bonjour,

Le connecteur chez nous a deux fonctions, il sert également de "raccourcis".
Il s'agit d'un Espace Numérique de Travail destiné à des structures scolaires (enfant dès 10 ans et adultes), l'usage de notre connecteur ici est double :

- l'authentification automatique 
- pouvoir accéder au service nextcloud depuis n'importe quel lieu et n'importe quel appareil sans forcément avoir un raccourci "sous la main" .

Le fait que le connecteur "refuse" l'accès en étant déjà connecté serait un obstacle contraignant pour un certain nombre d'utilisateurs.


--------
Hello,

The connector with us has two functions, it also serves as "shortcuts".
This is a Digital Work Space intended for school structures (children from 10 years old and adults), the use of our connector here is twofold:

- automatic authentication
- be able to access the nextcloud service from any location and any device without necessarily having a shortcut "handy".

The fact that the connector "refuses" it being already connected would be a restrictive access obstacle for a certain number of users.

**Comment by zorn-v** [comment]
If you have only one provider configured you can use `'social_login_auto_redirect' => true` nextcloud system config option (check readme) for autoredirect to auth via that provider from login page.

**Comment by albedo15** [comment]
Bonsoir,
Désolée de la réponse tardive.
Merci pour cette solution, cela permet de contourner le problème, et me convient parfaitement.
Merci

Good evening,
Sorry for the late response.
Thank you for this solution, it works around the problem, and suits me perfectly.
Thank you

**Comment by albedo15** [comment]
Bonsoir,
Je m'excuse de rouvrir cette issue, mais en fait cette solution permet bien de contourner le problème, mais elle en créée un nouveau : 
Les stockages externes ne sont tous simplement plus accessibles depuis l'interface lorsque le paramètre 'social_login_auto_redirect' est à true. si je met false, les stockages externes fonctionnent de nouveau.

Mes stockages externes utilisent "identifiants de connexion sauvegardés pour la session", donc avec "true" il semblerait que les identifiants de connexion diffèrent de ceux avec "false", comment cela se fait-il ? et que puis je faire ?
Avez vous une idée ?
Merci d'avance
![image](https://user-images.githubusercontent.com/87094370/132737484-fce183f3-7de0-421b-84e8-86529490d8e8.png)
![image](https://user-images.githubusercontent.com/87094370/132737604-2205058a-bb93-443f-99e0-08741283374e.png)

Good evening,
I apologize for reopening this issue, but in fact this solution works well around the problem, but it creates a new one:
External storages are simply no longer accessible from the interface when the 'social_login_auto_redirect' parameter is set to true. if I put false, the external storages work again.

My external storages use "saved login credentials for session", so with "true" it looks like the login credentials differ from those with "false", how come? and what can I do?
Do you have an idea ?
thanks in advance
