### ISSUE TITLE
Stockages externes et identifiants de connexion / External storage and login credentials

### ISSUE THREAD

**Issue by albedo15** [zorn-v/nextcloud-social-login#298]
Bonsoir,

Je viens seulement de me rendre compte d'un problème, et je ne trouve pas la solution seule : 

J'utilise des stockages externes qui utilisent "identifiants de connexion sauvegardés pour la session". Voici ma configuration actuelle : 
![image](https://user-images.githubusercontent.com/87094370/132737484-fce183f3-7de0-421b-84e8-86529490d8e8.png)
![image](https://user-images.githubusercontent.com/87094370/132737604-2205058a-bb93-443f-99e0-08741283374e.png)

Lorsque je passe par l'Oauth2 de social login, on se connecte sur le bon compte, mais les stockages externes ne sont tous simplement plus accessibles depuis l'interface.
Cela veut donc dire qu'en se connectant ainsi, les identifiants de connexion doivent différer du "vrai" ?

Avez vous une idée ?
Merci d'avance

Good evening,

I have only just realized a problem, and I cannot find the solution on my own:

I am using external storages which use "saved login credentials for session". Here is my current configuration:
! [image] (https://user-images.githubusercontent.com/87094370/132737484-fce183f3-7de0-421b-84e8-86529490d8e8.png)
! [image] (https://user-images.githubusercontent.com/87094370/132737604-2205058a-bb93-443f-99e0-08741283374e.png)

When I go through the social login Oauth2, we connect to the correct account, but the external storage is simply no longer accessible from the interface.
So that means that by connecting in this way, the connection identifiers must differ from the "real"?

Do you have an idea ?
thanks in advance

**Comment by zorn-v** [comment]
I'm sorry, but I have not your passwords etc. (truly). I have no idea how it may encrypt (possibly via user password). So just dont use my plugin if not compatible.
