### ISSUE TITLE
cron.php throws error when sociallogin is activated

### ISSUE THREAD

**Issue by mkrecek234** [zorn-v/nextcloud-social-login#299]
If I activate sociallogin, the cronjob php -f cron.php fails with this error - if I deactivate sociallogin, the cron job runs without errors. (Latest Nextcloud 22.1.1 and sociallogin 4.8.4) 

o app in context | Exception: The requested uri() cannot be processed by the script '/nextcloud/cron.php')/nextcloud/lib/private/AppFramework/Http/Request.php - line 796: OC\AppFramework\Http\Request->getRawPathInfo()/nextcloud/apps/sociallogin/lib/AppInfo/Application.php - line 118: OC\AppFramework\Http\Request->getPathInfo()/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 178: OCA\SocialLogin\AppInfo\Application->boot()/nextcloud/lib/private/legacy/OC_App.php - line 205: OC\AppFramework\Bootstrap\Coordinator->bootApp() nextcloud/lib/private/legacy/OC_App.php - line 139: OC_App::loadApp()/nextcloud d/cron.php - line 54: OC_App::loadApps()
-- | --

**Comment by zorn-v** [comment]
Fixed in v4.8.5
