### ISSUE TITLE
Restrict login to existing users

### ISSUE THREAD

**Issue by Flore-mozfr** [zorn-v/nextcloud-social-login#3]
Hello,

First of all, thank you for this awesome app which will be a great help for nextcloud admins.
This issue is probably related to issue #2 , but not entirely.
I tried to configure the app with google (which is the one I need more) and tried to login with my google account, it finally worked and I was happy. But then I realized it created a new account on my nextcloud without verifying anything (I had a user with this email). This point is issue #2 .

But my other problem is that it allows anyone to create an account on my private nextcloud instance just using a google account and that is a huge security / privacy issue for me. OK my instance is private (as much as it can be), but this was merely a sandbox for a bigger project.

I am managing a nextcloud instance for a small community (about 40 users in the end) which is not so private: public links will be available. What if suddenly this becomes a target for spammers (or whatever ill intending people) and they create lots of accounts?

What I would expect in the future

- Admin creates users
- Existing users can login using their social login
- Non existing users are not created and are not logged in

I hope you can understand my concerns and provide an appropriate answer.

Once again, thanks for this great promising app!

**Comment by zorn-v** [comment]
> I hope you can understand my concerns and provide an appropriate answer.

Sure. I'm working on it now. Two new checkboxes will appear in settings - "Disable create new user" and "Allow users to connect social logins".

**Comment by zorn-v** [comment]
Check settings page in v1.3.1

**Comment by Flore-mozfr** [comment]
That is so great!!!
I can see  just how I will use it
- Check "Disable create new user" all the time
- Uncheck for a short period of time to allow users to create their account
- Recheck to avoid unwanted users

It will be so much easier for my users and it will help a much larger adoption. At this point it was more like "Boarf, another login/password to remember...". And now I have the perfect counter argument.

I have to test with the mobile apps and it will be perfect.
