### ISSUE TITLE
Auth flow not working behind proxy

### ISSUE THREAD

**Issue by Chrisi-Bavaria** [zorn-v/nextcloud-social-login#309]
Hi, our Nextcloud instance is running in a company network where internet access is only possible via proxy. So Nexcloud is configured to use the proxy to search for updates/plugins etc.
But the social-login is not caring about the proxy setting but is trying to directly reach the (external) IDP in the auth flow to exchange the authcode into access-token. It is failing at resolving the external hostname. Of course only the proxy server itself can resolve external addresses.
So can you please obey the proxy settings configured in nexcloud?
-- Thx Chrisi

**Comment by zorn-v** [comment]
Check v4.9.0 with new option in config.php
![изображение](https://user-images.githubusercontent.com/12619075/139700931-a1820b5a-a239-4520-94d5-9a0a6e2ec91b.png)
