### ISSUE TITLE
merging users

### ISSUE THREAD

**Issue by stratege1401** [zorn-v/nextcloud-social-login#31]
see https://github.com/nextcloud/server/issues/9816 as i dont want to post everywhere.

Thanks.

**Comment by zorn-v** [comment]
A you mean something like this https://github.com/zorn-v/nextcloud-social-login/issues/2 ?

**Comment by stratege1401** [comment]
Yes and no.
Merging userA and userAfromgoogle would be awesome.
But merging userB and userD to userXfromgoogle is more like my idea...

**Comment by zorn-v** [comment]
What about files with same name, user profile info and other things ?
What to merge at least ?
What a great goal behind this ?

**Comment by zorn-v** [comment]
Any suggestions ?
Maybe answer for above questions ?
No ?

CLOSED

**Comment by stratege1401** [comment]
Sorry, i did not answer 

i ask the same question server  side, i receive answer as merging is not, will not be planned for some uuid reason ...

**Comment by zorn-v** [comment]
You did noy configure your server I guess
