### ISSUE TITLE
Social login connect is disabled while it is enabled

### ISSUE THREAD

**Issue by John-H-Smith** [zorn-v/nextcloud-social-login#310]
While trying to login with discord (even the discord social login as custom oauth2 login), there is a message "Social login connect is disabled".
My settings are the following: (german language)
![image](https://user-images.githubusercontent.com/18233867/140555502-fd5c5896-92a5-4d72-8abb-2516821ede70.png)
Hope you can help!

**Comment by zorn-v** [comment]
Regards to l10n you enable "Create users with disabled account" but not "Allow users to connect social logins with their account"
```json
    "Create users with disabled account": "Benutzer mit einem deaktivierten Konto erstellen",
    "Allow users to connect social logins with their account": "Benutzern erlauben, externe Konten mit Ihrem Konto zu verknüpfen",
```
