### ISSUE TITLE
wordpress login

### ISSUE THREAD

**Issue by foscone** [zorn-v/nextcloud-social-login#32]
Hi, I am trying to login to nextcloud with wordpress users but I get "invalid_scope An unsupported scope was requested" error.
I configured wordpress with miniOrange Oauth Server plugin and nextcloud-social-login in this way:
![oauth](https://user-images.githubusercontent.com/29599997/41363283-cec7cd5a-6f33-11e8-93d7-f3525f9b7a4c.JPG)
Wordpress miniOrange indicates to use these parameters:
![oauth2](https://user-images.githubusercontent.com/29599997/41363401-14a9959c-6f34-11e8-8736-02853809dfef.JPG)
Client ID and client secret are provided by miniOrange.
Which error did I commit?
Thanks

**Comment by zorn-v** [comment]
Try to use `openid` scope, or `openid profile`

**Comment by foscone** [comment]
Ok, it works with scope `openid`, not work with `openid profile`.
Once logged in, username is wordpress-4 (the number is wordpress user's number) instead of wordpress user's username or display_name. Is there a way to have in nextcloud the same username of wordpress?
Also the other fields are empty. How can I syncronize all user's data?
![nextcloud](https://user-images.githubusercontent.com/29599997/41472913-19241f5e-70b8-11e8-824d-c31469842f61.JPG)

Thanks

**Comment by zorn-v** [comment]
Wordpress should return `email` and `name` fields in `id_token` payload for this.
https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo

**Comment by zorn-v** [comment]
Is response from "get user info endpoind" standardized ?

**Comment by zorn-v** [comment]
As described here http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims this values may return in `id_token` or via UserInfo endpoint
I can add optional `User endpoint` setting and request it if needed.

PS. Anyway wordpress does not follow standards.

**Comment by foscone** [comment]
If you would add user endpoint settings it will be great.
Once done, will I have to edit CustomOpenIDConnect.php in this way?
```
$userProfile = new User\Profile();
$userProfile->identifier  = $data->get('username');
$userProfile->email       = $data->get('email');
$userProfile->displayName = $data->get('display_name');
```
Is it correct?

**Comment by zorn-v** [comment]
Nope. In `$data` info from `id_token`. And NO again. `identifier` MUST BE unquie, and EXISTS in any case.
Your `username` is fail of this.

**Comment by zorn-v** [comment]
I'll do it later (with bonus of parsing `avatar` claim 😉)

**Comment by zorn-v** [comment]
By the way, can you `var_dump($data)` or `print_r($data)` here https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L21 ?
Is it really needed to do another request ?

**Comment by zorn-v** [comment]
Done in v1.8.0
