### ISSUE TITLE
log out from public browser /computer

### ISSUE THREAD

**Issue by gpopesc** [zorn-v/nextcloud-social-login#320]
hello,

I was using a public computer with standard chrome browser and I used telegram login to access my nextcloud instance. Everything was perfect for login, but when I logout I realized the my telegram user is still there and I cannot clear it. (unless standard option from browser)

My question might look very silly, is there any option in the plugin or from admin panel to clear all unwanted or forgotten logins at least from telegram?

Thank you

**Comment by zorn-v** [comment]
You can close any session on any other telegram device.

**Comment by gpopesc** [comment]
Thank you. I haven't noticed that this option remains active after login in telegram.

**Comment by zorn-v** [comment]
Happy new year
