### ISSUE TITLE
FusionAuth Support

### ISSUE THREAD

**Issue by Tom5421** [zorn-v/nextcloud-social-login#321]
Could we get FusionAuth support/documentation for use with FusionAuth with Custom OpenID Connect, I have my FusionAuth server setup and configured however when my user logs into FusionAuth he just gets redirected back to the NextCloud login page without being logged in.

**Comment by zorn-v** [comment]
Probably (I think) you just wrong configured your FusionAuth instance.
Anyway, check nextcloud logs

**Comment by Tom5421** [comment]
Unfortunately the NextCloud log is showing nothing from the Social Login app, I have checked everywhere for any documentation/log and cannot find anything anywhere.

**Comment by Tom5421** [comment]
I believe there might be an issue in this app, I tested this app and it works perfectly fine: 
https://apps.nextcloud.com/apps/oidc_login

**Comment by zorn-v** [comment]
I'll check it later
