### ISSUE TITLE
Please add 'Allow login only from specified domains' option to yandex config too

### ISSUE THREAD

**Issue by lierdakil** [zorn-v/nextcloud-social-login#324]
AFAIU, it should be enough to duplicate this block, changing the provider name to `yandex`

https://github.com/zorn-v/nextcloud-social-login/blob/f071ad6e19dcaa236744c5cae8a9dbdb1e56e1ab/src/components/Settings.vue#L90-L96

The back-end apparently already has everything required in place (manually setting `"auth_params"` for yandex in `oauth_providers` config works as expected, but it gets reset when settings are modified in the web ui)

**Comment by zorn-v** [comment]
Check later

**Comment by lierdakil** [comment]
Ping. What's the status on this? Would creating a pull request help?

**Comment by zorn-v** [comment]
Check v4.13.0

**Comment by lierdakil** [comment]
Yep, that works. Thanks!
