### ISSUE TITLE
"Log in" button points at localhost instead of proper address

### ISSUE THREAD

**Issue by pktiuk** [zorn-v/nextcloud-social-login#328]
![obraz](https://user-images.githubusercontent.com/45544416/149510974-38851ef4-9c6b-437e-99a7-494a7fd025c1.png)

It points at local address (locahost:PORT) instead of one used to access website (myaddress.com).

**Comment by zorn-v** [comment]
Seems you are behind reverse proxy. Change `overwritehost` in nextcloud config

**Comment by pktiuk** [comment]
> Seems you are behind reverse proxy, which probably not properly configured. You can change `overwritehost` in nextcloud `config.php`

Thanks, it resolved my issue.
