### ISSUE TITLE
Is there any way to block users from changing their display name?

### ISSUE THREAD

**Issue by androbey** [zorn-v/nextcloud-social-login#333]
Hi, 

I am pretty new to Nextcloud, but installed your plugin, which works perfectly, thank you! 

However I have one question: Is there currently any way to block users from changing their display name if they log in via a social provider? Or to ask differently: what would be necessary to achieve this (or even to block avatar / password change)?

Nextcloud's IUser interface provides functions to return corresponding values, but I don't have any idea where to implement those functions /where to extend something. 

Hope somebody can point me in the right direction. In fact, I would even prefer if users, who logged in through social provider), are not even able to edit/view their profile. But I don't think this is currently supported by Nextcloud.

Thanks in advance!

**Comment by zorn-v** [comment]
There is no difference between normal users and logged in via my app.
