### ISSUE TITLE
RedirectUri and state parameter

### ISSUE THREAD

**Issue by EvilBMP** [zorn-v/nextcloud-social-login#334]
Hi I just updated an older instance where I had a working Custom OAuth2 profile. I updated to NC 23 with the latest sociallogin plugin version and now my primary system complaints about the wrong redirect uri. So I checked it and I saw, that since v4? the scope parameter is appended, even if empty and that there is a new state parameter with a changing value. Because of this the OAuth Server always aborts the login process because of the mismatching redirect uri.

What's the state parameter for?

**Comment by zorn-v** [comment]
Check "http" and "https" mismatch. Look at address bar of browser for actual url.
If someone say "about the wrong redirect uri" check it. And you get that you have wrong redirect uri in your app.

**Comment by zorn-v** [comment]
https://github.com/zorn-v/nextcloud-social-login#about-callbackreply-url
