### ISSUE TITLE
未知的提供者 "CustomOpenIDConnect"

### ISSUE THREAD

**Issue by seahurt** [zorn-v/nextcloud-social-login#337]
This is the config detail:

![图片](https://user-images.githubusercontent.com/3347603/156115716-5eeb60e6-2379-4805-b435-c8fe9be7169a.png)

---

I really want to find the solution by myself. But I just don't know how.

Where can I find the user manual? 
Where can I debug the error or see the error log? 

I have no clue what happened when an error occurred

**Comment by zorn-v** [comment]
What url do you have for that provider. 
It should be like https://some.nextcloud/apps/sociallogin/custom_oidc/authing_nextcloud_oidc
That error appear when config can not be found, and config can not be found if you enter wrong url (not configured provider).

**Comment by seahurt** [comment]
`https://some.nextcloud/index.php/apps/sociallogin/custom_oidc/authing_nextcloud_oidc` works

Thanks
