### ISSUE TITLE
No error reporting if login error

### ISSUE THREAD

**Issue by arkanovicz** [zorn-v/nextcloud-social-login#339]
Hi all.

My group mapping was not properly configured. I had to resort to xdebug to find the problem. The following exception:

```
throw new LoginException($this->l->t('Your user group is not allowed to login, please contact support'))
```

from `lib/Service/ProviderService.php:448` is never shown on the screen, all we get is a blank 404 page.

Is there any way to enhance this error reporting?

**Comment by arkanovicz** [comment]
Also, this specific exception wasn't displayed either in the web server error log.

**Comment by zorn-v** [comment]
What version of nextcloud do you use ? How your 404 is looks ?
Normally `LoginException` is displayed as error on login page.

**Comment by arkanovicz** [comment]
Sorry, I meant 401. Nextcloud 21.0.9.

**Comment by arkanovicz** [comment]
Sorry, I meant 401. Nextcloud 21.0.9.

**Comment by zorn-v** [comment]
Yep, status code is 401. But user must see the error like this. 
![изображение](https://user-images.githubusercontent.com/12619075/156928878-8038269f-3f4f-4bd9-b466-251413334cee.png)

Probably you have misconfigured reverse proxy that show empty page on status 401.
