### ISSUE TITLE
Group mapping: map towards several groups

### ISSUE THREAD

**Issue by arkanovicz** [zorn-v/nextcloud-social-login#340]
Looking at the source, it would not be too difficult to allow a mapping from one source group to several nextcloud groups.

One could specify it by listing coma separated values in the destination mapping field. This new feature can easily be backward compatible.

**Comment by zorn-v** [comment]
Why do not put user in several groups on provider side ?
I can not imagine scenario when proposed feature will be useful.
But it may be more inconvenient than now - currently "local" group is select box of existing NC groups.

**Comment by Blackclaws** [comment]
I would definitely second what zorn-v said. You can usually set up mappers that map a single group to multiple groups before putting them into the OIDC token. That way you don't create an arbitrary mapping in nextcloud and keep your source of truth closer to the user store.
