### ISSUE TITLE
Updated required with 24

### ISSUE THREAD

**Issue by nickvergessen** [zorn-v/nextcloud-social-login#341]
`OC\Authentication\Token\DefaultTokenProvider` was removed for Nextcloud 24.
I think you need to go through some deeper changes if you can not easily migrate to `PublicKeyTokenProvider`

See https://github.com/nextcloud/server/issues/29914

**Comment by zorn-v** [comment]
Changed to `IProvider` in v.4.14.0 which require minimum nextcloud 23
