### ISSUE TITLE
How to never have social login app create new users?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [zorn-v/nextcloud-social-login#347]
I am new to the social logins app and trying to set it up how I like it.

**What I have:**

- Private Nextcloud (NC) running
- Manually created users in that NC instance

**What I want:**

- When a user logs in with say, Google SSO, it auto-matches with a matching user that I already have made in NC
- And this is a big one: NEVER create a new user account, under any circumstances.

It is a private cloud for my family with only a handful of known, manually added users; I don't EVER want anyone to perhaps accidentally stumble across my NC and have **any** ability to create a new account. Let's say I have manually created 3 NC user accounts; I only ever want there to be those 3 accounts.

Simply put, I just want my pre-made users to have a second option to be able to login using Google (or FB, or Twitter). NO NEW ACCOUNTS. :)

I've tried messing with the options, but can't' seem to get it right. When I check the box to never create new accounts, I can't even login with a matching google + NC account (something along the lines of  'cant create new accounts' even though neither are new.  But if I leave that box unchecked, when I try to login with any other gmail account that doesn't have a matching pre-made NC account, social logins is going right ahead and creating a whole new account with all of the default NC files and folders in it, that I have to go in and manually delete. I don't want that.

This is all probably coming down to me just not really understanding how the settings truly work, so I'm hoping someone here can simply tell me exactly which options to check/uncheck to accomplish what I'm looking to do?

Thanks!

**Comment by zorn-v** [comment]
You should enable "Allow users to connect social logins with their account" option and then link social account with existing account in personal settings in NC.

**Comment by YouveGotMeowxy** [comment]
@zorn-v 

Thank you. So exactly like this?

![image](https://user-images.githubusercontent.com/39491297/165937547-e4901950-28d1-4e04-8999-b1595ac6b072.png)


and regarding the send part of your comment, do we have to manually login as their user account and manually go into their social login settings and connect it for them first? Or is it supposed to happen automatically?

**Comment by zorn-v** [comment]
> do we (the admin) have to manually login as their user account and manually go into their social login settings and connect it for them first?
Why admin should do this ? How does the admin know what social account user want to connect with NC account ?

**Comment by YouveGotMeowxy** [comment]
> > do we (the admin) have to manually login as their user account and manually go into their social login settings and connect it for them first?
> 
> Why admin should do this ?

Exactly?! lol

> How does the admin know what social account user want to connect with NC account ?

Well, in a case like mine where I manually create just say, 3 NC accounts for family, I know which email they're using because I created their acct with it, which would include (for example) their gmail email address.

**Comment by zorn-v** [comment]
Well, what a problem to ask login and link accounts then ?

If you mean "social login must link automatically by email" - this never will be done. 
Some providers may not have email confirmation for example, and some user can just set it as admin email (if he know it) and become admin.

**Comment by scheepers** [comment]
> Well, what a problem to ask login and link accounts then ?
> 
> If you mean "social login must link automatically by email" - this never will be done. Some providers may not have email confirmation for example, and some user can just set it as admin email (if he know it) and become admin.

Oh well that sucks.

My entire org is on Google. Would like to migrate to NextCloud, but if I can't create accounts attached to existing collectives, have users log into those accounts with their existing Google accounts and hordes of unchangeable usernames like google-1117286574668662423181...

What's the point?
