### ISSUE TITLE
Unable to exchange code for API access token.

### ISSUE THREAD

**Issue by bachns** [zorn-v/nextcloud-social-login#348]
I am doing login to Nextcloud using Keycloak user account. I did the configuration following the instructions [here](https://janikvonrotz.ch/2020/10/20/openid-connect-with-nextcloud-and-keycloak/). But I get the following error: **Unable to exchange code for API access token. HTTP client error: Connection timed out after 30000 milliseconds**. Hope someone can help me.

**Comment by riccardoroccaro** [comment]
Hi, I have a similar issue following the same [instructions](https://janikvonrotz.ch/2020/10/20/openid-connect-with-nextcloud-and-keycloak/). I get the following error: "Provider returned no access_token: &lt;!DOCTYPE html&gt;<...>".
I tried to retrieve by hands the token and the user information as explained in the "Test the login" section of the instructions mentioned above and it works. Just by using social login it doesn't work. Any ideas about why this is appening? Should I open a new issue or am I in the right place?

**Comment by zorn-v** [comment]
> I tried to retrieve by hands the token and the user information as explained in the "Test the login" section of the instructions mentioned above and it works.

Did you tried it from the same server/container where nextcloud runs ?

**Comment by bachns** [comment]
I solved the problem.
The reason is that the Keycloak and Nextcloud containers are not in the same network. So I added `--network` when running the containers.

```
docker network create --driver bridge my-network
docker run -d -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin --network my-network  jboss/keycloak:latest
docker run -d -p 8081:80 --network my-network nextcloud
```

**Comment by riccardoroccaro** [comment]
> 
> Did you tried it from the same server/container where nextcloud runs ?
> 

Actually, I was using a k3d environment with just one node and two pods (and correspondent ingress - one for each) one for keycloak and one for nextcloud. I'll try with a fresh k3s installation and I'll report here the complete configuration so that you can reproduce it.

> Also, regarding to comments, seems urls is changed
> 
> > As it might help somebody else, coming to this post – with a more recent Keycloak version (16+) I had to adjust the paths, basically remove ‘auth’.
> > E.g. «https://$KEYCLOAK_HOST/realms/$KEYCLOAK_REALM/protocol/openid-connect/token» and so on.

Yes, I noticed that during the configuration and I used the URLs suggested by keycloak itself for the endpoints.
