### ISSUE TITLE
bug - upgrading to 4.15.0 breaks plugin

### ISSUE THREAD

**Issue by c-nv-s** [zorn-v/nextcloud-social-login#349]
nextcloud version: 23.0.3
plugin version: 4.15.0

Immediately on upgrading the plugin to version 4.15.0 the social login functionality breaks and is no longer available on the login screen.
the logged in admin is also unable to access the nextcloud settings menu (appurl.com/settings/user) and receives an 'internal server error' message when attempting.

will see if I can add more info once available

**Comment by c-nv-s** [comment]
php 7.3

**Comment by zorn-v** [comment]
Yep, that version was require 7.4 
Update to v4.15.1

**Comment by c-nv-s** [comment]
that fixed it! Amazing, thanks for the speed of your response!
