### ISSUE TITLE
Social Login with Android app

### ISSUE THREAD

**Issue by Dicafr** [zorn-v/nextcloud-social-login#35]
Nextcloud 13.0.3
Social App 1.8.0
Using Google login option only (authorized url https://mydomain.com/apps/sociallogin/oauth/google)

The Nextcloud instance is being accessed through a web browser (computer) and Android app. Everything works great on the web browser (both computer and Android devices). The Google button is pressed and the user is redirected to the Nextcloud instance.

The problems start with the Android app. The button to login using Google is there as expected. When pressed, it shows a login screen (I would have expected it to use the credentials of the account on the Android device). Once the user logs in, the web page version of Nextcloud is displayed and not the Android frontend. It's like the web page that is being displayed for login is never closed and the user is never really logged in. After about 30 seconds, at the bottom of the screen, the "go back to old login method" message shows up. Clicking on it brings the user back to the login page. (An example of this problem [here ](https://github.com/nextcloud/android/issues/1587) although the cause of the problem is different). If I disable the Google login, the problem disappears.

Is there anybody else having problems login in with the Social app on the Android app? I haven't tested with the iOS version.

Thank you for this great addition to Nextcloud! You are making Nextcloud much more accessible!

**Comment by Dicafr** [comment]
Sounds good. I wasnt sure if each app had to manage their own section on the different platforms. I will post over there and see what they say.

**Comment by MorrisJobke** [comment]
We need to check what the social login does wrong regarding the login flow. Usually the login flow does this:

* show "grant permission"
* once clicked show the login screen (or redirect to a saml provider if user_saml is used)
* then the user authenticates with whatever method is wanted
* (saml only) for saml the user is redirected back to the login screen
* the login continues and notices that the authentication happens - there the critical part takes place: it checks if the user is in a browser or in the login flow of an app and if the latter is the case it does not a redirect to the files app but to a special URL to give the app specific credentials to that app (it basically opens a url like this: nc://login?serverurl=SERVER&userid=ID&token=TOKEN)

Could it be that the social login app does not respect the last step somehow? Then we should fix it to make it work with all the other apps, as they use the login flow as well.

See https://docs.nextcloud.com/server/14/developer_manual/client_apis/LoginFlow/index.html for the client side documentation

**Comment by zorn-v** [comment]
Yep, it does not follow login flow https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L233

**Comment by MorrisJobke** [comment]
> Yep, it does not follow login flow https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L233

@rulzer @christophwurst Maybe you could help to point to the correct commands

**Comment by ChristophWurst** [comment]
cc @rullzer

**Comment by zorn-v** [comment]
I tried to implement in such way https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L248 but got 401 error response

**Comment by zorn-v** [comment]
It seems that just needed to redirect to `redirect_url` if it exists

**Comment by zorn-v** [comment]
Some confusing is occurring.
If I put `die($this->session->get('client.flow.state.token'))` here https://github.com/zorn-v/nextcloud-social-login/blob/c7730a50a9414946e70fba494ea4f9aeb1c38637/lib/Controller/LoginController.php#L239
it prints state token as expected, but if I put it here (redirect follow to /login/flow/redirect) https://github.com/nextcloud/server/blob/v13.0.4/core/Controller/ClientFlowLoginController.php#L207-L218 nothing printed like session was cleared. I cannot understand why.

**Comment by zorn-v** [comment]
If comment this line https://github.com/nextcloud/server/blob/v13.0.4/lib/private/User/Session.php#L365 all works fine. Will try to find workaround.

**Comment by zorn-v** [comment]
Damn, it needed to add  `@UseSession` annotation to controller methods. Seems now I can remove (or improve) `SessionStorage` for `Hybridauth`

**Comment by zorn-v** [comment]
Fixed in v1.9.0

**Comment by MorrisJobke** [comment]
Thanks a lot 👍

**Comment by Dicafr** [comment]
Tested -- works great. Thanks so much @zorn-v @MorrisJobke

**Comment by supportreq** [comment]
I tried it with Facebook on nextcloud.com demo server and used the Play Store Beta app but didnt work.. it redirected me to 404 page not found error.. any suggestions?
