### ISSUE TITLE
Missing Documentation for various OAuth2 Providers.

### ISSUE THREAD

**Issue by lapidary-master** [zorn-v/nextcloud-social-login#352]
While Facebook, GitLab, Google, Telegram & Twitter all have documentation, the following providers while they are provided in the application administrator settings, they do not have any documentation linked to them.

These are the following providers that *do not* have any documentation;
- Amazon
- GitHub
- Discord
- QQ
- Slack
- Mailru
- Yandex

**Comment by zorn-v** [comment]
You are welcome to write that docs :smile:
