### ISSUE TITLE
Feature request: Allow login only from multiple specified domains

### ISSUE THREAD

**Issue by strozzascotte** [zorn-v/nextcloud-social-login#358]
It would be useful to be able restrict the login to multiple domains or subdomains.
We use Google Workspaces for education and multiple subdomains exists such as:
- @students.university.edu
- @academics.university.edu
- @administration.university.edu
- @campus.university.edu

would be nice to use a selection of those as a filter for access NextCloud.

P.D. Awesome work.

**Comment by zorn-v** [comment]
> Details about "Allow login only from specified domain" google setting you can find here https://github.com/zorn-v/nextcloud-social-login/issues/44 You can use comma separated list for multiple domains

README.md

**Comment by strozzascotte** [comment]
Thank you very much. Sorry for duplicate the request.
