### ISSUE TITLE
Discord Invalid OAuth 2 Redirect URI

### ISSUE THREAD

**Issue by Merith-TK** [zorn-v/nextcloud-social-login#359]
![image](https://user-images.githubusercontent.com/10422110/173248451-e98e0ad2-2ea1-4391-83a0-307dd00398d1.png)
![image](https://user-images.githubusercontent.com/10422110/173248467-fdadfb0e-9371-4075-b5e1-57dff97da3ea.png)
![image](https://user-images.githubusercontent.com/10422110/173248507-a1bc5a09-78b0-46ae-ba37-f69d868fa678.png)

**Comment by zorn-v** [comment]
It means that you configure wrong url in discord OAuth app.

> You can copy link of certain login button to get proper "redirect url" for OAuth app setting.

README.md

**Comment by Merith-TK** [comment]
does not help, as there is no documentation for this

**Comment by Merith-TK** [comment]
having this exact issue on github login

**Comment by pktiuk** [comment]
What URL did you set in discord settings?
`http://mywebsite.com:9000/apps/sociallogin/oauth/discord`
Is it something like that
