### ISSUE TITLE
Cryptic names

### ISSUE THREAD

**Issue by ochorocho** [zorn-v/nextcloud-social-login#36]
Would it be feasable or make sense to have "readable names" ?

Initially the users name is something like `OIDC-GitLab-13c45d4c253d5dad3541d3d1`.
Is it possible to use Gitlabs store details?

**Comment by zorn-v** [comment]
As mention here https://docs.gitlab.com/ce/integration/openid_connect_provider.html

> Only the `sub` and `sub_legacy` claims are included in the ID token, all other claims are available from the `/oauth/userinfo` endpoint used by OIDC clients.

So you need to configure optional user info url like `http://localhost:10080/oauth/userinfo`

**Comment by geosphere** [comment]
> So you need to configure optional user info url like http://localhost:10080/oauth/userinfo

Unfortunately I did not find in the documentation how to do this. Any ideas?

**Comment by zorn-v** [comment]
Just provide `User info url` How to document it ? "Type user info url in user info ur fieldl" ?
