### ISSUE TITLE
Social Login parameters page empty

### ISSUE THREAD

**Issue by Vilerant** [zorn-v/nextcloud-social-login#360]
Hello.
I'm trying to install a test Nextcloud server (containerized with a MySQL DB) with the Social Login app enabled but when I try to go to its settings the page is mostly empty.

[<img src="https://i.ibb.co/kBJyzH8/Capture.png" alt="Capture" border="0">](https://ibb.co/kBJyzH8)

I already tried to install the app with the GUI and manually on the server but no changes.
What to do ? Thanks in advance.

**Comment by zorn-v** [comment]
Check settings in "Administration" section

**Comment by Vilerant** [comment]
Oh, how thoughtless. Sorry for the mistake. Thank you very much for your time.
