### ISSUE TITLE
How to fill in the GitHub section correctly Allow login only for specified organizations？

### ISSUE THREAD

**Issue by axty666** [zorn-v/nextcloud-social-login#361]
When I fill in the relevant options of Allow login only for specified organizations, no matter what I fill in: the link of the organization, or the displayed name of the organization, or the real name of the organization, it will prompt this:
`Login is available only to members of the following GitHub organizations: xxxxx`
How do I fill in correctly? Or is the owner of the organization not considered a member?
I use Baidu translation to translate, so it may look strange.

**Comment by zorn-v** [comment]
It should looks as `xxxxx` in your example.
You can check response http code on https://api.github.com/orgs/{org}/members/{user}

**Comment by axty666** [comment]
Thank you very much. This problem has been solved successfully. Wish you happy every day!
