### ISSUE TITLE
Prompt after configuring Custom OAuth1 and logging in: Signed API request to http:// has returned an error. HTTP error 0. Raw Provider API response: .

### ISSUE THREAD

**Issue by axty666** [zorn-v/nextcloud-social-login#362]
Use:WP REST API - OAuth 1.0a Server + WordPress as th OAuth1 server.
Configure according to [WP-API/OAuth1/blob/master/docs/basics/Auth-Flow.md](https://github.com/WP-API/OAuth1/blob/master/docs/basics/Auth-Flow.md)'s documentation.
But when I actually tested, it said: Signed API request to http:// has returned an error. HTTP error 0. Raw Provider API response: .
I don't think this is the problem of the server, because it doesn't seem to be a mistake in the authorization process.

**Comment by axty666** [comment]
How can I check the problem properly?

**Comment by zorn-v** [comment]
Try to run `curl http://oauth-endpoint` on nextcloud machine/container. 
Where `http://oauth-endpoint` is you configured endpoint

**Comment by zorn-v** [comment]
Wait, your error looks exactly what you wrote (`Signed API request to http:// has returned an error.`) ?
If yes, then you do not configure it properly as there is no url at all.

**Comment by axty666** [comment]
I see. Thank you very much
