### ISSUE TITLE
Custom login button text

### ISSUE THREAD

**Issue by marcopalumbo** [zorn-v/nextcloud-social-login#364]
Hi everybody

I know this request may sound silly but often cosmetic adjustments are those who make solutions stepping up from "working" to "perfect"
It would be really nice if the text shown in the login button is exactly what is entered in the field "Title" without the prefix "Log in with". This will allow to use any custom wording in any language

On language translation, it would be also nice to have italian translation file, I can translate .js and .json files for you if needed.

**Comment by zorn-v** [comment]
> On language translation, it would be also nice to have italian translation file, I can translate .js and .json files for you if needed.

Well it'll be fine. I'm not a polyglot, all translations except 'ru' was done by users.
