### ISSUE TITLE
Please add mailru provider in "Allow login only from specified domain" array in ./js/settings.js

### ISSUE THREAD

**Issue by petrov-it** [zorn-v/nextcloud-social-login#368]
Hello and thanks for your code!
I'm a noob in git, and i'm not sure that only one line needs a pull request.
here it is (for unminified code):
%diff ./js/old_settings.js ./js/settings.js 
9604c9604
<                                     ["google", "yandex"].includes(r)
---
>                                     ["google", "yandex", "mailru"].includes(r)
it worked for me.
Would you be so king and make changes without pull request?

**Comment by zorn-v** [comment]
Done

**Comment by petrov-it** [comment]
Спасибо!
