### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [zorn-v/nextcloud-social-login#371]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

Thanks :-)

**Comment by zorn-v** [comment]
What point of such "overcomplicate"

**Comment by p-bo** [comment]
For instance:
- much more translators will get involved, because without it, they will newer even know about possibility to translate this app. As you asked - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c
(se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive)).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users) 

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

Helped this to better understanding, how this one-time effort would continuously improved your app without any future work for you please?

**Comment by zorn-v** [comment]
I rephrase the question: why I should depend on some external service ?
Without any benefits. L10n is for beauty, not for work.

**Comment by p-bo** [comment]
It is recommended way by Nextcloud developers. And there is no unavoidable dependency - it is just additional (and as stated, very efficient one) - it is still possible to contribute translation in direct git edit way as is used now.

Benefit of L10n is to make easier/possible to use apps even for people, who don't understand English (enough).
It is understandable, that from point of view of software developer, who must be proficient in English from principle, it is hard to have empathy for people who are not...

**Comment by p-bo** [comment]
And it shouldn't take much time of your time - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). There you will get checklist of only few things to do as for example this: https://github.com/nextcloud/docker-ci/issues/426 and you can ask [rakekniven](https://github.com/rakekniven) if something is unclear to you. Hope it helps :-)

**Comment by p-bo** [comment]
For motivation: This developer also at first [was not so fond](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1260663047) of this approach, than [he agreed to try](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1268635618) and at the end, [was very pleased](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1274590428) with result! :-)

**Comment by zorn-v** [comment]
Done

**Comment by p-bo** [comment]
That's great! - many thanks for this improvement for users of your app and Nextcloud (and translators too ;-) ) :-)

**Comment by zorn-v** [comment]
> it is still possible to contribute translation in direct git edit way as is used now.

This is not true - bot just erase those changes. You totally lose control of l10n with it. 
For example it remove ja_JP translation completely, and I cannot to restore it in transifex because does not member of "Japan" team.

**Comment by p-bo** [comment]
Foremost, very sorry for giving wrong information - was really under impression it is working that way.
But for recipients of translation (users) is situation much improved. Analysing and comparing state just before continuous translation workflow deployed - https://github.com/zorn-v/nextcloud-social-login/blob/395349a26c059749aa3ef68eb7e79efac133a6e4/l10n and after:
- .js and .json files were containing only fraction of translatable strings, with their numbers not even the same among languages (even .js and .json files of the same language contained different number of strings to translate). Now all languages are containing the same number of translatable strings (to this date 66) => now it is possible to translate everything, always in sync with latest state of source code
- for ja_JP, there were present and translated 22 (resp. 24 strings - .js not in sync with .json) strings (thus 2/3 of source strings were missing)
- looking at current progress of translations https://www.transifex.com/nextcloud/nextcloud/sociallogin/

  * de - previously stub, now **complete** => win
  * fr - previously stub, now similar and improving => win
  * ja_JP - previously stub, now untranslated => (temporary, see bellow) loss
  * pt_BR - previously stub, now over 60% => win
  * ru - previously stub, now (thanks to you) over 50% => win
  * zh_CN - previously stub, now over 10% => (for now) tie
  * zh_TW - previously stub, now over 6% => (for now) tie

And as bonus - new, before not existent translations:
  * hu - over 16%
  * bg - **complete**
  * cs - **complete**
  * sl - over 13%

And situation will become even much better in coming weeks - see example of another recently added (to continuous localization workflow):
- ticket: https://github.com/H2CK/oidc/issues/16
- result: https://www.transifex.com/nextcloud/nextcloud/oidc/
(two dozens of complete translations in comparison with half of this number of really incomplete ones)

Does this all, at least partly, improving your feeling regarding this please?

**Comment by zorn-v** [comment]
> even .js and .json files of the same language contained different number of strings to translate

Because it is enough. `json` - for php strings (`$l->t('Translable php string')`) and `js` for `js` (`t('appname', 'Translable js string')`). Bot just throws everything into a pile without taking care of it.

BTW, you also need to adapt sources like https://github.com/zorn-v/nextcloud-social-login/commit/82e22aac11e662346c1bc1a9611fe91bb8b593a1 and https://github.com/zorn-v/nextcloud-social-login/commit/585a5d9eb452efab2557d0a21555d3f19dc3a871
I wait now for next sync to check is everything ok now.

> de - previously stub, now complete => win
> ...

Actually not, there is not all string in transifex now :wink:  

> Does this all, at least partly, improving your feeling regarding this please?

Does not decided yet

**Comment by p-bo** [comment]
Thanks again for all that your work (lot of commits) here to adapt source code of app for Nextcloud bot / Transifex workflow and also work done on infrastructure of bot itself (https://github.com/nextcloud/docker-ci/pull/458) - appreciated!
