### ISSUE TITLE
change or remove prefix for usersnames groups

### ISSUE THREAD

**Issue by xundeenergie** [zorn-v/nextcloud-social-login#372]
Hi!
I tried social login via openid and keycloak.
So i have to set a name for the authenticator, which is used as prefix for usernames and groups. 

I get the groups via mapping in keycloak to be used in nextcloud. So the groups in nextcloud are named other than in my ldap (datasource for keycloak).

And if i use different custom authenticators with this plugin (my nextcloud is reachable via 2 domains, both use the same ldap-source) my groups are double, but with different prefixes...

Is it possible, to make the prefix optional? 
A checkbox in the provider-config "Do not use prefix"

Also the username is prefixed. I understand, why you add this. But change from local login to openid-login does not work. it is a new user.

And is it possible, to map another criteria from the token as username? The other Openid-Plugin for Nextcloud can do this mapping via serverside configuration. I have a managed nextcloud, and no possibility to use this plugin.

**Comment by zorn-v** [comment]
> Is it possible, to make the prefix optional?
A checkbox in the provider-config "Do not use prefix"

No. OAuth is not trusted source, and something like "admin" can arrive from there.
All users in group "admin" is admins in nextcloud by the way.

**Comment by xundeenergie** [comment]
I told you... this is a managed service, i have no server-access.

On the other nextcloud-server, i use, i have server-access.

I mean, let the admin choose for each authenticator, i it is a trusted source, then i can let the prefix away... if it is not a trusted service, usernames and groups have a prefix.

**Comment by zorn-v** [comment]
> I mean, let the admin choose for each authenticator, i it is a trusted source

Most "admins" configure as "internet says"

**Comment by xundeenergie** [comment]
I'm not able, to use another Plugin.
I found two.
This and one i can configure serverside.

On the on instance of nextcloud i have no server-access. It is a managed service. So i have to use this plugin...

**Comment by zorn-v** [comment]
So, adapt you needs to plugin requirements then.

**Comment by xundeenergie** [comment]
Oh...

No.

I'm the admin from my keycloak-instance. Therefore THIS source for authentication is save.

Let the admin choose, which authenticator is save, and which not. Please.

Make a Choosbox for every custom Authenticator, and give an advice next to the checkbox.

Please.

You can use Openid and ldap together. Openid for authentication, ldap for profile-informations and groups. With prefixed group- and usernames, you break this workflow.

**Comment by zorn-v** [comment]
Other users find a way. You ask to **ck security just for your needs.

**Comment by zorn-v** [comment]
Oh, forgot. This never be done )

**Comment by xundeenergie** [comment]
You break the possibility to authenticate via openid AND get user-infos via ldap.

**Comment by zorn-v** [comment]
LDAP is not my responsibility.

> Please tell my, why is a selfhostet

Because I do not know selfhosed it or not. And no, "admins" should not change it if it critical.

**Comment by zorn-v** [comment]
> You break the possibility to authenticate via openid AND get user-infos via ldap.

Well, Okay. I know at start that will be request like "give-me-full-acess-to-everything". If you want - just fork. If you cant - sorry.

**Comment by xundeenergie** [comment]
Please. Don't be rude.

I tell you the situation here. And you will sit on my face...

There is a managed nextcloud. 5€ for 1TB space. It's hetzner, if you know.
I have my own Nextcloud at a hetzner vserver. It is too expensive to resize the space to this size i can get for 5€, but managed.

I know, LDAP is not your job. But Nextcloud allows you to make authentification via keycloak but get users informations (CN, Avatar-Picture, Phone-Number... and so on) via LDAP. 

And, maybe you do not understand, what i want... 

Not to select every OpenID-Connect-Provider or no... just give the admin the possibility to allow ONE, the own one, OpenID-Connect-Provider, to create groups and usernames without prefix.

But i see. You are not willing to do this. 

Thank you for nothing.

**Comment by mohsensaeedi** [comment]
This is required for us too. Everyone with LDAP and self hosted nextcloud need to have users without any prefix. This feature is implemented on SAML2 plugin. I think it is better to have option to create users without prefix, if user is not exist. It prevents to accidentally create admin user for example. 

For this missing feature, i'm force to switch SAML2 plugin.

Thanks

**Comment by Keyinator** [comment]
While I appreciate the concern here, the option to remove the prefix would only be changeable by an admin itself so I don't see any security risks.
Another thing to note is that some don't use it for discord, gitlab, etc. but just for an internal auth-provider (like authentik) and have full control over the shared usernames.

**Comment by dleonarski** [comment]
Being aware that this may not be the most elegant solution, I suggest you consider the following trick inside the custom_apps/user_saml/lib/SAMLSettings.php (around the line #80):
// public const DEFAULT_GROUP_PREFIX = 'SAML_';
   public const DEFAULT_GROUP_PREFIX = '';

After that SAML's 'admin' group becomes NC's built in 'admin' group :-)
