### ISSUE TITLE
Get generated token for nextcloud from keyclock login(SSO)

### ISSUE THREAD

**Issue by moeindev** [zorn-v/nextcloud-social-login#373]
Hi,

From what I understand, social login generates a token based on the authentication tokens of other authentication services. I need to get the generated token to work with NextcloudAPIs. I would really appreciate any suggestions you may have for my situation: 

The keyclock service is already bound to my social login settings and after the user logs in, it redirects them to my local Nextcloud server.

My scenario is that I already have a keyclock token and I want to generate the token programmatically so I can use it within my code).

My first look at the codes did not yield any useful results.

The last thing I want to know is whether this is the right solution for my situation here?

**Comment by zorn-v** [comment]
I did not catch actually what you need. Can you describe your flow like
1. I need some info
2. I do request with token etc.
I suggest you can do it not in optimal way.
