### ISSUE TITLE
Login screen not working in Nextcloud 25 if "Hide standard login" is activated

### ISSUE THREAD

**Issue by mkrecek234** [zorn-v/nextcloud-social-login#375]
Steps to reproduce:
- Install or update to Nextcloud 25

If you have "hide standard login" option enabled for the social login app, then a blank screen appears on login and no way to login in any way. If you deactivate it, social login working.

 
![image](https://user-images.githubusercontent.com/28671486/196660906-ce1d277f-ca73-41e5-a647-d019599097de.png)

**Comment by zorn-v** [comment]
Fixed in v4.18.0
