### ISSUE TITLE
Gitlab return 'The redirect URI included is not valid.'

### ISSUE THREAD

**Issue by SofianeLasri** [zorn-v/nextcloud-social-login#377]
Hello, I followed your tutorial to connect nextcloud with a gitlab account but, unfortunately, I didn't manage to make it works.
I have this error when I click on the login button 'The redirect URI included is not valid.'. I have my own gitlab configured, here is my callback url: https://cloud.sl-projects.com/apps/sociallogin/custom_oidc/gitlab

If I put a slash at the end, it redirects me directly throught the login page. But I don't touch the url I get the error message.
I didn't find help anywhere else, how can I fix that? :/

Thx in advance for help!

**Comment by zorn-v** [comment]
Check hint about callbackreply url https://github.com/zorn-v/nextcloud-social-login#about-callbackreply-url
Did you try `'overwriteprotocol' => 'https'` ?

**Comment by SofianeLasri** [comment]
Thx for your fast answer! Yes I already put that into the Nextcloud config file. It doesn't to change anything for me. :/

**Comment by zorn-v** [comment]
Then check url (in browser) on that page which say "The redirect URI included is not valid."
There is query parameter with redirect url - compare it carefully with actual redirect url in you gitlab settings.
Possibly NC wrong detect host - then use `overwritehost`. Or maybe it generate url with `index.php` in it - then just add another url to gitlab (or try to use `htaccess.RewriteBase`)

**Comment by SofianeLasri** [comment]
Thanks a lot for your help!
The problem was that Nextcloud added 'index.php' after the hostname. So Gitlab didn't received the correct URL, even if the both redirect to the same page. I change the callback url by the one sended by Nextcloud and it worked. 👍
