### ISSUE TITLE
What features do I need to apply to use facebook?

### ISSUE THREAD

**Issue by chiyi4488** [zorn-v/nextcloud-social-login#38]
What features do I need to apply to use facebook?
USER_LINK ?

Thank You!

**Comment by zorn-v** [comment]
Unclear question.
Basically you need to create app at https://developers.facebook.com/ with correct settings, and provide `client id` and `secret` in plugin settings page.

**Comment by chiyi4488** [comment]
Sorry, this I know. I mean: Facebook has a lot of services(API) that can be applied for.Like user_link,So what services(API) should I apply for to fully support social login?

**Comment by zorn-v** [comment]
It is very clear how to do "login with facebook".
Just dont look at official docs.They just offer their fucking javascript framework (react I think).

**Comment by chiyi4488** [comment]
Ok, thank you.
