### ISSUE TITLE
error sso google

### ISSUE THREAD

**Issue by Josuate** [zorn-v/nextcloud-social-login#384]
hello i need help with problem 

Access blocked: This app’s request is invalid
You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

I followed this procedure

https://github.com/zorn-v/nextcloud-social-login/blob/master/docs/sso/google.md

**Comment by PTxmAwdROA** [comment]
Hi - were you able to resolve this?  I am having the same problem

**Comment by zorn-v** [comment]
`redirect_uri_mismatch` is EXACTLY what it says.
Compare `redirect_uri` in browser address bar and in google oauth app settings.

**Comment by zorn-v** [comment]
Your url may be like `https://--MY-DOMAIN--/index.php/apps` (depends on server config).
Check url in "Login with google" button.

README.md
> You can copy link of certain login button to get proper "redirect url" for OAuth app setting.
