### ISSUE TITLE
discord gives a 403 error

### ISSUE THREAD

**Issue by Fma965** [zorn-v/nextcloud-social-login#39]
https://domain/index.php/apps/sociallogin/oauth/discord?state=[state]&code=[code]

**Comment by zorn-v** [comment]
Need more info

**Comment by Fma965** [comment]
you can't just say "need more info" and not tell me what info you need...

**Comment by vlldk** [comment]
Well, you could start by saying what your problem/question/feature request is lol - a URL is useless without context

**Comment by Fma965** [comment]
The subject of the issue says the problem

discord gives a 403 error

**Comment by zorn-v** [comment]
> and not tell me what info you need...
The more the better.
How you configure app on discord ? How you configure sociallogin app ? On what step it happens ? What mean your url at least ?

**Comment by Fma965** [comment]
exactly as described, it's not hard to put a app id and a secret in... i then set the url to the url of the login link which is https://domain/index.php/apps/sociallogin/oauth/discord it works fine for github and others but not discord.

**Comment by zorn-v** [comment]
>it's not hard to put a app id and a secret in

Sometimes you just copy additional space for secret for example (as I has trouble with google). Try to copy credentials to text file and paste form it without additional chars

**Comment by zorn-v** [comment]
> after accepting the discord permissions either by linking a existing account or creating a new one from the login screen

Did not catch, on which step you have a problem. You see DISCORD 403 or NEXTCLOUD 403 ?
If nexctcloud, it would be nice to see last entries of nextcloudd.log after try.

**Comment by Fma965** [comment]
it's nginx error 403

**Comment by zorn-v** [comment]
I mean who gives it ? Discord server or your own ?
What url in browser address bar when you see that error ? Can you give screenshot ?

**Comment by Fma965** [comment]
my nginx server, the url is what was in the original post. i'm not posting my domain

**Comment by zorn-v** [comment]
Your server is configured wrong. That's all I can say with that info. Check nginx logs.

**Comment by Fma965** [comment]
well i know how to configure my server thanks. other providers work fine so it's clearly something relating to discord or your implementation and not "my server", facebook, github etc all work fine.

**Comment by zorn-v** [comment]
Well I know how to write programs thanks. And all works fine on my server and no one other say about problem with discord. 
You even did not look at logs, right ? And so sure in your rightness ?

**Comment by Fma965** [comment]
my logs don't show anything other than 403 error, i just wont use your "app". it was obvious from your attitude that you was going to say its my end.

**Comment by zorn-v** [comment]
> anything other than 403 error

And no other text like "due configuration restriction" or so ?

>  i just wont use your "app"

I will cry tonight

> it was obvious from your attitude

It is obvious that you are infallible and never mistake. And seems nginx guru. 
And also don't want JUST CHECK that you are wrong... 
You just did not want solve problem but want to show how "smart" you are. Good luck

**Comment by Fma965** [comment]
> I will cry tonight
this right here just shows how immature you are. 

> It is obvious that you are infallible and never mistake. And seems nginx "guru".
> And also don't want JUST CHECK that you are wrong...
> You just did not want solve problem but want to show how "smart" you are. Good luck
No i've made many mistakes, the fact is i can't share my domain info with you due to the nature of it. the site is also geoblocked outside of my home country so you wouldn't be able to access it via url anyway.
I have "JUST CHECK" there is nothing obviously wrong my end,
I do want to solve the problem but it's obviously you aren't going to help so i will figure it out on my own or just not use your software. my nextcloud isn't used enough for me to put loads of time in to confirm/deny my nginx config is the issue, which btw is using the LinuxServer nextcloud Docker so isn't actually configured by me. i do have it reverse proxied via nginx with letsencrypt but i guess i don't know what i'm on about so i can't possibly of set that up. my point is that the other oauths work fine, i presume discord uses oauth aswell? in which case why would it be just discord that doesn't work, if it was really a issue with my config/server wouldn't it affect all.

**Comment by Fma965** [comment]
I'm really not sure how i am "not willing to help me discover" since i've already checked the logs etc nothing stands out as being the issue. not really sure what else i can do,  i have no other server to hand to test it on, the server is headless and remote so launching localhost won't help without forwarding ports.

**Comment by Fma965** [comment]
and no the geoblock isn't the problem, why would it be? discord ip's don't connect to my server thats not how oauth works.

**Comment by zorn-v** [comment]
> so launching localhost

You can launch `php -S 0.0.0.0:8888` and open `http://server_ip:8888` Dont forget add new redirect_uri to discord oauth app.

> discord ip's don't connect to my server

But what about `Referer` http header ?

**Comment by Fma965** [comment]
Yes no problem i will try it after work. (i will still need to forward ports though as the server is behind pfsense)

The geoblock is purely IP so no that won't be the issue but thanks for the help.
