### ISSUE TITLE
Is there a manual on how-to use this plugin with discourse? 

### ISSUE THREAD

**Issue by albjeremias** [zorn-v/nextcloud-social-login#399]
I'd like to known how to setup this plugin with discourse 3.1.X

There are many options on discourse side and on nextcloud.

This are the definitions you can setup in discourse:
![image](https://user-images.githubusercontent.com/26681446/224567180-7d8ef29b-4ec7-4e0f-9a32-c0d38504c30a.png)
![image](https://user-images.githubusercontent.com/26681446/224567190-d0a8a695-9087-49dd-9e81-267e237d9f1f.png)

options on nextcloud:
![image](https://user-images.githubusercontent.com/26681446/224567329-c6729dc9-28b9-4de5-a9e8-a496d0487c25.png)

thank you.

**Comment by paroga** [comment]
the name in discourse changed from "sso secret" to "discourse connect secret", but it's still the same

* in discourse
  * create a random string for the discourse connect secret (see discourse documentation for details)
  * enable the discourse connect provider
* in nextcloud
  *  Base URL = your discourse instance (e.g., `https://meta.discourse.org`)
  * SSO secret = the same random string as in discourse connect secret

see also the [thread on meta](https://meta.discourse.org/t/_/59430)

**Comment by albjeremias** [comment]
sorry but im still confused. if you see my screenshots the settings in discourse are all very similar and confusing. from my screenshots there are 2 different places .

So after setting up as you said i got this error, when i click "Login in with ...."
![image](https://user-images.githubusercontent.com/26681446/224743707-102165d1-8df2-4163-9ed0-e619be0d7b91.png)


The settings i setup in discourse are looking like this:
![image](https://user-images.githubusercontent.com/26681446/224744022-33d7c57d-065b-4b78-9334-de638e7aec26.png)

**Comment by albjeremias** [comment]
:crying_cat_face:
