### ISSUE TITLE
invalid oauth2 redirect_uri on Discord

### ISSUE THREAD

**Issue by touhoku-japan** [zorn-v/nextcloud-social-login#404]
Discord login gives error "invalid oauth2 redirect_uri"

1. https://nextcloud.example.com/index.php/apps/sociallogin/oauth/discord configuration is ok
2. CLIENT ID and CLIENT SECRET settings are OK.

But for some reason I get the above error.

How can i solve it?

Should I look at some logs? where is the log?

**Comment by zorn-v** [comment]
You can check browser address bar for something like `redirect_url=YOUR_URL` and compare it with those in discord oauth app settings.

**Comment by touhoku-japan** [comment]
it's unfortunate news, but there was nothing wrong with it. was the same.

**Comment by touhoku-japan** [comment]
Is it wrong to use cloudflare proxy?

**Comment by touhoku-japan** [comment]
It was all my fault. I'm sorry. redirect_url was slightly wrong.
thanks to reply.
