### ISSUE TITLE
Dropbox login possible?

### ISSUE THREAD

**Issue by 3D-Schorsch** [zorn-v/nextcloud-social-login#406]
How can I use Dropbox as a login for Nextcloud? 
What do I need to set so that I can use it? 

Does anyone have any idea?

@zorn-v

**Comment by zorn-v** [comment]
Yes, it is possible. Just add it via pull request )

**Comment by 3D-Schorsch** [comment]
Thanks @zorn-v for your answer.
What does the request look like? 
Can you give me an example? 
And in which item in the configuration menu (OpenID-Connect, OpenID, OAuth1, OAuth2, Discourse) do I need to add it? 
I haven't done something like that yet.
