### ISSUE TITLE
Cant login with OIDC Anymore

### ISSUE THREAD

**Issue by acul009** [zorn-v/nextcloud-social-login#407]
Hi,
I just got an error and can't login into my nextcloud with OIDC anymore.

Log Message:
`
[index] Error: Exception: sha1(): Argument #1 ($string) must be of type string, null given in file '/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php' line 116 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\SocialLog ... "], "custom")
1. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\SocialLogi ... r", "custom", ["OC\\AppFramewo ... "], ["custom_oidc"," ... "])
2. /var/www/html/lib/base.php line 1055
   OC\Route\Router->match("/apps/sociallogin/custom_oidc/authentik")
3. /var/www/html/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: sha1(): Argument #1 ($string) must be of type string, null given at <<closure>>

 0. /var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php line 116
    sha1("*** sensitive parameters replaced ***")
 1. /var/www/html/lib/private/Authentication/Token/Manager.php line 69
    OC\Authentication\Token\PublicKeyTokenProvider->generateToken("*** sensitive parameters replaced ***")
 2. /var/www/html/lib/private/User/Session.php line 686
    OC\Authentication\Token\Manager->generateToken("*** sensitive parameters replaced ***")
 3. /var/www/html/custom_apps/sociallogin/lib/Service/ProviderService.php line 569
    OC\User\Session->createSessionToken("*** sensitive parameters replaced ***")
 4. /var/www/html/custom_apps/sociallogin/lib/Service/ProviderService.php line 433
    OCA\SocialLogin\Service\ProviderService->login("*** sensitive parameters replaced ***")
 5. /var/www/html/custom_apps/sociallogin/lib/Service/ProviderService.php line 293
    OCA\SocialLogin\Service\ProviderService->auth("OCA\\SocialLogi ... t", ["https://next.c ... "], "authentik")
 6. /var/www/html/custom_apps/sociallogin/lib/Controller/LoginController.php line 41
    OCA\SocialLogin\Service\ProviderService->handleCustom("custom_oidc", "authentik")
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\SocialLogin\Controller\LoginController->custom("custom_oidc", "authentik")
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\SocialLog ... "], "custom")
 9. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\SocialLog ... "], "custom")
10. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\SocialLogi ... r", "custom", ["OC\\AppFramewo ... "], ["custom_oidc"," ... "])
11. /var/www/html/lib/base.php line 1055
    OC\Route\Router->match("/apps/sociallogin/custom_oidc/authentik")
12. /var/www/html/index.php line 36
    OC::handleRequest()

GET /apps/sociallogin/custom_oidc/authentik
from xxx.xxx.xxx.xxx at 2023-04-17T12:28:04+00:00
`

**Comment by zorn-v** [comment]
Just wait nextcloud update
https://github.com/zorn-v/nextcloud-social-login/issues/401
