### ISSUE TITLE
OAuth2 correct redirect url

### ISSUE THREAD

**Issue by foscone** [zorn-v/nextcloud-social-login#41]
Hi,
I can not figure out which url should be entered as redirect address in the OAuth server configuration.
I tried with:
[nextcloud_url]/index.php/apps/sociallogin/custom_oauth2/[internal_name]
[nextcloud_url]/index.php/apps/sociallogin/oauth2/[internal_name]
[nextcloud_url]/index.php/apps/sociallogin/oauth/[internal_name]
but every time I had an error.
What is the correct url?
Thanks

**Comment by foscone** [comment]
The error I have is
`Signed API request has returned an error. HTTP error 401. Raw Provider API response: {}.`
![errore nextcloud stede](https://user-images.githubusercontent.com/29599997/42526864-60d2d368-8477-11e8-8a7b-3dfc8c942748.JPG)
I have two different servers both with one instance of wordpress and one of nextcloud. Server1 works fine with oauth autentication, server2 not.
If I try to request authentication from server1's nextcloud to server2's wordpress it works, the opposite (from nextcloud2 to wordpress1) does not work.

**Comment by zorn-v** [comment]
You can get redirect url from login button of certain provider on nexcloud login page (just "Copy link" from context menu) as mentioned in readme.
Seems you did not (or wrong) configured "server1" as oauth server. 401 mean "Unauthorized" in http.

**Comment by foscone** [comment]
I think the problem is in server2's nextcloud because, by testing with a different nextcloud, it seems that server1's wordpress as oauth server works.
