### ISSUE TITLE
Make contributing easier

### ISSUE THREAD

**Issue by pktiuk** [zorn-v/nextcloud-social-login#412]
I think entry barrier for contributions on this repo could be lower.

I think some docs telling how to install or edit code in your app would be very handy.

For small contributions enabling [GitHub codespaces](https://docs.github.com/en/codespaces) would also make contribution entry barrier much lower. For this purpose you could just copy config from other Nextcloud apps like [Deck](https://github.com/nextcloud/deck)

![image](https://github.com/zorn-v/nextcloud-social-login/assets/45544416/a60e4dcf-c5fb-46d6-814b-984e89aa9c5f)

What do you think about this idea?

**Comment by zorn-v** [comment]
What do you want ?

**Comment by pktiuk** [comment]
`some docs telling how to install or edit code in your app would be very handy`

**Comment by zorn-v** [comment]
Just open text editor and edit :smile: 
For frontend you can check `package.json` for scripts (e.g. `npm run watch` for recompile while change files).
All "standards" from php and js worlds.

**Comment by pktiuk** [comment]
And how to install the app to be sure, that nextcloud will see it?

How to see logs?

**Comment by zorn-v** [comment]
> And how to install the app to be sure, that nextcloud will see it?

Like any other nextcloud app, just put it in `apps` dir.
For example
```bash
cd /path/to/nextcloud/apps
git clone https://github.com/zorn-v/nextcloud-social-login.git sociallogin
```

> How to see logs?

There is no extra logs

**Comment by pktiuk** [comment]
Okay, if you find all of these facts obvious, then there is no need to add any contribution info.

But I think you shouldn't assume that everyone who wants to contribute to your app must be an experienced NC plugins developer.
