### ISSUE TITLE
Issues with custom OAuth2

### ISSUE THREAD

**Issue by ReneHezser** [zorn-v/nextcloud-social-login#42]
Hi,
I want to connect to Azure Active Directory with the OAuth2 provider. An application with necessary redirect_url... has been created.
When I try to log in, I get the error
`Unable to exchange code for API access token. HTTP error 400. Raw Provider API response: {"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: 1ae94aaf-e1d9-4678-9892-3b5bcd091d00\r\nCorrelation ID: 9f2c1f67-2961-490f-a330-13399888fdb5\r\nTimestamp: 2018-07-22 20:31:10Z","error_codes":[90014],"timestamp":"2018-07-22 20:31:10Z","trace_id":"1ae94aaf-e1d9-4678-9892-3b5bcd091d00","correlation_id":"9f2c1f67-2961-490f-a330-13399888fdb5"}.`

![custom_oauth2](https://user-images.githubusercontent.com/5988767/43087610-8c51d132-8ea0-11e8-9ac0-ed2e79b53bfd.PNG)

From my understanding the grant_type should be passed within the body as POST parameter.
Did anybody successfully connect via OAuth2 to an AAD?

**Comment by zorn-v** [comment]
Try to use OpenID Connect
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code

**Comment by ReneHezser** [comment]
I tried OpenID Connect before OAuth2. Same problem :-(

**Comment by zorn-v** [comment]
Seems AAD use not standard `grant_type` field. Maybe instead of `scope`

**Comment by ReneHezser** [comment]
Scope needs to be "openid". https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oidc

**Comment by zorn-v** [comment]
Problem solved ?

**Comment by ReneHezser** [comment]
No. I think the problem lies in the 3rd party library you are using, because there is an [open issue](https://github.com/hybridauth/hybridauth/issues/548).

**Comment by zorn-v** [comment]
It is no so problem as microsoft seems used not standard fields. Microsoft can afford it 😄 
Just remember Internet Explorer (if you deal with web develop you will understand what I'm saying)

**Comment by zorn-v** [comment]
I could do "azure provider" for hybridauth I think. But I has not account on it for testing.

**Comment by ReneHezser** [comment]
That would be awesome. I am creating an AAD and will provide you with necessary data via email.

**Comment by zorn-v** [comment]
Ok, but not earlier than next week

**Comment by exparamu** [comment]
Hello,
I'm trying to configure OAuth 2.0 for LinkedIn.

![image](https://user-images.githubusercontent.com/19313027/43688328-e1abfa54-98e6-11e8-9b53-4a737f4d16c6.png)

I have been quite successful in establishing the connection but then I get an INTERNAL SERVER ERROR.

This is the log I get:

Error: Cannot use object of type stdClass as array
/var/www/html/businesscloud/apps/sociallogin/lib/Controller/LoginController.php - line 214: OCA\SocialLogin\Provider\CustomOAuth2->getUserProfile()
/var/www/html/businesscloud/apps/sociallogin/lib/Controller/LoginController.php - line 200: OCA\SocialLogin\Controller\LoginController->auth('OCA\\SocialLogin...', Array, 'linkedin', 'Custom OAuth2')
[internal function] OCA\SocialLogin\Controller\LoginController->customOauth2('linkedin')
/var/www/html/businesscloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/var/www/html/businesscloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SocialLogin\Controller\LoginController), 'customOauth2')
/var/www/html/businesscloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SocialLogin\Controller\LoginController), 'customOauth2')
/var/www/html/businesscloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\SocialLogin...', 'customOauth2', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/businesscloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/businesscloud/lib/base.php - line 999: OC\Route\Router->match('/apps/sociallog...')
/var/www/html/businesscloud/index.php - line 42: OC handleRequest()
{main}

Any advise?

Thanks and regards,
Enrico

**Comment by exparamu** [comment]
I installed v1.9.4 but I still can't have it working for LinkedIn: "Provider API returned an unexpected response".
But I don't have errors in the log anymore.

**Comment by zorn-v** [comment]
You can check params for LinkedIn in https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Provider/LinkedIn.php
Try to set scope to `r_basicprofile r_emailaddress`
I cannot test it coz LinkedIn blocked in russia.

**Comment by exparamu** [comment]
Is there a way to see the detailed log of the app?
I would like to see what's behind the generic error "Provider API returned an unexpected response".
Many thanks!

**Comment by zorn-v** [comment]
I knew, that custom oauth gives me troubles ) It's not my implementation at all. https://github.com/zorn-v/nextcloud-social-login/pull/37
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOAuth2.php#L40

**Comment by zorn-v** [comment]
https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Provider/LinkedIn.php#L76
Id field should be there in response. So everything should work... May be find some time o test via tor...

**Comment by exparamu** [comment]
Thanks, I appreciate.
I reviewed the code, but still no success on my side.

**Comment by IInvocation** [comment]
Hi,
as i've encountered a similar problem today using IdentityServer4 as an provider - i'd like to point out that the required "identifier"-Claim should also be able to be adressed as "sub" from the default implementation. (Had to change the CustomOAuth2.php a little)

I don't know if "identifier" is right or "sub" - but since IdentityServer4 is a certified implementation - i'd have expected it to accept "sub".

**Comment by zorn-v** [comment]
"sub" is for OpenIDConnect

**Comment by zorn-v** [comment]
More and more confidence to remove custom oauth....

**Comment by ceelsoin** [comment]
In LoginController.php on sociallogin plugin you can see that there is this return message, solve my problem by adding a condition if you understand that my authenticator does not use the outh response ID, I could verify this using https://oauthdebugger.com and then validation code for more of an identity server that uses the username

**Comment by TobjasR** [comment]
I can link my LinkedIn profile with my Nextcloud account and use the social login all fine, but when registering (a new user account) via social login with LinkedIn, it fails to retrieve the e-mail address although scope is properly set to "r_emailaddress r_liteprofile". Anybody any idea what could be wrong?
![Screenshot](https://user-images.githubusercontent.com/37045496/119569968-c5c6d200-bdaf-11eb-806c-60b063e053a3.png)

**Comment by TobjasR** [comment]
> Anybody any idea what could be wrong? 
push
