### ISSUE TITLE
Website Ownership Verification

### ISSUE THREAD

**Issue by kotovasia5120** [zorn-v/nextcloud-social-login#426]
Google says you need to add an html tag to your website code. I don't understand where to add it.
`<meta name="google-site-verification" content="------------------------------------------------" />`
[google insruction](https://support.google.com/webmasters/answer/9008080#meta_tag_verification&zippy=%2Chtml-tag)
Other verification methods do not suit me.

**Comment by zorn-v** [comment]
What are you talking about ?

**Comment by GTP95** [comment]
It doesn't seem to be the case anymore: I just tried adding my domain to Google Search Console, and right after providing the domain it asks for verification. I didn't see a way to skip it. Am I missing something?
