### ISSUE TITLE
Invision Community - Error: Provider API returned an unexpected response.

### ISSUE THREAD

**Issue by gamekeeper** [zorn-v/nextcloud-social-login#43]
I'm trying to setup a custom OAuth2 with Invision Community v4.3.5 as an identity provider. But I'm stuck at "Error  Provider API returned an unexpected response." with no further feedback. How do I fix this?

Invision Community v4.3.5
![nextcloud 3](https://user-images.githubusercontent.com/41835780/43358151-91732b52-928d-11e8-99c5-c300f24bd6d7.png)
![nextcloud 2](https://user-images.githubusercontent.com/41835780/43358150-915729ca-928d-11e8-8578-b6149203e375.png)
*redirection uri: https://pyroforum.nl/nextcloud/index.php/apps/sociallogin/custom_oauth2/PyroForum.nl

Nextcloud
![settings nextcloud](https://user-images.githubusercontent.com/41835780/43358153-983c48ba-928d-11e8-8b77-46644427ce00.png)

Steps
![nextcloud](https://user-images.githubusercontent.com/41835780/43358158-a2db7476-928d-11e8-9821-42b9fb577e7b.png)
![authorize sign in pyroforum nl](https://user-images.githubusercontent.com/41835780/43358156-a29e0dfc-928d-11e8-8456-3a9ba9f4e07f.png)
![authorize sign in pyroforum nl 1](https://user-images.githubusercontent.com/41835780/43358155-a27a9908-928d-11e8-8557-8ffc2873895e.png)
![nextcloud 1](https://user-images.githubusercontent.com/41835780/43358157-a2bd26ce-928d-11e8-924f-44e99ac38d50.png)

**Comment by zorn-v** [comment]
Can you show related logs ?

**Comment by zorn-v** [comment]
> I'm a bit unsure what the 'profile url' should be in Nextcloud. I entered this url:

Profile url should be a url wich return correct profile info in "oauth format" (maybe it is main problem ?)

PS. Related info means "related to you problem". `/nextcloud/cron.php` does not seems related for example... But anyway I try to figure out.

**Comment by zorn-v** [comment]
> \/PyroForum.nl?code=9b625bf0a9706f14461605fd992bc66816f2c35d89c69de72cfbd4b8d7cb3ee0&state=HA-0ELXJSOG4NYIVWQA7FTPKRM5B3H29U1Z68DC","message":"Failed to connect to the database: Unsupported type: "

After all I think problem in incorrect progile url. If all works fine (I think so) database creds can not be "incorrect".

**Comment by gamekeeper** [comment]
Can you confirm the redirect_uri / Callback URL is: https://pyroforum.nl/nextcloud/index.php/apps/sociallogin/custom_oauth2/PyroForum.nl
That is the url under the Alternative Login button:
![nextcloud 1](https://user-images.githubusercontent.com/41835780/43368639-bc2d9c96-9360-11e8-93d0-70d2469b9114.png)
"You can copy link of certain login button to get proper "redirect url" for OAuth app setting."

If I try to test it using postman I get an invalid_client error:
![untitled2](https://user-images.githubusercontent.com/41835780/43368655-f38e62f6-9360-11e8-8a5d-e92c80b1c5a0.png)
![untitled](https://user-images.githubusercontent.com/41835780/43368657-fee7adf6-9360-11e8-9b2f-db74597c974d.png)

**Comment by gamekeeper** [comment]
The profile (https://pyroforum.nl/api/core/me) should return this with a valid oauth access token: 
https://invisioncommunity.com/developers/rest-api?endpoint=core/me/GETindex

That is sufficient or not? nextcloud-social-login has issues with this?

**Comment by gamekeeper** [comment]
In Invision Community OAuth clients Client Identifiers are 32 characters long, Client Secrets are 48 characters long, Authorization Codes are 64 characters long, and Access Tokens are 97 characters long.

**Comment by gamekeeper** [comment]
In Postman, in GET NEW ACCESS TOKEN. I changed Client Authentication to 'Send credentials in body'. 
Now i'm successfully able to pull user data from https://pyroforum.nl/api/core/me as specified in https://invisioncommunity.com/developers/rest-api?endpoint=core/me/GETindex

**Comment by zorn-v** [comment]
`identifier` is mandatory field in provider response. Must be unique for that provider.
Try to play with OpenID Connect (maybe with some plugin for Invision Community).
`OpenID Connect`  != `OpenID`
First one like extension for oauth

**Comment by zorn-v** [comment]
Or you can try v1.9.3 where I add workaround for that field

**Comment by gamekeeper** [comment]
I did the update. But now when I try to login with the Custom Oauth2 it doesnt say just unexpected response. But I get this:

```
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: XXX.XXX.XXX.XXX
Request ID: lLCD8MkAEvTANxx5paXN
Type: Error
Code: 0
Message: Cannot use object of type stdClass as array
File: /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/apps/sociallogin/lib/Provider/CustomOAuth2.php
Line: 33

Trace
#0 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/apps/sociallogin/lib/Controller/LoginController.php(214): OCA\SocialLogin\Provider\CustomOAuth2->getUserProfile()
#1 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/apps/sociallogin/lib/Controller/LoginController.php(200): OCA\SocialLogin\Controller\LoginController->auth('OCA\\SocialLogin...', Array, 'PyroForum.nl', 'Custom OAuth2')
#2 [internal function]: OCA\SocialLogin\Controller\LoginController->customOauth2('PyroForum.nl')
#3 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)
#4 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SocialLogin\Controller\LoginController), 'customOauth2')
#5 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SocialLogin\Controller\LoginController), 'customOauth2')
#6 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\SocialLogin...', 'customOauth2', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#7 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#8 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#9 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/lib/base.php(999): OC\Route\Router->match('/apps/sociallog...')
#10 /home/vhosting/b/vhost0054698/domains/pyroforum.nl/htdocs/www/nextcloud/index.php(42): OC::handleRequest()
#11 {main}
```

**Comment by zorn-v** [comment]
No standard responce, sorry.

**Comment by zorn-v** [comment]
I don't want to provide some "custom" things beacase of this.

**Comment by gamekeeper** [comment]
It works now! Thanks.

**Comment by naiaokami** [comment]
> It works now! Thanks.

how did you get it to work? also an IPS user

**Comment by krisnantobi** [comment]
> It works now! Thanks.

how did you get it to work?
