### ISSUE TITLE
Google Sign In Not Working

### ISSUE THREAD

**Issue by Daniel-dev22** [zorn-v/nextcloud-social-login#435]
In my experience using Google OAUTH I get a prompt to select the account I want to use.

With Social Login I am getting this prompt which is to select an account to manage? It doesn't do anything but take me to the manage accounts screen which isn't what it should be doing.

![Screenshot_20231102_063414_Chrome.jpg](https://github.com/zorn-v/nextcloud-social-login/assets/47092714/d2fc3418-e3a9-473b-aee6-aa34249e4352)

**Comment by zorn-v** [comment]
Not working for you
