### ISSUE TITLE
Can't configure Social Login

### ISSUE THREAD

**Issue by GTP95** [zorn-v/nextcloud-social-login#436]
Greetings,

After following the instructions to get the client ID and secret for OAuth via Google, I opened the "Social Login" section under my administrator settings. This is what I got: 
![social login settings](https://github.com/zorn-v/nextcloud-social-login/assets/9197945/72c5fa99-3f34-481f-941e-59270b5f7b45)
I see no "Google" section to input the required values, contrary to what stated in the instructions [here](https://github.com/zorn-v/nextcloud-social-login/blob/master/docs/sso/google.md). What shoud I do to be able to complete Social login's configuration?
Than k you for your help,

GTP

**Comment by zorn-v** [comment]
It is "user section". There is admin section below
![изображение](https://github.com/zorn-v/nextcloud-social-login/assets/12619075/2343f0dd-e913-44d5-9e06-234cd3516e1a)

**Comment by GTP95** [comment]
Found it, thank you.
