### ISSUE TITLE
email not getting mapped OIDC

### ISSUE THREAD

**Issue by tfmm** [zorn-v/nextcloud-social-login#443]
Just set this plugin up, and after associating Social accounts with existing users, the email address for the users is being wiped out from the settings. 

Here's my settings: 
```
Custom OpenID Connect 
Internal name
zitadel

Title
SSO

Authorize url
https://sso.domain.com/oauth/v2/authorize

Token url
https://sso.domain.com/oauth/v2/token

Display name claim (optional)
preferred_username

User info URL (optional)
https://sso.domain.com/oidc/v1/userinfo

Logout URL (optional)

Client Id
redacted

Client Secret
redacted

Scope
openid profile

Groups claim (optional)

Button style
OpenID

Default group
None

Add group mapping
```

Any advice on how to resolve this?

**Comment by zorn-v** [comment]
You can disable "Update user profile every login"

**Comment by tfmm** [comment]
I should have been more clear, my apologies.  When a user is logging in, their email is getting set to a null value. Is there a way to set it to the provided email that is coming from the OIDC provider?

**Comment by zorn-v** [comment]
If it provided by non standard email field, then no by now.
