### ISSUE TITLE
Use NextCloud API with Keycloak token

### ISSUE THREAD

**Issue by romain-akvize** [zorn-v/nextcloud-social-login#444]
Hello,

I would like to call Nextcloud APIs to browse user files like calling GET https://cloud.domain/ocs/v2.php/search/providers/files/search?term=cat (cf https://docs.nextcloud.com/server/20/developer_manual/digging_deeper/search.html ).

The user is authenticated in another app with Keycloak. How can I convert a Keycloak JWT token to a valid session on the Nextcloud API please ?

From what I see in the documentation, the Nextcloud API is waitig for a basic auth (login:password) but it’s not possible with a Keycloak user :( .

**Comment by zorn-v** [comment]
Sorry, not now. It is not "auth" plugin, but just "I just want to login via social"
