### ISSUE TITLE
BUG: Problem with `useGuildNames` for Discord

### ISSUE THREAD

**Issue by pktiuk** [zorn-v/nextcloud-social-login#446]
After update: https://github.com/zorn-v/nextcloud-social-login/pull/437

I saw error in logs:

`Undefined array key "useGuildNames" at /var/www/html/custom_apps/sociallogin/lib/Service/ProviderService.php#426`    

---------------

Moreover, changing this value in settings (`Use guild nicks`) does not seem to work.

After pressing Save (and seeing `Settings for social login successfully saved`) and reloading website I still see empyty checkbox.

![image](https://github.com/zorn-v/nextcloud-social-login/assets/45544416/b11b7f4f-9853-4280-91a0-c4645eae836e)
This problem should be fixed by https://github.com/zorn-v/nextcloud-social-login/pull/447

**Comment by zorn-v** [comment]
Fixed in https://github.com/zorn-v/nextcloud-social-login/commit/0013a5c8efb538fa6b06eba30fbfd5031b39dbf9
