### ISSUE TITLE
OpenID issues / request

### ISSUE THREAD

**Issue by petrk94** [zorn-v/nextcloud-social-login#45]
Hello,
thank you for providing a app for nextcloud to allow to login with openid.
I tried it now successfully with selfhosted simpleid v1. This work really well.
Only Im facing the problem, that the account created from the openid, seems to use the "internal name" from the social login settings and the identity name. But due the identity is in the settings made as URL, like user.domain.com, with the internal name it looks in-user.domain.com.
This look really mess. 

First, which configuration is necessary, that the social login app get the name of the user from openid identity file?

Second, is it possible to remove the requirement, that a internal name has to be set?

Thank you for your help

Edit: maybe something like Friendica it does, after the login with OpenID, to ask for a Full name and than use this for the profile
![friendica-openid](https://user-images.githubusercontent.com/19719052/44058682-32592832-9f4f-11e8-80d3-f7c6a8bb0df0.PNG)

**Comment by petrk94** [comment]
@zorn-v yes I know, but its not very user friendly that all who use openid I have to explain, that they have to change the name in the user settings manually.
In nextcloud the uid is even not shown in the name of the user in the settings. Can this not been made under the "floor", so no one need to see it?
If not, I can still live with it.
But is it possible to get the Full name of the user, out of the OpenID identity file? Than at least they doesnt need to change the name manually and would make the flow smoother.

Thanks

**Comment by zorn-v** [comment]
username == uid if username is empty in nexcloud.
You can check what server response needed to fill `displayName` here 
https://github.com/zorn-v/nextcloud-social-login/blob/master/3rdparty/hybridauth/hybridauth/src/Adapter/OpenID.php#L222-L235

**Comment by petrk94** [comment]
@zorn-v 
Hmm, I see, unfortunately I can not PHP, so I dont understand the logic behind the code.
Ok, so the uid can not be changed.

Than whats about the name of the identity file?
Internal the uid will be used, but can you make it work, that at least the name of the identity file get used for the Full name?
So the user doesnt has to change the name by itself.

Thanks

**Comment by zorn-v** [comment]
All can I say. Provider server MUST return proper response to identify user.
I does not do adapters for ALL possible providers,

**Comment by petrk94** [comment]
Well, I can provide you the structure of the identity file, but I can not change the behavior of the OpenID provider software.

**Comment by jvinolas** [comment]
According to the OpenID standard https://openid.net/specs/openid-connect-basic-1_0.html#Scopes the profile will provide name, family_name fields and I assume that the displayname in nextcloud should be build based on this fields.

![108854732-79b99500-75e8-11eb-8e6c-e65faf12ff2e](https://user-images.githubusercontent.com/2132863/108972535-b4bcd680-7683-11eb-947d-5604b7b3c576.jpg)

At least this is how other CMS like moodle handle that.
