### ISSUE TITLE
social login registration shows complex password error, but user is created

### ISSUE THREAD

**Issue by blindzero** [zorn-v/nextcloud-social-login#451]
I configured a Google Login which seems to work in general. Google is granting access and social login settings are processed.
Then, on registration an error is displayed, but the user is created as intended (in our case deactivated).
![image](https://github.com/zorn-v/nextcloud-social-login/assets/13959569/6534878c-6023-44c3-a344-0e60117d4a37)

**Comment by zorn-v** [comment]
Fixed in v5.6.3
