### ISSUE TITLE
automatically link social account via email

### ISSUE THREAD

**Issue by blindzero** [zorn-v/nextcloud-social-login#452]
If users have not manually linked a social account in their profile, they are not able to use the social login.
It would be great if social login would

1. check existing social links
2. if no social link exists - but email is the same for account --> create link
3. if no email exists --> create user (if allowed by setting)

**Comment by zorn-v** [comment]
No. Some services has no email confirmation.

**Comment by Arusekk** [comment]
I also had the same idea, and posted about it in https://github.com/zorn-v/nextcloud-social-login/issues/121#issuecomment-2787836375

If some services have no email confirmation, would it be possible to do this optionally, like one of the other admin checkboxes (e.g. account auto-creation)? I think this is a reasonable feature to expect, as many online services do link external identities based on email. Anyway, thanks for all the hard work, this plugin works excellent for me.

(I just think it would be even better with the possibility of auto-linking identities by email.)
