### ISSUE TITLE
What's the use of Profile Fields (optional, comma-separated)?

### ISSUE THREAD

**Issue by TimoReusch** [zorn-v/nextcloud-social-login#454]
I'm a bit confused with the profile fields option when integrating an own OAuth provider. From my understanding, this option should map fields to one-another (e.g. `nextcloud_email <-> fancy_name_for_user_mail`). However, this does not seem to be the case. 

Is there any documentation available or can someone explain?

**Comment by zorn-v** [comment]
No, it does not mapping, just "show me that fields". Seems some provider respects this parameter (it is not my code).

**Comment by TimoReusch** [comment]
Ah, I see, so its for filtering the information returned by the OAuth Providers /me-Endpoint for certain fields.

I'd suggest adding a little "?" behind the description with a popup for explanation.

**Comment by zorn-v** [comment]
> I'd suggest adding a little "?" behind the description with a popup for explanation.

Just for you ? :smile: 
It is not hard, but... "any complication needs support"
