### ISSUE TITLE
Auto Connect Accounts with Oauth

### ISSUE THREAD

**Issue by yousefmansy1** [zorn-v/nextcloud-social-login#455]
I see there are settings to disable user creation when they have the same email which makes sense.

Would it be possible to auto connect the nextcloud on oauth login?

For example:
1. user is already registered with user@gmail.com
2. that user attempts to login with oauth
3. login is successful (or asks for password) and nextcloud is successfully connected

This is more useful than the current flow where step 3 would throw an error if user creation is disabled - or if it is enabled it would create a user with the same email but isnt the same user as user@gmail.com.

**Comment by zorn-v** [comment]
Once again, no.

**Comment by yousefmansy1** [comment]
Hey thanks for the response
I may have missed where this was asked before.

Just tried looking at the backlog and couldn't find it.
Was there a prior discussion on this issue?

**Comment by zorn-v** [comment]
If you REALLY need it you can fork and support :smile:

**Comment by yousefmansy1** [comment]
Ah ok I see, that does make sense.

In my head I was mainly thinking about the Google oauth.
Which you could say is pretty trustworthy.

But for the general case you're correct.
