### ISSUE TITLE
Cannot Authenticate with Discord.

### ISSUE THREAD

**Issue by TMTCo** [zorn-v/nextcloud-social-login#457]
I have no clue what is happening, 
![1](https://github.com/zorn-v/nextcloud-social-login/assets/149132955/583f986b-1c13-4dad-b9e8-4a39ddb4c0b4)
![2](https://github.com/zorn-v/nextcloud-social-login/assets/149132955/308dc551-84a7-4dc5-aa11-0aceda951ffa)
You can see what I am experiencing in thoes two images, but when I paste the link that social login page gives my from the doccumentaion it redirects to my discord server like what will happen if i was to do [https://themrtechguy.com/dsc](url)

If anyone can find out what the issue is please feel free to reply or email me at admin@themrtechguy.com

**Comment by chuushi** [comment]
somewhere in your redirect URI seems to contain a local IP address 192.168.8.187
