### ISSUE TITLE
How to set up to login using WeChat.

### ISSUE THREAD

**Issue by ywtoly** [zorn-v/nextcloud-social-login#459]
Nextcloud local login/3rd party/hybrid/hybrid/src/Provider
/WeChat.php

**Comment by zorn-v** [comment]
You need to add 'WeChat' to DEFAULT_PROVIDERS here https://github.com/zorn-v/nextcloud-social-login/blob/1ff9b80ce092d8513e0f2eaa526343ad0cbdc562/lib/Service/ProviderService.php#L46
Also need icons and styles for login buttons and settings.
Check `img` dir and `src/styles.scss` for examples
