### ISSUE TITLE
[Feature] Username of OAuth login

### ISSUE THREAD

**Issue by linnil1** [zorn-v/nextcloud-social-login#46]
Hi,
This module do a good job for OAuth2 login.

However, I don't want my username become `'internal-name' + 'id'`, which is written in 
https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Controller/LoginController.php#L222
because I start to use this module after some users  are already added in NextCloud.

My solusion is replacing `$uid = $provider.'-'.$profileId;` to this one `$uid = $profileId;`. 
Yet, can this name prefixing rule be optional?

**Comment by zorn-v** [comment]
Nope. https://github.com/zorn-v/nextcloud-social-login/issues/24
