### ISSUE TITLE
REST API login

### ISSUE THREAD

**Issue by thopico** [zorn-v/nextcloud-social-login#461]
Hello,

I need to migrate user data from another Nextcloud instance. My users are now registered in a Keycloak instance but I need to trigger user creation on Nextcloud side so that "homes" get created and I can copy data to appropriate folders.

I am wondering if there is any way to **automate social login to Nextcloud by API requests** ? I only need a user login (and logout maybe).

Thank you very much for your help

**Comment by zorn-v** [comment]
You can just POST same data as login page does if I understand you correctly.

**Comment by thopico** [comment]
Thank you for your response.
Yes I guess it is enough, but I can't manage to get it working. Could you point me out to the right requests please?

For now I try to get <nc domain name>/apps/sociallogin/custom_oidc/<oidc name> with the authorization bearer. But it seems it is not the appropriate way.

**Comment by zorn-v** [comment]
> need to trigger user creation on Nextcloud side so that "homes" get created and I can copy data to appropriate folders

Ah, I see what you need. There is no API for it. User must login on third party provider anyway. 
I even does not imagine how that "API" should looks like.
