### ISSUE TITLE
With custom OpenID authentication, Status code prompts for a“401unauthorized” error. What is the interface returned by this OIDC?

### ISSUE THREAD

**Issue by newbie-ture** [zorn-v/nextcloud-social-login#464]
With custom OpenID authentication, Status code prompts for a“401unauthorized” error. What is the interface returned by this OIDC?

**Comment by zorn-v** [comment]
What you mean by "interface" ?

**Comment by newbie-ture** [comment]
Is the address returned by the third party“Http://cloud/index.php/apps/socaillogin/custom_oidc/{ provider }”?

**Comment by newbie-ture** [comment]
> 你说"接口"是什么意思?
Is the address returned by the third party“Http://cloud/index.php/apps/socaillogin/custom_pidc/{ provider }”?
