### ISSUE TITLE
Add feature to remove a provider

### ISSUE THREAD

**Issue by aminsaedi** [zorn-v/nextcloud-social-login#465]
![image](https://github.com/zorn-v/nextcloud-social-login/assets/23167933/550482e0-4774-4aa0-9849-ab891b989d2b)

It would be nice if there is any way to remove a provider, I wanted to remove Google but seems like that there is no way to do it!

**Comment by zorn-v** [comment]
You can clear app id for this

**Comment by zorn-v** [comment]
Added in v5.6.5
