### ISSUE TITLE
oAuth doesn't work 

### ISSUE THREAD

**Issue by GreenSnail1008** [zorn-v/nextcloud-social-login#467]
Hello there

I have got message "Signed API request to http:// has returned an error. HTTP error 0. Raw Provider API response: ."
then try to use to my OAuth connection. It's set up. And I can't find any errors there.

How I can fix my problem ?

With best regards,
GS

**Comment by zorn-v** [comment]
Hello there. My PC is not working. Just not work. How can I fix it ?

**Comment by GreenSnail1008** [comment]
> Hello there. My PC is not working. Just not work. How can I fix it ?
> 
> `Signed API request to http:// has returned an error.` As you can see there is no target url where request was sended. So it sended to nowhere

Hi Zorn

If you are think it's fun then it is not.
I have found what settings was set up for oAuth1, not for oAuth2.
You can closd this issue.

शुभकामनाएँ सहित
VGS

**Comment by zorn-v** [comment]
> If you are think it's fun then it is not.

I did not meant that. `to http:// has` - there is no url, just protocol.

> You can close this issue.

You can close by yourself.

**Comment by zorn-v** [comment]
But yes, its fun when someone ask help without details.
