### ISSUE TITLE
Provider returned no access_token: &lt;!DOCTYPE html&gt; &lt;html&gt; &lt;head&gt

### ISSUE THREAD

**Issue by newbie-ture** [zorn-v/nextcloud-social-login#468]
![12313213](https://github.com/zorn-v/nextcloud-social-login/assets/170705989/bd3a6ca8-8b2d-4c4e-860a-dfcd37e1bfed)

Provider returned no access_token: &lt;!DOCTYPE html&gt; &lt;html&gt; &lt;head&gt
Prompt for this error, where should I fix the problem? Can you elaborate on the parameters and methods of the callback?

**Comment by zorn-v** [comment]
I literally does understand nothing
AI ? Close then
