### ISSUE TITLE
Can't find this way

### ISSUE THREAD

**Issue by newbie-ture** [zorn-v/nextcloud-social-login#469]
The“Auth” method in“ProviderService” could not find the method noted below 
```
 try {
            $adapter = new $class($config, null, $this->storage);
            $adapter->authenticate();  // Can't find this way
            $profile = $adapter->getUserProfile();
        }  catch (\Exception $e) {
```

**Comment by zorn-v** [comment]
Basically `$class` is subclass of `Hybridauth\Adapter\OAuth2` (located in `3rdparty/hybridauth/hybridauth/src/Adapter/OAuth2.php`)
So check there

**Comment by newbie-ture** [comment]
ok，thank you
