### ISSUE TITLE
Nextcloud 14 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [zorn-v/nextcloud-social-login#47]
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We usually try to keep up compatibility with previous app versions, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827. You can run occ app:check-code to validate that there are no issues with deprecated or private message calls.

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14.

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket: .

**Comment by zorn-v** [comment]
I think I recieve it because of

> cleanup of OC_* namespace - we removed quite some classes, methods and constants from our internal namespace. If it was used by any app in the App Store we notified the owner of that app. Keep in mind that using the OC_ namespace is not official supported and can break any time without notice. So better not use it in your app.

But there is no alternative for `\OC_App::registerLogIn` Did you forget make it in `OCP\App` ?
`registerLogIn` is main functionality of my app 😉

**Comment by zorn-v** [comment]
I know it. And don't use it. But...

**Comment by zorn-v** [comment]
Anyway, need to add check something like 
`php
if (method_exists('\OCP\App::registerLogIn '))
`
for BC and occ:check anyway will show "deprecated"

**Comment by Flore-mozfr** [comment]
Hello, I'm checking my apps compatibility with NC14. Is social login going to be compatible ? (I'm not sure by reading this). Thanks for the answer!

**Comment by zorn-v** [comment]
`\OC_App::registerLogIn` is not removed from v14 https://github.com/nextcloud/server/blob/v14.0.0/lib/private/legacy/app.php#L649 so should work.
