### ISSUE TITLE
Discord default group removed & added on every login

### ISSUE THREAD

**Issue by Claiyc** [zorn-v/nextcloud-social-login#470]
With a discord default group set, social login will remove and add that default group on every login.

![image](https://github.com/zorn-v/nextcloud-social-login/assets/58397976/0f3b0475-58ef-47a6-9d22-b731ef25035b)

While this doesn't directly affect functionality, it is a spam issue as this will generate a user notification / eventually an email:

![image](https://github.com/zorn-v/nextcloud-social-login/assets/58397976/45ba0544-77ca-4b48-9075-d898cf4cbbd5)

**Comment by zorn-v** [comment]
So it works like this https://github.com/zorn-v/nextcloud-social-login/blob/08f06c3382b555c83bfde3dfaeee385e69c80d64/lib/Service/ProviderService.php#L608

Pull request are welcome.

**Comment by zorn-v** [comment]
Fixed in v5.6.6
