### ISSUE TITLE
the redirect URL written in the documentation need to be changed

### ISSUE THREAD

**Issue by Takasugi-MBSJK** [zorn-v/nextcloud-social-login#471]
The redirect URL written in the documentation needs to be updated because the implemented redirect URL was changed.

file : docs/sso/google.md

When you can, I hope to update it.

**Comment by Takasugi-MBSJK** [comment]
the point that needs to be changed is...    https://example.com/apps/sociallogin/oauth/google
to
https://example.com/index.php/apps/sociallogin/oauth/google

**Comment by zorn-v** [comment]
It depends on your server configuration
