### ISSUE TITLE
Github login issue with Non-Public Organization Members

### ISSUE THREAD

**Issue by linalinn** [zorn-v/nextcloud-social-login#475]
Hi,

I encountered an issue when setting up GitHub login with limiting to a GitHub Org. This resulted in the `Login is available only to members of the following GitHub organizations` error even if the users are part of that Org.

I was able to fix that by adding `read:org` to the scope in `3rdparty/hybridauth/hybridauth/src/Provider/GitHub.php`, so maybe that could be added. But perhaps instead of requesting read access to the user's organizations. It would be better to use the `/user/orgs` endpoint in `lib/Service/ProviderService.php` and use the `read:user` scope.

**Comment by zorn-v** [comment]
I don't want that my app request some rights that it does not need for.
Close.

**Comment by CRImier** [comment]
I've also had to deal with this issue. It's a pretty basic permission, a lot of plugins request it, and it'd be nice if the app included this permission by default - figuring out why it doesn't work for non-public org members took a fair bit of time and was frustrating :s
