### ISSUE TITLE
Undefined array key "defaultGroup" at /var/www/nextcloud/apps/sociallogin/lib/Service/ProviderService.php#249

### ISSUE THREAD

**Issue by purejosh** [zorn-v/nextcloud-social-login#477]
Hey there. Just did my install today, and I added and removed some apps. I'm not sure which step might've caused this one, but the error I'm seeing is 
```
Undefined array key "defaultGroup" at /var/www/nextcloud/apps/sociallogin/lib/Service/ProviderService.php#249
```

Is this value meant to be blank? Should it be a certain group? Just wanted to ask before breaking stuff. This error is clogging up my logs pretty decently.

**Comment by zorn-v** [comment]
If you press "save" button in social login settings page, error gone ?

**Comment by purejosh** [comment]
I will try that and update if the errors stop, thank you!

**Comment by purejosh** [comment]
I think that's solved it. Thanks.
