### ISSUE TITLE
Skip update check

### ISSUE THREAD

**Issue by ywtoly** [zorn-v/nextcloud-social-login#482]
Thank you to the author!
I have made modifications based on your version to suit my application scenario, as updates will overwrite the parts I have modified. Therefore, I would like to skip the version update check or prompt for this application separately. How can I do this?

**Comment by ywtoly** [comment]
Is it sufficient to modify the version number in the info.xml file?

**Comment by zorn-v** [comment]
> Is it sufficient to modify the version number in the info.xml file?

Yes

**Comment by zorn-v** [comment]
You confused your local changes with ginhub.
China ? )

**Comment by zorn-v** [comment]
No problem by the way.

**Comment by zorn-v** [comment]
> Change the version number in the 'info. xml' file to match the latest one

You can simply set it to something like 999.99

**Comment by ywtoly** [comment]
> > Change the version number in the 'info. xml' file to match the latest one
> 
> You can simply set it to something like 999.99


 <version>999.99</version>
Still prompting for updates, but the app name is not listed.
![sss](https://github.com/user-attachments/assets/69b7c82f-15dc-4f2b-a180-3e6d9a502756)

**Comment by ywtoly** [comment]
> > Change the version number in the 'info. xml' file to match the latest one
> 
> You can simply set it to something like 999.99


 <version>999.99</version>
Still prompting for updates, but the app name is not listed.
![sss](https://github.com/user-attachments/assets/c83c12fc-1813-4bf3-adff-d9b5eaff9153)

**Comment by zorn-v** [comment]
It ask only first time you change version in xml

**Comment by zorn-v** [comment]
Problem solved ?

**Comment by ywtoly** [comment]
With your patient guidance, I finally succeeded!
Before modifying the XML file, disable the application first, and then enable it after modification, and there will be no problem.
Thank you again for your patience!

**Comment by zorn-v** [comment]
Glad to hear that )
