### ISSUE TITLE
Nextcloud-Social-Login does not support the use of WeChatWork as an Oauth2 provider to provide unified authentication login services

### ISSUE THREAD

**Issue by boHam-wang** [zorn-v/nextcloud-social-login#487]
- My question: After reading the Web authorization Login document of WeChatWork, it is found that the authentication login mode of Oauth2 used by Wechatwork is inconsistent with the authentication login mode of Custom Oauth2 supported by Nextcloud Social Login, so additional parameters need to be added to the url configuration bar. And more configuration options to meet WeChatWork's authentication requirements
-  the Web authorization Login document of WeChatWork：
> https://developer.work.weixin.qq.com/document/path/96440

- Goal: My goal was to use WeChatWork Oauth2 and social login's Oauth2 to achieve unified authentication

**Comment by boHam-wang** [comment]
When I created a nextcloud application in the enterprise wechat background management system, and configured the nextcloud address; Then configure Custom OAuth2 items on nextcloud-social-login according to the document. Click nextcloud on the enterprise wechat, and a prompt will appear on the page: "Can not get identifier from provider".

![1731403121389](https://github.com/user-attachments/assets/f54c41cd-aa4c-42df-8652-e00b6e7c6bef)
![1731403181273](https://github.com/user-attachments/assets/60dc60f5-070a-4b66-b8c1-db0f74b7cb4f)

**Comment by boHam-wang** [comment]
Can provide default provider support for the WeChatWork Ouath2 standard?

**Comment by zorn-v** [comment]
You can check `3rdparty/custom/Hybridauth/Provider/PlexTv.php` for example how to implement "default" provider that does not exists in hybridauth.

**Comment by boHam-wang** [comment]
ok，I have developed WeWork.php Provider code to solve this problem.

**Comment by zorn-v** [comment]
You can make pull request then
