### ISSUE TITLE
Remove Provider Prefix

### ISSUE THREAD

**Issue by CoplandTech** [zorn-v/nextcloud-social-login#488]
Hello, could you please add a setting to the "Remove Provider Prefix" plugin for those who use a single Provider for authorization? Personally, I do not need the Provider prefix, for example: google-, telegram-, and so on.

Or at least suggest which code to edit.

I would be very grateful for any feedback!

**Comment by CoplandTech** [comment]
I'm not a great coder, so please don't judge too harshly.

I decided to tackle the problem on my own and am sharing the solution here. Use it at your own risk.

The condition "if active providers = 1, then we delete the prefix"

[ProviderService.zip](https://github.com/user-attachments/files/17717298/ProviderService.zip)

**Comment by ywtoly** [comment]
ProviderService.php
`$uid = $provider.'-'.md5($profileId); -------$uid = md5($profileId);`
