### ISSUE TITLE
PKCE support

### ISSUE THREAD

**Issue by albundy83** [zorn-v/nextcloud-social-login#490]
Hello,

will it be possible to add PKCE support ?
It will be a nice feature to improve security.
Here a short example of what has been done on a fork of your great project:
https://github.com/pulsejet/nextcloud-oidc-login/pull/203

I don't know if it could be so easy to add ?

Thanks for your help

**Comment by zorn-v** [comment]
> However, it has a weakness when used by applications that cannot securely maintain secrets, such as native applications or single-page applications (because their are hosted in the public internet). It’s like leaving the key under the mat; if Agent Smith knows where to look, he might just find it.

How Agent Smith can see https traffic ? 
If he can, you have much more problems then PKCE support :wink:

**Comment by albundy83** [comment]
You are right, thanks for explanation :-)
