### ISSUE TITLE
how to add setting-items in settings page for the default provider developed by myself?

### ISSUE THREAD

**Issue by boHam-wang** [zorn-v/nextcloud-social-login#492]
I hava developed the WeWork default provider to fit my use case.
Now I use the deault setting-items in the setting web page and some other setting-items in my WeWork.php code to achieve the Oauth2 login through WeWork.

My question is : where to add  or modify the code or settings to add more setting-items in the web page，in this way the admin can configure all the needed params for oauth2 providers.

Example:  In the web page, when I choose the default provider "WeWork", here are four setting-items below:
- App id
- Secret
- Agent id
- Default group

then those params can be used in the backend server to finish Oauth2 login process.
![企业微信截图_17332998473032](https://github.com/user-attachments/assets/c5e03930-18e0-4db7-bfe1-aa97c65cfc15)

**Comment by zorn-v** [comment]
You can do something like this
https://github.com/zorn-v/nextcloud-social-login/blob/348e818267515b3497677cd234bcf9ffe4681775/src/components/Settings.vue#L82
