### ISSUE TITLE
Social login and Nextcloud desktop app

### ISSUE THREAD

**Issue by Flore-mozfr** [zorn-v/nextcloud-social-login#5]
Hello,
It's not really an issue of social login, but it might be an issue for the users of social login.

When you want to connect an account in the desktop app, it's asking for login / password. Whereas the nextcloud app (at least the android one) redirects you to the login page to authorize the app and the social login is there.

Honestly, it's the last blocker for me, I want my users to be able to sync files on their desktop computers (or laptop) and this may not be easy.
It's probably more an issue with the desktop app, but I believe that you would know better than me...

Thanks again for the app and your dedication to it

**Comment by zorn-v** [comment]
Honestly, I dont understand how this app belongs to desktop app 😏

**Comment by Flore-mozfr** [comment]
Usecase:

- User A creates an account on nextcloud using social login
- A logs in Nextcloud everyday using their google account (thanks to social login)
- A logs in on mobile app using their google account
- A installs the desktop app to sync their file on their computer
- The desktop app asks for login/password but does not offer social login (unlike mobile apps): FAIL

I know it's not something you can change on your app, because it probably belongs to nextcloud desktop app, but I was wondering if you had any advice or knowledge on where and how to report that.

**Comment by zorn-v** [comment]
Try ask here https://github.com/nextcloud/client/issues

**Comment by Flore-mozfr** [comment]
Done: https://github.com/nextcloud/client/issues/261

**Comment by lachmanfrantisek** [comment]
@zorn-v OK, I got it.

**Comment by zorn-v** [comment]
Will wait release with this changes https://github.com/nextcloud/desktop/pull/75
Currently I'm try to fix client login flow for social login https://github.com/zorn-v/nextcloud-social-login/issues/35#issuecomment-401061735

**Comment by zorn-v** [comment]
Tested on latest 2.5 build from here https://download.nextcloud.com/desktop/daily/
All works fine

**Comment by pktiuk** [comment]
I have a question related to this statement:

> Some settings need password confirm, but users created via social login does not know their (nobody knows smile).

Is there any random password initialized during creation of such a user, or there is just no password for such a users?

If they don't have any password, then I could report lack of handling this case on nextcloud repo. :)    
(field 'current password' should not be visible)
![image](https://user-images.githubusercontent.com/45544416/223765861-c70e2f12-645b-4d03-9b5f-8ca2c784ff5b.png)

**Comment by zorn-v** [comment]
> Is there any random password initialized during creation of such a user

Yes

**Comment by pktiuk** [comment]
That's a shame.    
Using this workaround is not very obvious for many users and required instance with configured email. :/
