### ISSUE TITLE
How to use "Profile Fields (optional, comma-separated)" in Custom OAuth2?

### ISSUE THREAD

**Issue by gamekeeper** [zorn-v/nextcloud-social-login#50]
How do I use this setting in Custom OAuth2? 

I would use the name string from the profile response as 'Full name' in Nextcloud when a new account is created. Currently the 'Full name' is the Custom OAuth2 Internal Name + identifier. And that looks a bit weird.  --> https://invisioncommunity.com/developers/rest-api?endpoint=core/me/GETindex  

I have used 'name' as Profile Field, but I dont see it going anywere. Cant find any documentation about this either.  

Would be nice if you configure a matching table of Nextcloud profile settings with the profile field from any custom oauth2 profile response.

**Nextcloud -> Invision Community or any custom Oauth2**
Profile picture -> photoUrl 
Full name -> name
Email -> email
Phone number ->
Address ->
Website -> profileUrl
Twitter

**Comment by zorn-v** [comment]
![default](https://user-images.githubusercontent.com/12619075/44795675-9a0e6180-abee-11e8-81fe-f00beed071be.png)

**Comment by gamekeeper** [comment]
Thanks 👍
