### ISSUE TITLE
Invision Community - reauthorise every time during login

### ISSUE THREAD

**Issue by gamekeeper** [zorn-v/nextcloud-social-login#51]
Is it necessary to reauthorise during every login? Is this normal behaviours for Oauth2 logins? Cant an authorisation not being reused until Token Expiration? 

![43358155-a27a9908-928d-11e8-8557-8ffc2873895e](https://user-images.githubusercontent.com/41835780/44731917-8c6cb500-aae4-11e8-8aff-e5bda330b226.png)

![nextcloud](https://user-images.githubusercontent.com/41835780/44731951-9e4e5800-aae4-11e8-8852-ab60c890040b.png)

**Comment by zorn-v** [comment]
Questions to Invision Community...

**Comment by gamekeeper** [comment]
Thanks 👍
