### ISSUE TITLE
Error when new user login from Custom OIDC keycloak provider

### ISSUE THREAD

**Issue by Ludogo** [zorn-v/nextcloud-social-login#52]
Hello,

New users get error when trying to connect using a keycloak provider V4.3.0 Final. 
 _Can not get identifier from provider_
I think this is due to scope data or something to configure but cannot find help. 
Everythings woked fine until i update keycloak and social login to last version.

What does social login expect as user data ? 

![image](https://user-images.githubusercontent.com/9932379/44774422-5de9eb00-ab73-11e8-903b-2833abafc0e2.png)

**Comment by zorn-v** [comment]
If you don't know how you provider response.... its not my problem.

**Comment by Ludogo** [comment]
? 
No, i don't know what is expected by social login: What is _identifier_ ? 
There is no trace, no log that's why i need help :)

**Comment by zorn-v** [comment]
`identifier` is what 'should' return as unique id. If not, you can give me pull request...

**Comment by zorn-v** [comment]
And I don't need to know how every provider returns answer. I guarantee only for preconfigured and tested by my own...

**Comment by Ludogo** [comment]
Yes of course i understand your point of view. 
I just try to understand if "identifier" is concerning current user trying to logon or someting else. 
Is this data is part of scope ? Does this data must have a particular name ?

**Comment by zorn-v** [comment]
Nope. It is DATA of response from server.

**Comment by Ludogo** [comment]
Ok after having invastigate i found the root cause of the problem : User's name contains a "î ". 
This provocs bad base64_decode from CustomOpeIDConnect line 20 and 21 : 
```
$data = base64_decode($payload);
 $this->storeData('user_data', $data);
```
$data contains corrupted json data that cannot be decode in getUserProfile method. 
If i remove î from user's name it works. 

I am not a php developer. May have you any idea to correct this ? 
Hope this help. 
regards,
Ludo

**Comment by zorn-v** [comment]
That corrupted json comes from server. I cannot convert any garbage (server can return ANY) to valid json, sorry. It's a server problem, as it generate that incorrect json. All non ascii symbols should be as "\xBADE" for example AFAIK.
