### ISSUE TITLE
Discord Login didn't work

### ISSUE THREAD

**Issue by Luc1412** [zorn-v/nextcloud-social-login#53]
I don't know if I made a mistake or if it's Social Login, but it doesn't work.

The way I did it:
1. Go on: https://discordapp.com/developers/applications/
2. Create new Application
3. Set Custom Name
4. Copy Client ID + Client Secret and paste it in App id and Secret
5. Save

The Error: https://i.imgur.com/USOTX9o.png

**Comment by stardebris** [comment]
Where do I redirect it to?
I'm trying this but I get that same error.

I don't know what link to add to the redirects.

**Comment by chiyi4488** [comment]
https://your.domain/index.php/apps/sociallogin/oauth/facebook

**Comment by stardebris** [comment]
I assume that but discord
https://your.domain/index.php/apps/sociallogin/oauth/discord
?

**Comment by chiyi4488** [comment]
Maybe,you can try it.

**Comment by EatDev** [comment]
What is The Discord redicurl ?

**Comment by xxredxpandaxx** [comment]
The info can be found here. https://apps.nextcloud.com/apps/sociallogin#configure-discord

The redirect url is https://nextcloud.mydomain.com/apps/sociallogin/oauth/discord.
