### ISSUE TITLE
Facebook Login URL Bloacked Problem

### ISSUE THREAD

**Issue by piscess16** [zorn-v/nextcloud-social-login#56]
how to setting ?

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

is my setting wrong ？
the Valid OAuth Redirect URIs actual setting is ?

my website is 

https://skshop.com.my/nextcloud

**Comment by chiyi4488** [comment]
Do you have a redirect URL?
I think you need to set.
Your redirect URL should be...
https://skshop.com.my/nextcloud/index.php/apps/sociallogin/oauth/facebook

**Comment by chiyi4488** [comment]
為啥小老闆海苔不用錢：D哈哈（skshop.com.my)
