### ISSUE TITLE
Make permanent custom changes

### ISSUE THREAD

**Issue by Dgo27** [zorn-v/nextcloud-social-login#60]
Hi, I've done a little changes on Custom OAuth2 in order to read API from kayako.com and I would to keep it saved even if in the future the app will be updated.
I've simply replaced $response->id in $response->data->id in /lib/Provider/CustomOAuth2.php
if (!isset($response->identifier) && isset($response->data->id)) {
    $response->identifier = $response->data->id;
}
How can I make it permanent?
Thank you for this useful app

**Comment by zorn-v** [comment]
It's not good solution becase it is not compatible with invisioncommunity response (for wich I made that ugly workaround).

**Comment by Dgo27** [comment]
It was only a fast custom fix, maybe a better solution could be to write a new /Provider/ file. But I think that also these files will be overwritten on updates. Is it true? Is there the possibility to save and link a provider file in a "safety" folder that won't be deleted on next update?

**Comment by zorn-v** [comment]
You should acquainted with the concept of pull request 😉 
https://help.github.com/articles/creating-a-pull-request/
For small changes you can use "Edit file" button in github interface.

In you case it's better add your "if condition" below exsisting one. It will be still ugly hack but without breaking of existsing.

PS. I can add it by myself, but try it 😄

**Comment by zorn-v** [comment]
![w9sxnbu](https://user-images.githubusercontent.com/12619075/45687020-e9620500-bb90-11e8-988a-fd7ea0ae1ec6.png)

**Comment by zorn-v** [comment]
Already in master
