### ISSUE TITLE
invalid token with WP OAuth Server

### ISSUE THREAD

**Issue by johappel** [zorn-v/nextcloud-social-login#62]
I want to use nextcloud-social-login with [WP OAuth Server](https://wordpress.org/plugins/oauth2-provider/)

I tried many different settings but the result ist allways this:
![image](https://user-images.githubusercontent.com/307023/47418696-ee5f3900-d77a-11e8-9d7d-df8714c53ea4.png)

OAuth-Server Setting
![image](https://user-images.githubusercontent.com/307023/47418995-8a894000-d77b-11e8-95b5-1120ee73831b.png)

![image](https://user-images.githubusercontent.com/307023/47419114-ca502780-d77b-11e8-908a-a0fb19a84a91.png)

Any help?

**Comment by gamekeeper** [comment]
![image](https://user-images.githubusercontent.com/41835780/49689776-7b413480-fb26-11e8-8743-9cd26f7dbde0.png)

https://github.com/zorn-v/nextcloud-social-login/issues/50#issuecomment-416982210
