### ISSUE TITLE
Allow to map some other field to uid than sub

### ISSUE THREAD

**Issue by ju55i** [zorn-v/nextcloud-social-login#66]
At the moment sub is used for the uid and sometimes it is not preferable if we want to use LDAP backend at the same time for example. It would be great if one could map the uid field to another field from userinfo endpoint (preferred_username for example).

**Comment by zorn-v** [comment]
I do not want to use fields for uid that end user can change due security and other reasons. So no.

**Comment by bminer** [comment]
I originally thought this night be a good idea, as well, but then I read the OIDC spec: https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability

The spec explicitly forbids this.
