### ISSUE TITLE
Add support for ORCID

### ISSUE THREAD

**Issue by severin-lemaignan** [zorn-v/nextcloud-social-login#67]
A useful addition to the oauth providers would be ORCID: https://members.orcid.org/api/integrate/orcid-sign-in

ORCID is the de-facto standard identity provider for the academic community, and having ORCID based auth would certainly contribute to the adoption of nextcloud by university & research centers.

**Comment by zorn-v** [comment]
You can add it as custom OIDC provider. 
* Go to https://orcid.org/developer-tools
* Create app with something like this
![default](https://user-images.githubusercontent.com/12619075/49555425-85f3a200-f94b-11e8-803f-b9309e6df757.png)
* Create custom OIDC provider in nexcloud admin settings with data from prev step 
Something like this (internal name and title as you wish)
![default](https://user-images.githubusercontent.com/12619075/49556066-ea176580-f94d-11e8-94a3-831d18b36b02.png)
