### ISSUE TITLE
Social login with google+ going deprecated ???

### ISSUE THREAD

**Issue by stratege1401** [zorn-v/nextcloud-social-login#69]
Hello.

As i use the google cloud plateform, i receive an email today with this warning:

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

Today, on my nextcloud server, i am only using your app for user login with mostly their google account. 

My questions are:
- does your app will be impacted by this change of policy from google.
- If yes, will you have some kind of contigency plan (  i did saw the Hybridauth 3 in your code ...  )
- if yes, should i start to warn my users and start thinking alternates options

Thank in advance for clarification

PS:  my warning is clearly about v1 G+API witch is about to die ...

Project | Google+ API Name | Version | Method
-- | -- | -- | --
nextcloud_APP_social | plus | v1 | plus.people.get

**Comment by zorn-v** [comment]
Added issue in hybridauth repo. Let's see what they say

**Comment by stratege1401** [comment]
thx.  Otherwise, the new thing is Google Sign-in https://developers.google.com/identity/sign-in/web/

**Comment by zorn-v** [comment]
I changed google scope in v1.11.3
Maybe it helps

**Comment by stratege1401** [comment]
ok. i change my api key v1 for an  Oauth
original format was like: key=API_KEY =  AIzaSyxxxxxxLyqMRcivb_gg6tcxxxxxxLmAg 
new Oauth is now like: 8368xxxxxx23-uke25fmjdxxxxxxxx9a8r2iur302joa2.apps.googleusercontent.com

Unfortunatly, i may have done something wrong because i did not correctly type in the return uri and i get an error message:

`The redirect URI in the request, https://nextcloud.rkn.ovh/index.php/apps/sociallogin/oauth/google, does not match the ones authorized for the OAuth client. `

Could you give the good uri your app is using ...

switch back to my v1 without troubles

**Comment by zorn-v** [comment]
You doing it wrong I think

**Comment by zorn-v** [comment]
Previosly something like this was with Facebook.

**Comment by stratege1401** [comment]
you can definitly consider fixed, as all my users loged in, and i see only Aouth V2 keys access now
