### ISSUE TITLE
Callback url always bad in all case with NextCloud 15

### ISSUE THREAD

**Issue by Xarkam** [zorn-v/nextcloud-social-login#71]
Hello, 
how to correct configure your plugin with nextcloud 15 ?

for github, I receive always this :
```
Provider returned an error: redirect_uri_mismatch The redirect_uri MUST match the registered callback URL for this application. 
https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch
```
I give to github this callbakc url: https://mysite.osames.org/apps/sociallogin/oauth/GitHub (accordance with #11)

Same with discord and twitter.

**Comment by zorn-v** [comment]
https://mysite.osames.org is domain with your nextcloud instance ? I don't think so...

> Just copy link of GitHub button on login page of nexcloud and paste it as redirect_url

**Comment by Xarkam** [comment]
The callback url is https://nextcloud.osames.org/apps/sociallogin/oauth/GitHub
And the error is: `redirect_uri_mismatch The redirect_uri MUST match the registered callback URL for this application`

**Comment by zorn-v** [comment]
Just test on nexcloud 15.0.1RC2 - all works fine. Can you show screen of redirect uri from github app setting ?

**Comment by Xarkam** [comment]
![image](https://user-images.githubusercontent.com/331816/50953716-8e904880-14b4-11e9-9865-a54fb51be69b.png)

**Comment by zorn-v** [comment]
Try to set it as https://nextcloud.osames.org
Or maybe update nextcloud to 15.0.1RC2 (beta channel)

**Comment by zorn-v** [comment]
Well, then wait until it released.

**Comment by zorn-v** [comment]
It is released yesterday :smile:

**Comment by Xarkam** [comment]
Hello, I tested with 15.0.2 and it's same problem.

The only difference is I redirected to github login page. After he back to my nextcloud instance and its same error.

`Provider returned an error: redirect_uri_mismatch The redirect_uri MUST match the registered callback URL for this application`

Could that be because it is a docker instance? But, I have other services with oauth in docker instance and I not have any problem with is

**Comment by zorn-v** [comment]
> Could that be because it is a docker instance?

Yep. You can check by adding something like 
```php
die($callbackUrl);
```
below this line
https://github.com/zorn-v/nextcloud-social-login/blob/66263c75b8d383901f600fbb3cc32f378d0ae1ef/lib/Controller/LoginController.php#L92

If you'll see that url is incorrect, try to add `overwritehost` with proper host in `config.php`

**Comment by Xarkam** [comment]
Hello,

I think it's settled.

I had already configured the overwritehost but I saw that the cli was positioned on http and not https.
I also added the `'overwriteprotocol' => '',` on https

Result, with my account, i receive a message email address already exist :)

**Comment by zorn-v** [comment]
You can disable appropriate options to allow create account with exists email. In that case you cannot reset password by email for such accounts, only by login.
