### ISSUE TITLE
Can we get rid of the $provider-$profileId?

### ISSUE THREAD

**Issue by remkolodder** [zorn-v/nextcloud-social-login#72]
Hi,

I am trying to use the openid-connector from Keycloak with a sub-mapping to the username. This works "well", except that it prepends the "Internal name" for the authentication method. Since my users are just <username> instead of <internalname>-<username>. I would like to get rid of it.

I found that the function is handled in: lib/Controller/LoginController.php
Changing the line 230 gives me the wished output:

--- lib/Controller/LoginController.php.orig     2019-01-04 17:41:52.387496000 +0100
+++ lib/Controller/LoginController.php  2019-01-04 17:41:59.346521000 +0100
@@ -227,7 +227,7 @@
         if (empty($profileId)) {
             throw new LoginException($this->l->t('Can not get identifier from provider'));
         }
-        $uid = $provider.'-'.$profileId;
+        $uid = $profileId;
         if (strlen($uid) > 64) {
             $uid = $provider.'-'.md5($profileId);
         }

Can you please consider making this a selectable? I can imagine that if users authenticate via different protocoles you might want to prepend them, but in my case I dont need the functionality.
Thanks!
Remko

**Comment by zorn-v** [comment]
1. You have one provider
2. Tomorrow you add second provider
3. Second provider suddenly return response with uid of existing user (not belong to real user)
4. Someone get access to someone else account (possible even admin)

How to handle this situation ?

**Comment by remkolodder** [comment]
Yes, well at least the administrator needs to be aware of what they are doing. The default can ofcourse be that it has the provider+profileid setting.But in my case I only have one SSO environment and I do not want to have "Internal Name"+id names as users. I want them to have their normal name "(id)".

If it is a selectable per provider, and a message or hover text is included that " be aware when you enable this, every user that authenticates with the same name, will have access to that specific accountnames data and shares". 

If the administrator thinks he needs to fiddle with those settings (And deviate from the standard settings) then he/she needs to be aware of what is being done. If people want to shoot themselves in the foot, they will :-)

**Comment by zorn-v** [comment]
> I want them to have their normal name "(id)".

ID IS NOT NAME. Don't use entities as something they're not. There is proper field for that.

**Comment by zorn-v** [comment]
I found a compromise solution - if there is no "display name" field in server response, use identifier without prefix as "display name" on account creation.Will be in next release.

**Comment by zorn-v** [comment]
Released v1.12.0

**Comment by dubit0** [comment]
I would like to follow up on this. It is really useful to get rid of the provider prefix in order to map the SSO login onto the users of a different, underlying authentication backend (eg. LDAP). 

In my case, I'm running my own IdP (keycloak) that syncs users with an LDAP directory. NC gets the users from the same LDAP directory. Without the provider prefix, I can use social-login for SSO  and get the users transparently mapped to the LDAP users. The reason to do this is the following: For obvious reasons, social-login sets a random password upon account creation in NC. This implies that SSO users cannot access NC by other means than SSO auth (unless they manually set a password within NC).

Of course, getting rid of the provider prefix does not work in situations where more than one IdP provider is configured (due the security issues discussed before). However, maybe it is possible to allow disabling the prefix in situations where only one provider is configured.

**Comment by zorn-v** [comment]
> However, maybe it is possible to allow disabling the prefix in situations where only one provider is configured.

And what to do if additional provider will be added later ?

**Comment by dubit0** [comment]
Either you have only one provider and it makes sense to map the accounts on an underlying backend or you are not. It that sense, I would say, the admin should not be allowed to add a second provider when mapping users.

One idea might be the following: Provide a checkbox along the lines of "Map SSO users to existing users (only possible with a single provider)". When this is checked, the prefix is not added to the IDs and it is no longer possible to add a second provider. If already more than one provider is configured, the checkbox should be unavailable.

**Comment by krono** [comment]
> Either you have only one provider and it makes sense to map the accounts on an underlying backend or you are not. It that sense, I would say, the admin should not be allowed to add a second provider when mapping users.
> 
> One idea might be the following: Provide a checkbox along the lines of "Map SSO users to existing users (only possible with a single provider)". When this is checked, the prefix is not added to the IDs and it is no longer possible to add a second provider. If already more than one provider is configured, the checkbox should be unavailable.

That would be awesome.

An upgrade of this plugin from pre messed up my whole instance.
Exisiting users now can't login and new user have a different id scheme, which is horrendeous with clients.
