### ISSUE TITLE
[Feature Request] Please support Tencent QQ oauth2

### ISSUE THREAD

**Issue by GammaPi** [zorn-v/nextcloud-social-login#74]
The custom oauth2 function works great, but still failed to generalize to Tencent QQ oauth2 interface.
Check this (Chinese Content): http://wiki.connect.qq.com/%e5%bc%80%e5%8f%91%e6%94%bb%e7%95%a5_server-side

The documentation says its oauth2 process requires 3 steps
1.Authorize using **Authorize URL**         [currently supported]
2.Get Token using **Token** URL              [currently supported]
3.Get openid                                              [It's an extra step which seems to be not supported]
4.Get User profile                                       [currently not supported because it requires additional fields from step3 results]

Tencent is one of the largest developers in China and its product is widely used, so maybe some chinese php developers can help to create a built-in Tencent QQ oauth2 plugin?

I also think it can be solved by adding extra options to enable the user to config 1...n custom requests in sequence. Requests can be specified as Get/Post individually and the user can use placeholders to represent fields that was returned from previous steps. After each Get/Post request, the json result is parsed and all fields returned can be stored in a map for future use (replace placeholder). In that way many compatibility problems will be solved.

**Comment by GammaPi** [comment]
By the way, tencent protocol is still oauth2 rather than OpenID/OpenID connect to the best of my knowledge. It just had an additional step to get a field called OpenID.

And from the code I think the Profile Fields were simply appended to the back of the url according to here. (I may be wrong because I'm not a PHP guy)

**nextcloud-social-login/lib/Provider/CustomOAuth2.php**
```
class CustomOAuth2 extends OAuth2
{
    /**
     * @return User\Profile
     * @throws UnexpectedApiResponseException
     * @throws \Hybridauth\Exception\HttpClientFailureException
     * @throws \Hybridauth\Exception\HttpRequestFailedException
     * @throws \Hybridauth\Exception\InvalidAccessTokenException
     */
    public function getUserProfile()
    {
        $profileFields = array_filter(
            array_map('trim', explode(',', $this->config->get('profile_fields'))),
            function ($val) { return !empty($val); }
        );
        $profileUrl = $this->config->get('endpoints')->get('profile_url');
        if (count($profileFields) > 0) {
            $profileUrl .= (strpos($profileUrl, '?') !== false ? '&' : '?') . 'fields=' . implode(',', $profileFields);
        }


```

**Comment by GammaPi** [comment]
Issue #68 may caused by the same reason

**Comment by GammaPi** [comment]
Adding QQ support is very meaningful to chinese users becuase not much of the supported service providers can be accessed by chinese users.

**Comment by zorn-v** [comment]
Are you try Custom OIDC with followed urls and `openid` scope ?

* https://graph.qq.com/oauth2.0/authorize
* https://graph.qq.com/oauth2.0/token

**Comment by GammaPi** [comment]
Yes, but it won't work.
It seems that Tencent's protocol is still oauth2, but it requires an extra step to get an extra field called openid and developers has to use this openid to get user info instead of use acces_token.

**Comment by GammaPi** [comment]
No id_token was found.
When using oidc Nextcloud says: No id_token was found.

**Comment by zorn-v** [comment]
> so maybe some chinese php developers can help to create a built-in Tencent QQ oauth2 plugin?

If someone implement it as Hybridauth provider I'll add it 
https://github.com/hybridauth/hybridauth/tree/master/src/Provider
