### ISSUE TITLE
Telegram auth

### ISSUE THREAD

**Issue by hibryid** [zorn-v/nextcloud-social-login#75]
Hello.
If it's possible, how to add a telegram auth to nextcloud?

**Comment by zorn-v** [comment]
How do you imagine that ?

**Comment by zorn-v** [comment]
I think it'll be better to implement it in separate app.

**Comment by hibryid** [comment]
Maybe, I can help you testing?
For now, after successfull logining:
![image](https://user-images.githubusercontent.com/32869232/51003207-8977db80-153e-11e9-8342-1c15fc63872f.png)
and
![image](https://user-images.githubusercontent.com/32869232/51003293-ce037700-153e-11e9-9dd9-262927cc93b6.png)

I get this:
![image](https://user-images.githubusercontent.com/32869232/51003249-ac09f480-153e-11e9-9ca2-2669ff55afc3.png)

**Comment by hibryid** [comment]
Maybe, I can help you testing?

After successfull logining:
![image](https://user-images.githubusercontent.com/32869232/51003404-45d1a180-153f-11e9-932b-ac0520a9d926.png)
and
![image](https://user-images.githubusercontent.com/32869232/51003421-5f72e900-153f-11e9-9d5f-b291580f306d.png)
I get this:
(internal error)
![image](https://user-images.githubusercontent.com/32869232/51003439-74e81300-153f-11e9-8a4f-31163fd229fe.png)

**Comment by zorn-v** [comment]
Он еще не закончен )
Кстати для большинства юзеров из России работать не будет (домен telegram.org заблочен). Тупо виджет не загрузится.

**Comment by hibryid** [comment]
Спасибо)
Ну, телеграмом и в снг пользуются)
Нас группа из 20 человек, у каждого есть телега)
Увидел, что авторизацию по телеграму возможно реализовать:"А почему бы и... да"

**Comment by zorn-v** [comment]
Check v1.12.0

**Comment by hibryid** [comment]
Yeap

Работает
![image](https://user-images.githubusercontent.com/32869232/51023991-0764d280-1591-11e9-996b-6ad133772552.png)

**Comment by hibryid** [comment]
Авторизация через приложение nextcloud не проходит
![photo_2019-01-11_11-55-03](https://user-images.githubusercontent.com/32869232/51026741-eb186400-1597-11e9-9a24-edcff57f5517.jpg)
![photo_2019-01-11_11-55-06](https://user-images.githubusercontent.com/32869232/51026746-eeabeb00-1597-11e9-84df-dc4bcc3c2229.jpg)

**Comment by zorn-v** [comment]
Возможно и не будет работать. Телеграмовский виджет открывает новое браузерное всплывающее окно, которое приложуха видимо не открывает. Хз можно ли это разрулить. Будет свободное время - пощупаю.

**Comment by hibryid** [comment]
Ещё нюанс.
Я не уверен насчет того, баг ли это в самом плагине, но действия других участников, зарегистрированных через телеграм, не показываются в истории.
![image](https://user-images.githubusercontent.com/32869232/51087572-b35b1900-175d-11e9-9c95-8c5ff9165787.png)
А если смотреть с аккаунта телеграма, то другого история аккаунта, зарегистрированного вручную, таки видна
![image](https://user-images.githubusercontent.com/32869232/51087595-ff0dc280-175d-11e9-876d-f16bd56e8edd.png)

**Comment by zorn-v** [comment]
Тут надо задавать вопросы аппке activity. Либо у тебя с настройками что то.

**Comment by zorn-v** [comment]
Telegram auth will not work everywhere another than browser.
