### ISSUE TITLE
Login with Amazon (OAuth2)

### ISSUE THREAD

**Issue by mchl-btlr** [zorn-v/nextcloud-social-login#76]
Configuring Custom OAuth2 Provider "Login with Amazon" results in following error: Provider API returned an unexpected response.

![bildschirmfoto 2019-01-14 um 10 18 05](https://user-images.githubusercontent.com/43033467/51104299-155f6100-17e6-11e9-979d-8f976481ed23.png)

Config as follows:

![bildschirmfoto 2019-01-14 um 10 14 21](https://user-images.githubusercontent.com/43033467/51104461-8141c980-17e6-11e9-9639-c49b1f4af89a.png)

The response should only contain user_id, which should be sufficient for authentication. The error persists when adding "user_id" to "Profile fields". 

Could you please inspect? Could Amazon be added to the built-in providers - (please check their pretty Developer API)?

Amazon API OAuth2:
https://developer.amazon.com/docs/login-with-amazon/conceptual-overview.html
Amazon API OAuth Profile:
https://developer.amazon.com/docs/login-with-amazon/customer-profile.html

![bildschirmfoto 2019-01-14 um 10 14 42](https://user-images.githubusercontent.com/43033467/51104336-2dcf7b80-17e6-11e9-8e25-dca6c989eafb.png)

**Comment by zorn-v** [comment]
Amazon added in built-in providers in v1.13.0

**Comment by mchl-btlr** [comment]
Thanks, that was fast! I can confirm that it is working. :-)
