### ISSUE TITLE
Logout support?

### ISSUE THREAD

**Issue by victornoel** [zorn-v/nextcloud-social-login#78]
Hi,

We are using Social Login in order to use keycloak as an openid provider for Nextcloud (see https://framagit.org/oxyta.net/docker-atelier/tree/keycloak/keycloak), and apparently when login out of Nextcloud, users are not logged out of keycloak.

Could this be supported by Social Login?

**Comment by victornoel** [comment]
@zorn-v is the reason technical or by design? We can contribute :)

**Comment by zorn-v** [comment]
There is no standard way for doing this. And I don't see much point in it.
