### ISSUE TITLE
Google Login not working

### ISSUE THREAD

**Issue by jaswanth098** [zorn-v/nextcloud-social-login#79]
When I click on the Google login we are being redirected to https://example.com/apps/sociallogin/oauth/google

But when it is throwing me a 404 error
But it working for GitHub the below is the link for GitHub Login
https://example.com/apps/sociallogin/oauth/GitHub

But when I change the google URL by renaming google at end Google
https://example.com/apps/sociallogin/oauth/Google

It throws me a 403 error, so I started debugging it.
I've Checked the code and made a small change which worked for me, But I don't think this might be the way of doing it, Posting my finding.

In the LoginController (sociallogin/lib/Controller)While getting $providers in `oauth` function which is returning json which is having a key  "google".
```
$providers = json_decode($this->config->getAppValue($this->appName, 'oauth_providers', '[]'), true);
```
But the $provider(input param of oauth function) is `Google`(capital letter G) which might be because I changed `google` word in the above google url with `Google`(capital G).
But in the below line we are checking if $provider is there in $providers keys
```
if (is_array($providers) && in_array($provider, array_keys($providers))){
  ....
}
```
I have change two conditions on is above by adding strtolower around $provider
```
if (is_array($providers) && in_array(strtolower($provider), array_keys($providers))){
  ....
}
```
there is one more condition inside that if condition which also checks if $name is equal to $provider I have changed it as following
```
if ($name === strtolower($provider)) {
  ....
}
```
This works for me because I only use google.

**Comment by FuzzyMistborn** [comment]
I had this same issue, noticed the URL for the login was different now.

Before it was https://example.com/apps/sociallogin/oauth/google
Now it's https://example.com/index.php/apps/sociallogin/oauth/google

Basically need to add the index.php and it should work.

**Comment by zorn-v** [comment]
> Basically need to add the index.php and it should work.

It is wrong configured webserver. As first "problem" not confirmed I think there it is some similar. So I close it
