### ISSUE TITLE
Google Login does not parse existing users

### ISSUE THREAD

**Issue by gelo2002** [zorn-v/nextcloud-social-login#81]
Hi,

I am totally new to GitHub as user, but I am already pretty long programming. 

Anyway, to the matter:
I have activated Social Login to my private Nextcloud instance and registered everything at Google Console. Everything work almost till the end step of logging in, but them at the last step I am not redirected to my account, but I get one of those errors:
1. If I have "Disable auto create new user" box checked, I get message at login that Nextcloud cannot create new user.
2. If I have "Disable auto create new user" box UNchecked, I got message at login, that "something went wrong, contact System Administrator".

Is there a step that I have missed to set it all up properly?

All the best,
G.

**Comment by zorn-v** [comment]
Check logs in admin panel or in log dir

**Comment by gelo2002** [comment]
Basically I am getting only those 3 types of entrien in "logging":

Fatal | ocs_api | Failed addUser attempt: User already exists. |   | 2019-03-13T12:54:16+0100

Fatal | files_antivirus | OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run, exception: The antivirus executable could not be found at /usr/bin/clamscan |   | 2019-03-13T12:48:02+0100

Error | PHP | You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /var/www/html/nextcloud/3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18 |   | 2019-03-14T09:59:44+0100

wherby the first one is generated when I am trying to login with Google.

The security and setup warings are as follows (mind, that this is test and NOT production system, so I don't really set up any "security" tweaks yet):
here are some warnings regarding your setup.
Your web server is not properly set up to resolve "/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's documentation page. On Nginx those are typically the lines starting with "location ~" that need an update.
Your web server is not properly set up to resolve "/ocs-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's documentation page. On Nginx those are typically the lines starting with "location ~" that need an update.
SQLite is currently being used as the backend database. For larger installations we recommend that you switch to a different database backend. This is particularly recommended when using the desktop client for file synchronisation. To migrate to another database use the command line tool: 'occ db:convert-type', or see the documentation ↗.
Accessing site insecurely via HTTP. You are strongly adviced to set up your server to require HTTPS instead, as described in the security tips ↗.
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
No memory cache has been configured. To enhance performance, please configure a memcache, if available. Further information can be found in the documentation.
You are currently running PHP 7.0.33-0+deb9u3. Upgrade your PHP version to take advantage of performance and security updates provided by the PHP Group as soon as your distribution supports it.
The PHP OPcache is not properly configured. For better performance it is recommended to use the following settings in the php.ini:
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
imagick
Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.
filecache.mtime
filecache.storage_mtime

**Comment by zorn-v** [comment]
Check users with uid starting with `google-`, and delete it, logout and try to relogin with google
Anyway this is strange. Are you using non modified last wersion of SocialLogin app ?

**Comment by gelo2002** [comment]
I have deleted all users starting with `google-`, but those are created only when the checkbox for "Disable auto create new user" is UNchecked. 
As the system is on VM, I have not only reloaded the page, logged out, tried from other (private) web browser session, but also rebooted VM, reloaded server and similar thing...
The SocialLogin app is out of the box, no adjustments done, just set up with Google App ID etc. 
Maybe that's something with SQLite? I will try in some spare time try out MariDB/MySQL...

Anyway, the SocialLogin app lookup for e-mail, right? Not other fields like username registered in my instance of Nextcloud?

**Comment by zorn-v** [comment]
> Anyway, the SocialLogin app lookup for e-mail, right? 
No, moreover email is optional AFAIR. And it is possible to have multiple NC accounts with same email.
App uses identifier from provider prefixed with provider name as UID

**Comment by gelo2002** [comment]
OK!
I got it, it's working now. I have missed one setting, binding user account to google on Additional Settings page of the user... 
This thread can be closed.
Thanks for pointing out to the UID!
