### ISSUE TITLE
Social Login Security failure 

### ISSUE THREAD

**Issue by Le0x555** [zorn-v/nextcloud-social-login#85]
When I set a filter on Domain login "@example.com" I can log in with that, but if select create an account, he let me create with @gmail.com and without "@example.com". When I say, I don't want to create an account, I go back or select login as an alternative. Now we don't have the limitation "@example.com" and can log in.

That is, anyone can log in...

**Comment by Le0x555** [comment]
Oops I close this accidentally

**Comment by zorn-v** [comment]
It is google feature (not documented BTW). I only can check on login and show error if `hd` parameter inset for google provider and user email does not match it. Like in this PR https://github.com/zorn-v/nextcloud-social-login/pull/82

**Comment by Le0x555** [comment]
Nice #82 work for me thank you

**Comment by zorn-v** [comment]
Done in v1.14.2
