### ISSUE TITLE
Roles to Group matching support in "Custom OpenID Connect" Configuration

### ISSUE THREAD

**Issue by funkyferdy** [zorn-v/nextcloud-social-login#87]
First, Great Nextcloud-Extension. It's amazing! Thank you so much for this. I was able to attach and configure a custom "Custom OpenID Connect" Identity Provider based on (Opensource based) "WSO2 Identity Server" that we use here in less than 5 Minutes without any worries. World Record :)

Now to my request/wish. 

In wso2 identity-server you can, in the userinfo-endpoint, output, so called, roles-claim. Basically this are Usergroups definded in the identity server. 

Now, it would be great to have 2 Features in your extension:

1) Ability to define wich roles (in Identity Server) are allowed to login to nextcloud at all.
Example: Allow to login only users with Roles A,B,C

2) Ability to "match" Identity-Server Roles with existing nextcloud-groups.
Example: Role in Customer_Company_A equals -> Nextloud-Group 123456

That would be a perfect match between WSO2 Identity Server and Nextcloud.

I can provide more informations/details/code if you think that could be "something".

**Comment by zorn-v** [comment]
You request related to custom provider and not "generic". Maybe need some "built-in" provider like "WSO2 Identity Server". I think about it

**Comment by funkyferdy** [comment]
Excuse me @zorn-v exactly. i used custom provider:

![grafik](https://user-images.githubusercontent.com/22144187/56732586-29f4b300-675e-11e9-9bef-62f8674a3202.png)

But i will close this issue because is discussed allready on another Issue #87
