### ISSUE TITLE
 Default group support for each identity provider.

### ISSUE THREAD

**Issue by jlallana** [zorn-v/nextcloud-social-login#88]
First of all, I apologize for my English. I am using a translator.
I currently have 3 organisms. Each of them has its own identity provider. Everything works perfect but I need to assign permissions to the users according to which body they are members. Currently I have to go into a later step and assign a group such as "organism 1 / organism 2 / organism 3". The software already has a "Default group that all new users belong" option but it applies to all identity providers and not to each one separately. I would work very hard if that field were available to each identity provider.

**Comment by zorn-v** [comment]
Done in v1.15.1
