### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by raudraido** [zorn-v/nextcloud-social-login#89]
Hi,

Just recived email from facebook, they are not happy with social login facebook button design.

_Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign._

    
_You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/._

_Please make the requested changes by 2019-05-01 at 12:00 PST._

_Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help._

**Comment by raudraido** [comment]
Is there a change it will be changed as FB wants or login with FB will be removed?

**Comment by zorn-v** [comment]
I dont know, but I will not do it. If they disable login only on "login button appearance", so - BURN IN HELL FACEBOOK 😈

**Comment by raudraido** [comment]
So, I responded to FB almost as you did to me. Their answer was quite surprising.

_Hi,

Thank you for your reply and all actions taken so far. 

Please mind that due to new policies applied in 1st of May, for the moment, you do not need to take any action, we will come back to you with as soon as the we can assist on all of your question and the queries 

We are sorry for any inconvenience.

Your app will not be enforced until we come back with answers.

Thanks for your understanding.

Thanks,

Emile_

**Comment by zorn-v** [comment]
"app will not be enforced" - mean they block your app, or opposite ?

**Comment by raudraido** [comment]
it means I app continue to work as it was
