### ISSUE TITLE
aws cognito oauth

### ISSUE THREAD

**Issue by salisaim** [zorn-v/nextcloud-social-login#9]
Any one has tried this with aws-cognito user pools ? I am trying to get it done using cognito as OAUTH provider, but i think cognito adds a little bot more complexity to the whole process. My hunch is the client should work if the is a way to pass redirect_uri, that aws-cognito requires in an  openID request. 

Let me try to be more specific here and explain (newbie enthusiasm).

so I have aws-cognito user-pool, and for one of my JS-applications I am using the cognito-auth-(https://github.com/aws/amazon-cognito-auth-js).

I am wondering in the nextcloud-social-login - how can I call this - and use it .

Any help would great.

**Comment by zorn-v** [comment]
No info provided

**Comment by kksmartexchange** [comment]
Is it possible to configure AWS Cogntio user pool with nextcloud social login?

**Comment by zorn-v** [comment]
Currently - I don't think so

**Comment by jabouchleih** [comment]
Works fine for me.
Just create a user pool and an app client for your Nextcloud Social Login plugin.

Make sure you add a valid redirect URL to your app client's settings:
`https://nextcloud.mydomain.com/apps/sociallogin/custom_oidc/my_cognito` 

Create a "Custom OpenID Connect" entry.

Use the following data:

Authorize url: `https://<name>.auth.<region>.amazoncognito.com/oauth2/authorize`
Token url: `https://<name>.auth.<region>.amazoncognito.com/oauth2/token`
Display name claim (optional): `email` (or `name` or ... depending on your needs)
User info URL (optional): `https://<name>.auth.<region>.amazoncognito.com/oauth2/userInfo`
Logout URL (optional): `https://<name>.auth.<region>.amazoncognito.com/logout`
Client Id: `your appclient id`
Client Secret: `your appclient secret`
Scope: `openid`
Groups claim can be empty or you can use `cognito:groups`.
