### ISSUE TITLE
Support for multiple authorized domains

### ISSUE THREAD

**Issue by ronyshtamler** [zorn-v/nextcloud-social-login#91]
Hi,

We currently run 2 Google domains.
Is there a way to allow 2 domains to be authorized?

Thanks,

**Comment by Omaha2002** [comment]
If you configure Google as social login provider you can login with any google domain account. At least I could with an @gmail.com account and a @acme.com account hosted at google.

**Comment by ronyshtamler** [comment]
I meant using acme.com and acme2.com, but not allowing @gmail.com

**Comment by Omaha2002** [comment]
good one, would like that too

**Comment by alexthamm** [comment]
Hi, I would love to see this feature to go a bit further.

My use case: I have a private Nextcloud instance. I'd like to allow users from my own domain and specific external users to create accounts (family, friends). 
Checking the email address (in the case of Google as an OAuth provider) against a list of regular expressions could provide a flexible way to do this. I don't know what feature Facebook and other providers have that could be tested.

This should also cover the requirement from @ronyshtamler.

**Comment by zorn-v** [comment]
@ronyshtamler @Omaha2002
Multiple domains implemented in v2.0.2
Use comma separated list for this

@alexthamm 
Your request is not related to this issue.

**Comment by Omaha2002** [comment]
Shouldn't you change text from:
"Allow login only from specified domain" 
to
"Allow login only from specified domains (comma separated)"
then?
