### ISSUE TITLE
Link to Allow users to connect social logins with their account is missing

### ISSUE THREAD

**Issue by alejandroliu** [zorn-v/nextcloud-social-login#92]
For an user to connect social logins with an existing account they have to:

1. Login to nextcloud with their existing account.
2. Enter in their address bar in their browser:
    - https://$nextcloud_host/settings/user/additional
3. Click on the social login icon, to connect the accounts.

There should be a link in the "/settings" menu to access this "/settings/user/additional" URL.

Currently there is none to be found.

**Comment by zorn-v** [comment]
Seems you need update nexcloud at least to v14

**Comment by alejandroliu** [comment]
I am running Nextcloud v16

**Comment by zorn-v** [comment]
Personal settings moved to sociallogin section in v1.14.4

**Comment by alejandroliu** [comment]
Yes, it works now.  Thanks!
