### ISSUE TITLE
Add Documentation regarding external claims in "Custom OpenID Connect"

### ISSUE THREAD

**Issue by funkyferdy** [zorn-v/nextcloud-social-login#95]
Would be cool to have a little piece of documentation what 
external claims/Profile Fields are expected (by default) to be mapped to local nextcloud-user table.

**Comment by zorn-v** [comment]
You can check it there https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L34
and below (if `user_info_url` is specified).

There is some conditions on user info url.

**Comment by funkyferdy** [comment]
Oh great, thanks!
