### ISSUE TITLE
Map new users to group

### ISSUE THREAD

**Issue by DmitriiKuvshinov** [zorn-v/nextcloud-social-login#97]
Hi
I need to map new user, which was created via Google+ auth to existing group in nextcloud server
I can do this manually by SQL injection, but are there any other way to add users to one group automaticaly?

**Comment by zorn-v** [comment]
You can set "default group" in provider (google+ in your case) settings

**Comment by DmitriiKuvshinov** [comment]
exactly
did not notice. thank

**Comment by DmitriiKuvshinov** [comment]
exactly
did not notice. thank
