### ISSUE TITLE
Login with another Nextcloud-instance via OAuth2?

### ISSUE THREAD

**Issue by githubkoma** [zorn-v/nextcloud-social-login#98]
Dear zorn-v,
many many thanks for your plugin!

is it possible to do the oauth2 login with another nextcloud instance?

i was unable to find a working scheme, while already using rocketchat to login via nextcloud successfully..

best regards,
me

**Comment by zorn-v** [comment]
What you mean about "another instance" ?

**Comment by githubkoma** [comment]
@zorn-v 
NextcloudA: with Social Login App
NextcloudB: acting as OAuth2 Provider

UserB has an Useraccount on NextcloudB.

-> Is the following possible, and if yes, how?
     UserB wants so login to NextcloudA with NextcloudB with OAuth2..

P.S.: I already have a Rocketchatserver, that successfully allows authentication through NextcloudB with OAuth2..
But for Nextcloud-to-Nextcloud OAuth2 Authentication i didnt find out a working scheme..

**Comment by zorn-v** [comment]
Nobody wants, so closed
